### ISSUE TITLE
Question about console ui post build.

### ISSUE THREAD

**Issue by deflinhec** [heroiclabs/nakama#1006]
I'm have my own console ui version upgraded to Angular 15, which encouters an issue of showing directory list of files after page reloads. For the fix of this issue I changed the baseHref to `/` instead of `static/` within angular.json and remove this post build. Is this post build necessary or I may break something else which I didn't aware? 

https://github.com/heroiclabs/nakama/blob/f2588f2fb6172a5693106af7491f5ea7da37134b/console/ui/package.json#L8

**Comment by novabyte** [comment]
@deflinhec Can you contribute back to the project your upgrade to Angular 15? Thanks 🙏

**Comment by deflinhec** [comment]
PR #1008

**Comment by deflinhec** [comment]
By the way, most of the changes are made automatically during the upgrade process. I was intergrating vanillia-jsoneditor with some dependecies issue, so I decided to upgrade to Angular 15.

**Comment by deflinhec** [comment]
Since https://github.com/heroiclabs/nakama/pull/1008 has been merged, I'll close this issue.
