### ISSUE TITLE
Cockroach dump and insert failing

### ISSUE THREAD

**Issue by ulasbilgen** [heroiclabs/nakama#101]
## Description
Cockroach dump and insert is not working as intended.

## Steps to Reproduce
1. Get a data and schema dump from a nakama db:
$ sudo cockroach dump nakama > nakamabackup.sql --insecure
2. Create a new DB to insert the data
cockroach sql -e 'CREATE DATABASE nakamaTest'
3. Try to insert the data dumped in the first step
$ sudo cockroach sql --database=nakamaTest < nakamabackup.sql --insecure

## Expected Result
You should be getting an output similar to this;
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
INSERT 1
INSERT 28
INSERT 3
INSERT 64
INSERT 10
INSERT 10
INSERT 10

## Actual Result
You'll get an output like this;
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
pq: referenced table "users" not found
Error: pq: referenced table "users" not found
Failed running "sql"

## Issue detail and workaround
This happens because user_devices table create script is actually before users create script. If you move this create script after CREATE TABLE users. The table creation works. 

But again when the data insertion comes, the order is wrong again, and because of the foreign key constrain, the script fails at that stage. So moving INSERT INTO user_device (id, user_id) VALUES to the end of the script provides a workaround. 

But I'm guessing when you have lots of users you can't really mess with the script that easily.

## Your Environment
$ cockroach version
Build Tag:    v1.0.1
Build Time:   2017/05/25 15:17:49
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.1
C Compiler:   gcc 6.3.0
Build SHA-1:  50fd18dcf8da75a0f4980344a885fe6105d0cf23
Build Type:   release

$ nakama --version
0.14.0-dev+40da17a

**Comment by ulasbilgen** [comment]
I'm guessing dumping and importing tables one by one will be an other workaround. Didn't try it though.

**Comment by novabyte** [comment]
This isn't something we can solve. It's an issue with the referential constraints applied as the schema is imported into the database server. I think if it's still an issue it should be reported on the cockroachdb repo.
