### ISSUE TITLE
[Feature Request] need beforehook  on PartyJoin

### ISSUE THREAD

**Issue by hexun80149128** [heroiclabs/nakama#1019]
https://forum.heroiclabs.com/t/how-to-ensure-that-a-player-can-only-join-at-most-one-party/3842/2
Since we need ensure player can only join a party.thanks

**Comment by jonbonazza** [comment]
I'm looking through the interface for the Go runtime library here: https://github.com/heroiclabs/nakama/blob/master/server/runtime.go

and I don't see any before or after party event hooks. Was this removed?

**Comment by mofirouz** [comment]
@jonbonazza the file you've linked is for specific API calls that are request/response models. As Party is on the socket, it is "message" based and therefore the link @zyro mentioned is correct to follow.
