### ISSUE TITLE
Issue: Version Mismatch after Upgrading Nakama from 3.14 to 3.16

### ISSUE THREAD

**Issue by yograterol** [heroiclabs/nakama#1023]
## Description

Greetings,

I've recently upgraded Nakama from version 3.14 to 3.16. Post upgrade, I'm encountering an error related to the version of github.com/cespare/xxhash/v2.

Upon investigation, I noted that Nakama 3.14 was using version v2.1.2 of github.com/cespare/xxhash/v2, whereas the newer Nakama 3.16.0 is utilizing version v2.1.1. I am curious to understand the reason behind this version downgrade.

Any assistance or clarification on this would be appreciated.

## Steps to Reproduce
Upgrade 3.14 to 3.16

**Comment by novabyte** [comment]
@yograterol "cespare/xxhash/v2" is a transitive dependency in our codebase which means its subject to the constraints of [minimal version selection](https://go.dev/ref/mod#minimal-version-selection) in the Go dependency resolver. As a result we haven't adjusted this dependency ourselves but it may have been adjusted automatically as a result of one of our other dependencies changing.

We don't guarantee our dependency tree as a backwards compatibility guarantee of the server. You can follow our guide on how to pin transitive dependencies to match what Nakama uses here:

https://heroiclabs.com/docs/nakama/server-framework/go-runtime/go-dependencies/

Hope this helps.
