### ISSUE TITLE
GoogleAuth requires player ID remapping for Google's Next Generation User IDs

### ISSUE THREAD

**Issue by DaveOak** [heroiclabs/nakama#1033]
Google have introduced "Next Generation Player IDs" which give each player a unique and different ID for each game.
Existing games have been using the player's actual Google ID but the Google API is changing and supplying the new ID instead.
In order to allow game server's to remap the database and not lose track of player status, they are providing both IDs side by side, at least for now.

Nakama should look up player's using the original ID (if specified), and if it exists change it to the new ID.

Some background on the problem here:
https://forum.heroiclabs.com/t/new-google-auth-returns-incorrect-google-id/3876

Google documentation on the player record, specifically originalPlayerId:
https://developers.google.com/games/services/web/api/players?hl=es-419

**Comment by novabyte** [comment]
@DaveOak Would you be interested to make a code contribution to Nakama? Contributors are always welcome 🙏

**Comment by DaveOak** [comment]
Yes, I've been trying to set up a dev environment for it between other tasks. I'll let you know if I need some pointers on getting it going.Sent from my Galaxy
-------- Original message --------From: Chris Molozian ***@***.***> Date: 29/05/2023  18:48  (GMT+00:00) To: heroiclabs/nakama ***@***.***> Cc: Dave Walker ***@***.***>, Mention ***@***.***> Subject: Re: [heroiclabs/nakama] GoogleAuth requires player ID remapping for Google's Next Generation User IDs (Issue #1033) 
@DaveOak Would you be interested to make a code contribution to Nakama? Contributors are always welcome 🙏

**Comment by zyro** [comment]
Fix merged as #1035. Nice find @DaveOak!
