### ISSUE TITLE
Know a friend online simply 

### ISSUE THREAD

**Issue by DungDajHjep** [heroiclabs/nakama#104]
## Description
I want to know who is online on my list friend( same steam friend), and i can invite him play game with me.

## Context

- [x] Unity
- [ ] Unreal
- [ ] Other

**Comment by novabyte** [comment]
This was added in the [1.4.0 release](https://github.com/heroiclabs/nakama/releases/v1.4.0).

You can now check the `LastOnlineAt` timestamp to see if it's non-zero. It will indicate whether the user is online. This is added to friends, group members, and bulk fetch of user records.
