### ISSUE TITLE
Storage problem in V3.17

### ISSUE THREAD

**Issue by mamaliw** [heroiclabs/nakama#1070]
https://github.com/heroiclabs/nakama/commit/06ed00f6c040000e3fa5915fb1f1820a6dae2d9d#r123822115

**Comment by zyro** [comment]
[Fixed on master](https://github.com/heroiclabs/nakama/commit/d5f76b74b6bf6095c9449ffddd030c0004a61158#diff-f225e823db8c56c68c2c0d73e1c0502f63009e845aff3d656545ba6bcea9ee5c) and will be part of the next release.

**Comment by redbaron** [comment]
Your comment is on the read function, but you call write function and that's were error is generated.

I'll try to replicate this problem with arguments you've provided in the commenct. Which DB version do you use?
