### ISSUE TITLE
nakama --version shows bogus info

### ISSUE THREAD

**Issue by jan-ekholm** [heroiclabs/nakama#1071]
When building a Nakama from sources the version info built in to the binary seems to be bogus or just hasn't been updated in forever.

```bash
% wget https://github.com/heroiclabs/nakama/archive/refs/tags/v3.17.0.tar.gz
% tar zfx v3.17.0.tar.gz
% cd nakama-3.17.0
% go build -trimpath -mod=vendor
% ./nakama --version
3.0.0+dev
```

Expected value is `3.17.0`.

**Comment by novabyte** [comment]
@jan-ekholm The version number is never set when you build from source and has not been set. This is not bogus but as intended. You can have a look at our build instructions if you're curious about how its set.

Recent versions of Go have introduced the new Go package: https://pkg.go.dev/debug/buildinfo. It's been on the backlog to update to it if possible so pull requests are always welcome 😄

**Comment by jan-ekholm** [comment]
The build instructions https://github.com/heroiclabs/nakama/blob/master/README.md#simple-builds do not seem to mention anything about the version. The instructions do however tell you to do `./nakama --version` to verify that the binary was built correctly. Personally I find it pretty confusing when a freshly compiled binary does not show the same version as the package I just downloaded.
