### ISSUE TITLE
Help button in console config page points to 404 page

### ISSUE THREAD

**Issue by Coxcopi** [heroiclabs/nakama#1072]
## Description

When clicking on the little question mark icon in the web consoles config page, it forwards to **https://heroiclabs.com/docs/install-configuration/#**, which results in a 404 error message.

The link seems to have moved, and I believe the configuration docs are now at **https://heroiclabs.com/docs/nakama/getting-started/configuration/**.

Just a minor issue and probably pretty easy to fix as well, just thought I'd report it anyways.

## Your Environment

- Nakama: 3.16.0 (latest docker image)

**Comment by mofirouz** [comment]
Thanks for reporting this. Are you sure the Nakama version is 1.27.0? As that doesn’t exists?

**Comment by flaviofernandes004** [comment]
README's link needed to be updated. Here is the PR: https://github.com/heroiclabs/nakama/pull/1131

**Comment by sesposito** [comment]
Resolved by https://github.com/heroiclabs/nakama/pull/1098
