### ISSUE TITLE
Steam Web API

### ISSUE THREAD

**Issue by SmallImpactGames** [heroiclabs/nakama#1076]
Could the address be swapped for the Steam web api? (Relating to Steam Auth&Linking)

From api.steampowered.com 
To partner.steam-api.com

Steams lame, 
Both can use a publisher key but the partner endpoint has higher availability and less prone to throttling.
https://partner.steamgames.com/doc/webapi_overview

**Comment by novabyte** [comment]
@SmallImpactGames Thanks for the suggestion. We'll make the change 👍
