### ISSUE TITLE
why nakama can not debug in goland

### ISSUE THREAD

**Issue by jiangben** [heroiclabs/nakama#1093]
i clone source code
and config like this。
![image](https://github.com/heroiclabs/nakama/assets/11189356/7c027a2c-4b61-4fb5-82cf-1312678a7886)

whe i run go build main.go and set a breakpoint .
then  i get error like this。
![image](https://github.com/heroiclabs/nakama/assets/11189356/86f44320-bf6c-478b-9005-71d7d0aec457)

We can't debug Nakama's source code directly. We can only embed it in a Docker runtime.
why？ why？

**Comment by zyro** [comment]
[The forum](https://forum.heroiclabs.com/) is a better place for general discussion, please post there.

**Comment by jiangben** [comment]
> [The forum](https://forum.heroiclabs.com/) is a better place for general discussion, please post there.

thx u . posted already
