### ISSUE TITLE
how to get the party Presence

### ISSUE THREAD

**Issue by lizhug** [heroiclabs/nakama#1115]
when a party owner(A) create a party, the return data is the party data include party presense, when he invite a new member(B),i need to show the both two members in the room(UI layer) so i need to get the new Presenses for both A and B to show UI Element in the game,but there's not a socket api to get the party data(ReceivedPartyPresence only return the new member, not the list of all member in the party) please help

**Comment by zyro** [comment]
@lizhug Questions and discussion belong on [the forum](https://forum.heroiclabs.com/), please open a thread there if you don't find one that already matches. 👍
