### ISSUE TITLE
Can't ping cockroachdb

### ISSUE THREAD

**Issue by gustavotero7** [heroiclabs/nakama#112]
Hi, I'm trying to run nakama but whrn I try to run `nakama migrate up` or `make dbstart nakama_12345` I get the following error 
```
root@vm:~# nakama --database.address user:password@localhost:26257 make dbstart nakama_cws
{"level":"warn","ts":"2017-09-08T16:49:01.342+0200","msg":"WARNING: insecure default parameter value, change this for production!","param":"socket.server_key"}
{"level":"warn","ts":"2017-09-08T16:49:01.342+0200","msg":"WARNING: insecure default parameter value, change this for production!","param":"session.encryption_key"}
{"level":"warn","ts":"2017-09-08T16:49:01.342+0200","msg":"WARNING: insecure default parameter value, change this for production!","param":"runtime.http_key"}
{"level":"info","ts":"2017-09-08T16:49:01.342+0200","msg":"Nakama starting"}
{"level":"info","ts":"2017-09-08T16:49:01.342+0200","msg":"Node","name":"nakama-945a","version":"1.0.1+9d6196f"}
{"level":"info","ts":"2017-09-08T16:49:01.342+0200","msg":"Data directory","path":"/root/data"}
{"level":"info","ts":"2017-09-08T16:49:01.342+0200","msg":"Database connections","dsns":["master:ChimeraDev13@localhost:26257"]}
{"level":"fatal","ts":"2017-09-08T16:49:01.344+0200","msg":"Error pinging database","error":"pq: cleartext connections are not permitted","stacktrace":"nakama/vendor/go.uber.org/zap.Stack\n\tvendor/go.uber.org/zap/field.go:209\nnakama/vendor/go.uber.org/zap.(*Logger).check\n\tvendor/go.uber.org/zap/logger.go:273\nnakama/vendor/go.uber.org/zap.(*Logger).Fatal\n\tvendor/go.uber.org/zap/logger.go:208\nmain.dbConnect\n\tmain.go:157\nmain.main\n\tmain.go:81"} 
```

In this case, I have specified the DB address with --database.address, also the DB nakama_cws exists and is have granted all permissions 

**How can I do t correctly?** I have installed secured cockroachdb with a single cluster (https://www.cockroachlabs.com/docs/stable/manual-deployment.html) and have created the user and DB with all permissions granted.

**Comment by mofirouz** [comment]
@gustavotero7 What is `make dbstart nakama_cws` ?

I think it's best to speak directly via [Gitter](https://gitter.im/heroiclabs/nakama).

**Comment by gustavotero7** [comment]
@mofirouz to connect to a db (`nakama make dbstart nakama_cws`), I will ask trough gitter also, thanks

**Comment by mofirouz** [comment]
Also you need to start cockroach with `--insecure` as Nakama does not support secure connection to the database (as the database is supposed to be secured behind a firewall). The error message suggests that:

`pq: cleartext connections are not permitted`

Have a look at this: https://github.com/heroiclabs/nakama/blob/master/Makefile#L138

**Comment by gustavotero7** [comment]
Got it, thanks
