### ISSUE TITLE
Confirm Account Delete

### ISSUE THREAD

**Issue by delasource** [heroiclabs/nakama#1123]
Please add a confirmation modal when deleting (recorded delete) a user account in Nakama Console, to prevent accidential button press.

**Comment by mofirouz** [comment]
@delasource Yes that would be great; If you could create a PR, happy to accept contributions. Would be good to have it across multiple permanent-delete components in the UI. Thank you.

**Comment by delasource** [comment]
I only know a little about Go and even less about Angular. So I'm the wrong person for this (:

**Comment by xinatcg** [comment]
@mofirouz  PR submitted, hope this feature can be added in the near future.

**Comment by sesposito** [comment]
Resolved in https://github.com/heroiclabs/nakama/pull/1197
