### ISSUE TITLE
TournamentRecordWrite adds to leaderboard cache even if there isnt't a new score

### ISSUE THREAD

**Issue by robtraynor** [heroiclabs/nakama#1124]
## Description

I was getting an error where an incorrect Rank was being returned by TournamentRecordsList, and I think I've tracked it do to  
TournamentRecordWrite, updating the rank cache even if the score isn't used.

In the case where the score isnt updated and the leaderboard is doesnt require a join  ` rankCache.Insert`  is always called:
```
	record.Rank = rankCache.Insert(leaderboard.Id, leaderboard.SortOrder, record.Score, record.Subscore, oldScore, oldSubscore, expiryUnix, ownerId)

```
in core_tournament.go.

In this case oldScore and oldSubscore are zero, since they are set from the result of the database update which is empty in the case where there is no update. Meaning that when the rankCache looks to delete the old entry there are no matches and instead it is added. 

I can create pull request to fix if you want by adding logic similar to core_leaderboard.go and calling `rankCache.Get`, if there hasn't been an update, but im not sure if this logic would need to be mirrored in the requiredJoin branch for cosistency.

## Steps to Reproduce

1. Set up a tournament without required join and operator set to best
2. Use any client to call TournamentRecordWrite
3. Call TournamentRecordWrite again with a lower score

## Expected Result
The rankCache for the leaderboard should contain one entry

## Actual Result
The rankCache for the leaderboard contains two entries

**Comment by zyro** [comment]
@robtraynor Nice find, this makes sense. The rank cache entries are definitely intended to be unique so if there's a situation that adds an entry without removing the previous one, that's not intended.

A PR would be awesome! 🙏

**Comment by zyro** [comment]
Off the top of my head I think `max_num_scores` is meant to be the submitted count full stop, improved or not. I need to look into it to be sure. 👀 

That sounds like a separate issue though, right? If memory serves the number of scores doesn't affect rank and/or rank caching.

**Comment by robtraynor** [comment]
I think if the score is not an improvement, the values passed to the rank cache for the old values will always be 0, since the insertion to the cache tries, therefore it cant find it to remove it from the cache and instead adds a new one. and since the insertion to the cache tries to since they are set from the result of query which fails due to the WHERE condtion which only updates the value if it's better. So I think while they are two seperate issues but caused by the same issue.

**Comment by robtraynor** [comment]
@zyro Hey just wondering if there is an update?

**Comment by flaviofernandes004** [comment]
Sorry, I closed this by mistake.
