### ISSUE TITLE
Test Eorror with Metrics

### ISSUE THREAD

**Issue by jiangben** [heroiclabs/nakama#1129]
.\match_common_test.go:56:18: cannot use &testMetrics{} (value of type *testMetrics) as Metrics value in argument to NewLocalMatchRegistry: *testMetrics does not implement Metrics (missing method GaugeStorageIndexEntries)
.\matchmaker_test.go:1658:181: cannot use metrics (variable of type *testMetrics) as Metrics value in argument to NewRuntime: *testMetrics does not implement Metrics (missing method GaugeStorageIndexEntries)

**Comment by maciejmrozinski** [comment]
I added fixes for this in my PR: https://github.com/heroiclabs/nakama/pull/1128

**Comment by zyro** [comment]
Fixed in 2f1882387b375742360ada136ac69c584e55265d ahead of the 3.19.0 release.
