### ISSUE TITLE
[Lua] Math.log Not working correctly

### ISSUE THREAD

**Issue by AleksandarEri** [heroiclabs/nakama#1143]
## Description
Using math.log with base for example 2, does not yield correctly results..

## Steps to Reproduce
Example:
Create new lua script and past following code:

> local bitmask = {1,2,4,8,16,32,64,128,256,512,1024,2048}
> for i=1,#bitmask do 
>     print("Type: " ..tostring(type(bitmask[i]))..":"..tostring(bitmask[i]))
>     print("Checking Mask: ")
>     local index = math.log(bitmask[i], 2)
>     print("Index: "..index)
> end

## Expected Result
Running the same script in stock lua 5.1 should or in nakama should give following results.
![image](https://github.com/heroiclabs/nakama/assets/55407031/7e19f867-1478-402f-8b84-2fd696f75560)

## Actual Result
Notice in the console how for each bit mask, different float value will be given as output..Sometimes negative number may appear i suspect it takes waht ever is it at cache/memory in that moment.
![image](https://github.com/heroiclabs/nakama/assets/55407031/c4472219-6527-438b-b01e-df25ae36d41e)

## Context

- [X] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: 3.17.1
- Database: cockroach 23.0
- Environment name and version: Docker Desktop
- Operating System and version: Windows 10

**Comment by adrmcintyre** [comment]
It seems to me that two-argument log was only added to lua in version 5.2, so you're getting log base e, and the results are as expected. Compare the documentation for math.log in https://www.lua.org/manual/5.1/manual.html vs https://www.lua.org/manual/5.2/manual.html.

**Comment by AleksandarEri** [comment]
@adrmcintyre This is correct. in our IDE lua is set to 5.2 while cmd is saying 5.1 so from there went confusion. Can be marked closed.
