### ISSUE TITLE
Starting problems with nakama server

### ISSUE THREAD

**Issue by blacklightknight** [heroiclabs/nakama#115]
I am using nakama server inside docker on a mac environment.
I went through the documentation of nakama server which I found very descriptive but I was not able to use the Full Android example on this link 
https://heroiclabs.com/docs/android-java-client-guide/
Can anyone provide a example or something so that I can get a Idea about it?

**Comment by novabyte** [comment]
@blacklightknight What trouble have you had with the Android example? Can you give more details?

**Comment by blacklightknight** [comment]
Actually I am a begginner with android studios and I am using it just to use nakama (since I don't know unity nor ios) so I have a very basic question that the code given on the link above is for the android client, but in the android also how exactly can we use this code, because what I can see that the part corresponding to 
` public NakamaSessionManager() {
    client = DefaultClient.builder("defaultkey").build();
    errback = new Callback<Error, Error>() {
      @Override
      public Error call(Error err) throws Exception {
        System.err.format("Error('%s', '%s')", err.getCode(), err.getMessage());
        return err;
      }
    };
  }`

seems like the code to create a session only,
then there is a getting the  Client reference  part then login with uid etc

but my question is that how how to use these different parts of the codes and where exactly to use them?
I know that it is quite a noob question but if you can just provide me with a starting it would be very helpful for me.
Thank you.

**Comment by blacklightknight** [comment]
I got one example, I have a activity with a editbox for taking user's input, and a login button. I want the user to give their name in this editbox and then on clicking on login I want the user to log in to the nakama server.

I was able to emulate this example within my system using sqlite database and android , but how to accomplish this with nakama server?

**Comment by zyro** [comment]
@blacklightknight Since this isn’t an issue with the core Nakama server or a bug in any of the clients I recommend we move the discussion to our [Gitter channel](https://gitter.im/heroiclabs/nakama). Jump on there and ping us, we’ll be happy to help.

**Comment by blacklightknight** [comment]
sure and sorry for the inconvenience caused.
