### ISSUE TITLE
Issue loading storage values in Nakama Console

### ISSUE THREAD

**Issue by jonbonazza** [heroiclabs/nakama#1155]
Before you submit an issue we recommend you drop into the [community forum](https://forum.heroiclabs.com) and ask any questions you have or mention any problems you've had getting started with the server.

Please provide as much information as you can with this issue report. If you believe it may be an issue with one of the client libraries please report it on their [own trackers](https://github.com/heroiclabs?utf8=%E2%9C%93&q=nakama%20AND%20sdk&type=&language=).

## Description
Since upgrading to Nakama 3.20 released a few hours ago, I have been experiencing an issue where the Nakama Console is unable to load storage entries. See the attached gif

![2023-12-15 16-50-18](https://github.com/heroiclabs/nakama/assets/1424843/2a05b655-3352-4216-ae4b-4d6393d8b94f)

The following error is present in the Nakama logs when this happens:

```
{"level":"error","ts":"2023-12-16T00:48:01.573Z","caller":"server/core_storage.go:494","msg":"Could not read storage objects.","error":"cannot convert [user_characters] to Text"}
emergence-nakama-nakama-1       | {"level":"error","ts":"2023-12-16T00:50:23.200Z","caller":"server/core_storage.go:494","msg":"Could not read storage objects.","error":"cannot convert [characters] to Text"}
emergence-nakama-nakama-1       | {"level":"error","ts":"2023-12-16T00:50:30.558Z","caller":"server/core_storage.go:494","msg":"Could not read storage objects.","error":"cannot convert [classes] to Text"}
```

This issue did not occur before upgrading.

## Context
- [ ] Unity
- [ ] Unreal
- [x] Other

This is just in the nakama console. No client was tested yet.

## Your Environment
- Nakama: 3.20.0
- Database: Cockroachdb v20.2
- Environment name and version: Go runtime module using go v1.21.5 and nakama-common 1.30.1 (module loads fine)
- Operating System and version: Windows 11 64-bit

**Comment by mofirouz** [comment]
Please upgrade to the latest cockroachDB and report back 🙏

**Comment by jonbonazza** [comment]
That indeed did the trick. Thanks. Out of curiosity, what changed?

**Comment by mofirouz** [comment]
We made changes to the storage engine queries as part of 3.18.0 release that added Storage Indexing: https://github.com/heroiclabs/nakama/releases/tag/v3.18.0
