### ISSUE TITLE
RPC code 16

### ISSUE THREAD

**Issue by mojoyup1528** [heroiclabs/nakama#1170]
I did a search and found three topics I though might be relative but Im not sure they are. The issue is, I came back in the morning to test server connection and I am now getting this error:=== Nakama : DEBUG === Sending request [ID: 2, Method: POST, Uri: http://127.0.0.1:7350/v2/storage, Headers: {Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhZTNjNDc2Ni1kZDEzLTRiYjAtOGE3Zi1kOTYxYTk4MjJkYjEiLCJ1c24iOiIxMjNAMTIzLmNvbSIsImV4cCI6MTcwNzY3MDIyMX0.cWm81cFAnz50cJZ0dg_eORCmYMBqkWntHJNyrNsVmQk}, Body: {"object_ids":[{"collection":"player_data","key":"last_character","user_id":"ae3c4766-dd13-4bb0-8a7f-d961a9822db1"}]}, Timeout: 3, Retries: 3, Backoff base: 10 ms]
=== Nakama : DEBUG === Freeing request 2
=== Nakama : DEBUG === Request 2 returned response code: 401, RPC code: 16, error: Auth token invalid

I tried refreshing everything but nothing has worked yet. This is for Godot 3.5.3 using Nakama 3.20.1 windows amd64 with Docker Desktop installed. I followed the tutorial guided by GDQuest on your Youtube and everything worked yesterday and I did not change anything (PC only went into sleep mode). Came back and now authentication doesnt seem to work. 

I am not great at understanding the backflow too well yet but maybe its a common issue? Ill give more info if needed :)

To reproduce, all I did was made sure everything worked yesterday then shut down the server at night and stopped Godot running and put my computer to sleep so no Nakama was active at the night time. Came back this morning and loaded server, had a few issues with prometheus loading at first then after a few tries it worked, then loaded back Godot and ran multirun for two instances and even on single run it came up with the error for authentication. I noticed in the cmd, that if you see here: 

nakama-1       | {"level":"info","ts":"2024-02-11T14:58:01.016Z","caller":"main.go:175","msg":"Startup done"}
prometheus-1   | ts=2024-02-11T14:58:13.918Z caller=compact.go:521 level=info component=tsdb msg="write block resulted in empty block" mint=1707624000000 maxt=1707631200000 duration=16.961189ms
prometheus-1   | ts=2024-02-11T14:58:13.919Z caller=head.go:1325 level=info component=tsdb msg="Head GC completed" caller=truncateMemory duration=674.792µs
prometheus-1   | ts=2024-02-11T14:58:13.919Z caller=checkpoint.go:100 level=info component=tsdb msg="Creating checkpoint" from_segment=19 to_segment=20 mint=1707631200000
prometheus-1   | ts=2024-02-11T14:58:13.929Z caller=head.go:1287 level=info component=tsdb msg="WAL checkpoint complete" first=19 last=20 duration=9.984437ms

after "Startup done", usually nothing else pops up until I try to connect but after a few seconds, the other info popped up before doing anything. Maybe related? In the Docker, everything is running. 

I think thats about all. Let me know what else you need to help!

**Comment by mofirouz** [comment]
This is not a Nakama issue. Please kindly ask this question on the forum.
