### ISSUE TITLE
It is necessary to prevent deletion of a system user.

### ISSUE THREAD

**Issue by JCtapuk** [heroiclabs/nakama#1177]
Because I accidentally deleted the system user and there was no way to restore it, I had to create it in the database manually
Prevent deleting a system user via the rpc "Delete Account" call to delete a system user.

**Comment by novabyte** [comment]
@JCtapuk This looks like a simple change to make to guard the system user, can you share more on how you deleted the system user? What did your code look like?

**Comment by JCtapuk** [comment]
![image](https://github.com/heroiclabs/nakama/assets/61321608/ac51eae1-9acf-4d53-8139-92e10d683cc2)
