### ISSUE TITLE
Allow to call match creation in run_once

### ISSUE THREAD

**Issue by JCtapuk** [heroiclabs/nakama#1178]
During the call to run_once I create a match to pre-register but it freezes and the program crashes.
Example code lua
```lua
local nk = require("nakama")

nk.run_once(function()
  nk.match_create('test')
end)
```

If you know any alternative ways, I will be glad.

**Comment by sesposito** [comment]
Hello @JCtapuk, I'm unable to reproduce, can you give a full example of all of your code? What error are you getting?

**Comment by sesposito** [comment]
Closing the issue, please re-open if you can provide a full reproducible example on the latest Nakama version.
