### ISSUE TITLE
Why does the document say that After hooks are executed asynchronously but the code doesn't?

### ISSUE THREAD

**Issue by yaohuiwu** [heroiclabs/nakama#1181]
## Description
Why does [the document](https://heroiclabs.com/docs/nakama/server-framework/introduction/hooks/#after-hooks) say that After hooks are executed asynchronously but the code doesn't?

## Steps to Reproduce
See the code:

         //server/api_authenticate.go line 246~254
	// After hook.
	if fn := s.runtime.AfterAuthenticateDevice(); fn != nil {
		afterFn := func(clientIP, clientPort string) error {
			return fn(ctx, s.logger, dbUserID, dbUsername, in.Account.Vars, exp, clientIP, clientPort, session, in)
		}

		// Execute the after function lambda wrapped in a trace for stats measurement.
		traceApiAfter(ctx, s.logger, s.metrics, ctx.Value(ctxFullMethodKey{}).(string), afterFn)
	}

         //server/api.go line 588~596
         func traceApiAfter(ctx context.Context, logger *zap.Logger, metrics Metrics, fullMethodName string, fn func(clientIP, clientPort string) error) {
	        clientIP, clientPort := extractClientAddressFromContext(logger, ctx)
	        start := time.Now()
        
	        // Execute the after hook itself.
	        err := fn(clientIP, clientPort)
        
	        metrics.ApiAfter(fullMethodName, time.Since(start), err != nil)
        }

## Expected Result
asynchronously

## Actual Result
synchronously

## Context
- [ ] Other

## Your Environment

- Nakama: 3.20.1
- Database: [X.X.X](postgres:12.7)
- Environment name and version:
- Operating System and version:

**Comment by novabyte** [comment]
@yaohuiwu We'll clarify the documentation to be more accurate (cc @heroiclabs/devrel) but to clear up the confusion, IIRC the code runs within the same Goroutine which handled the request from the socket acceptor but does not wait or prevent a response from the API to be sent back to the client. Its execution is independent to the socket response rather than strictly asynchronous. Hope that helps.

**Comment by sesposito** [comment]
@yaohuiwu strictly speaking, what @novabyte said and what the documentation states holds true for after hooks that are registered to execute after a function has been invoked via a real-time message (`RegisterAfterRt`). 

For after hooks registered to fire after HTTP API calls, as you point out, the API call will only return after the after hook has executed, so the response is not sent asynchronously. We've filed a ticket to improve the documentation around hooks.
