### ISSUE TITLE
[Feature Request] Official Goland Debugging Support PLEASE !

### ISSUE THREAD

**Issue by baledreamcastau** [heroiclabs/nakama#1199]
Nakama is really a great open source server framework and i really want to use it for my start up project.

However, the debugging support is REALLY bad !!!

 i am very noob to programming and i dont want to debug with cmd line because it makes my life much harder.

The debugging support for VisualStudio is not visualized at all you still have to look a the debugger for the current line delve is at.

Please, support goland debugging officially, i really dont want to quit using Nakama because of lacking of debugging suport

**Comment by zyro** [comment]
We've recently revamped our official [Debugging with Delve](https://heroiclabs.com/docs/nakama/guides/server-framework/debugging-with-delve/) documentation page! 🎉 

That documentation page should have everything needed to get started and productive with a debugger workflow.
