### ISSUE TITLE
Nakama DX using Docker

### ISSUE THREAD

**Issue by exotexot** [heroiclabs/nakama#1208]
I find using Nakama and Docker very bad.
I'm using Typescript to write Nakama Server stuff and there is no way you can update things quickly. When you edit files, you will STILL need to rebuild the entire docker container to see your updates, even though you have an exposed docker volume that is actually MEANT to share data across host and docker container. 

Maybe I'm just missing something, but I feel like this is something that can be  improved. 

- Nakama: 3.21.1
- Database: Cockroach-23.1
- Environment name and version:
- Operating System and version: MacOS, Dockerised nakama application

**Comment by zyro** [comment]
What you're describing should work just fine, if you've bound a volume to your host environment that should work fine. All you would need to do is restart the Nakama container.

If you're using a Dockerfile to bundle Nakama plus your TS/JS output into a new image together, then yes you need to rebuild that each time.

**Comment by exotexot** [comment]
Ah, that's actually good to know! Still not ideal but restarting the container is much faster than rebuilding. 
Thanks for letting me know!
