### ISSUE TITLE
Nakama Client SDKs should append port after host name instead of after full host path

### ISSUE THREAD

**Issue by smsunarto** [heroiclabs/nakama#1221]
Currently, the Nakama client SDK will naively append the passed-in port after whatever is passed in as the host paramater

For example:

```
var client = new Nakama.Client("http", "127.0.0.1", 7350, "defaultkey");
```

will produce http://127.0.0.1:7350. Which works out just fine.

---

However, this becomes a problem when you use a path-based load balancer:

```
var client = new Nakama.Client("http", "example.com/nakama", 7350, "defaultkey");
```

The client SDK will append the port after the full path instead of the hostname, therefore producing -> http://example.com/nakama:7350 which is invalid. It should've been http://example.com:7350/nakama

Would be great if we can cover this edge case :D

**Comment by zyro** [comment]
This looks valid, but should be opened against the relevant SDK repo rather than server - please open the issue there if needed.

Worth noting we typically run servers at the root of a subdomain, rather than on a path, but I don't see any harm in supporting this if possible.
