### ISSUE TITLE
Nakama MP service - with respect to Paradox Interactive Accounts

### ISSUE THREAD

**Issue by JGFMK** [heroiclabs/nakama#1236]
I asked [Paradox](https://support.paradoxplaza.com/hc/en-us/requests/299550) 
Is my router MAC address or IP address possibly blacklisted by you? Is this the reasons for the disconnects?

A member of their helpdesk responded:

No, it is not. You are connecting to an external MP service called Nakama. We in Paradox have no way to block or blacklist anyone on their servers, only Nakama could do that.

Not understanding what MP meant, I went in search of it within the context of Nakama.
I found this post:
https://www.reddit.com/r/hoi4/comments/wvjc92/what_is_nakama_mp/

There are a couple of answers that jumps out at me:
1) nakama mp is for **crossplay** with microsoft pp store 
2) Also **it gets rid of most multiplayer connection**s, or at least when I was having issues swapping over helped

It's specifically the cross play and getting rid of multiplayer connections:

I have a PS5 that has CK3.
I have a Windows 11 laptop that has Stellaris on it.

https://beta-accounts.paradoxinteractive.com/profile
shows this:
<img width="810" alt="Screenshot 2024-06-26 at 05 20 24" src="https://github.com/heroiclabs/nakama/assets/14791808/98bc1e50-8450-45a5-a219-11426374cffc">

Could this perhaps explain some of the odd log messages in my BT Home Hub router?:

```
WHW INFO A station (Smart Hub 2)IF[2.4G](<Router MAC address - AFAIK>):STA(<Razer 18 MAC address>)(Legacy Device) join WHW infrastructure
5G client Mac: <Razer 18 MAC address> Deauthentications (Reason:Deauthenticated because sending station is leaving (or has left) IBSS or ESS)
Self roaming might be occurring... Deauth original one...
```

netwaw14 Messages in the Windows 11 event viewer correspond to the messages in the router logs for the same timestamp. System Event_ID chronology 7021(Info),7003 (Info), 6062 (Warning)

I have been trying to unravel this for more than 2 weeks going down several rabbit holes with the parties Razer, Intel, Microsoft, BT, Paradox Interactive:

**Maybe this is why I keep getting disconnected at my home and not elsewhere like at my sisters house (No triple netwaw14 event log entries when playing there)?**

I have been posting about this, thinking it was an Intel Wi-Fi network adapter bug (search for JGFMK posts)  
See here:
https://community.intel.com/t5/Wireless/Netwtw14-Cannot-be-Found/m-p/1605423
And here:
https://community.intel.com/t5/Wireless/The-description-for-Event-ID-7021-from-source-Netwtw12-cannot-be/td-p/1481659

I have no idea about the environment - since this would be in the realm of Paradox.

My PS5 isn't even connected to my router at the moment, since I changed the Wi-Fi password because of the following message when trying to play Stellaris and haven't reconnected the device. I disconnected every device at the router level and gradually re-added devices to it:
![Screenshot 2024-06-10 171606](https://github.com/heroiclabs/nakama/assets/14791808/069a63aa-12d7-436f-93e2-bf0bd1d8fe31)
I often can barely play the game for about 7 minutes before this happens, making £217 worth of Stellaris PC game + DLCs unplayable and £4400 laptop unusable for the purpose I bought it. Not to mention a laptop cooler, leather case, NVMe enclosure  - bringing combined total to near £5000 [for the lemon this has created](https://www.reddit.com/r/razer/comments/1dnxxav/razer_18_2024_and_windows_update_hell_due_to/).

**Your feedback/advice is requested?**

This is really impacting a huge number of people and messing up Windows Updates causing BSODs too. So it's quite a nasty issue.

**Ideally there is something the Nakama MP server can do to realise my PS5 isn't even connected to my router or even switched on before the inference I am. This obviously should work in reverse too (PS5 in use, laptop not in use - at the open game level).**

If it does appear to be cross-platform related, is the simplest way to unlink a hardware platform from my paradox account every time I want to play specific platform games. Perhaps have 2 paradox accounts, 1 per platform? Not sure if I can spoof it by gmail account with suffix - normally used to track where spam originates from/get rid of spam emails by removing the suffix association later.

**Comment by sesposito** [comment]
Hello @JGFMK, this is not a Nakama issue so I'll closing this thread, but please reach out at support@heroiclabs.com and we'll see if there's anything we can do to help.

**Comment by JGFMK** [comment]
Intel have also provided a driver update today, that is not yet on the windows update site.
https://www.intel.com/content/www/us/en/download/19351/intel-wireless-wi-fi-drivers-for-windows-10-and-windows-11.html
This for now seems to have cured the issue. I'll keep you posted/the people at the support email if I continue to get issues.
