### ISSUE TITLE
Release ARM versions of binary

### ISSUE THREAD

**Issue by sercand** [heroiclabs/nakama#126]
Currently, only amd64 architecture is deploying for three platforms. Releasing arm64 and arm binaries for Linux enables using Nakama on Raspberry PI. CoachroachDB [only supports 64-bit platforms](https://github.com/cockroachdb/cockroach/issues/8179) therefore only arm64 would be sufficient.

**Comment by digimbyte** [comment]
I second this, while on full production I might use a dedicated service like Amazon with Nakama - but without roadtesting it during development to see if it works for us, we can't confidently develop for it. Prototyping on arm7/8 processors, not just the common and popular raspberry pi, but Chip pro and BeagleBone are highly desirable for early stages and internal development.

**Comment by novabyte** [comment]
@sercand @digimbyte The build system has been simplified down to just `go build -i` in the root of the repo. I'll make sure we produce ARM builds with our official releases as well but in the meantime you can build from source. Please re-open if you encounter any problems.

**Comment by sana2024** [comment]
> @sercand @digimbyte The build system has been simplified down to just `go build -i` in the root of the repo. I'll make sure we produce ARM builds with our official releases as well but in the meantime you can build from source. Please re-open if you encounter any problems.

hi, any update on this ?? do you have support for ARM64??
