### ISSUE TITLE
context.Env not available outside of registered function

### ISSUE THREAD

**Issue by brett-richardson** [heroiclabs/nakama#131]
## Use case

Wanting to create leaderboards on server boot based on configuration.
Currently there doesn't seem to be any way to access that context without registering a function.

It was mentioned that registering to a `after_boot` message might make sense?

```
local nk = require("nakama")
local names = nk.getEnv("LEADERBOARD_NAMES") or "" -- would be nice to have

for name in string.gmatch(names, "[^%s]+") do
    local id = nk.uuid_v4()
    local metadata = { name = name }
    nk.leaderboard_create(id, "asc", "", metadata, false)
end
```

**Comment by novabyte** [comment]
This has been implemented as a new function in the code runtime:

```lua
nk.run_once(function(context)
  print(context.env["KEY_NAME"])
end)
```

The `run_once` function is intended to provide startup logic like a `"main"` function.
