### ISSUE TITLE
Disallow multiple logins from the same user concurrently.

### ISSUE THREAD

**Issue by kingslayerkinght** [heroiclabs/nakama#132]
## Description
Same user login concurrently and there will be have two session .BUT ,in mostly game ,user just want to there just one.

## Context

- [x] Unity
- [ ] Unreal
- [ ] Other

- Nakama: 1.0.1
- Cockroach: 1.0.4

**Comment by mofirouz** [comment]
This is tracked in issue #42, closing in favour of that.
