### ISSUE TITLE
Message Delete Feature

### ISSUE THREAD

**Issue by xysverma** [heroiclabs/nakama#133]
Often is chat messages (Public, 1 to 1 or Group messages), we wish that some messages could be removed so that it becomes inaccessible for all users. Whats app very recently came up with similar [Delete Message feature](https://faq.whatsapp.com/en/android/26000068/)

It will be an interesting & very useful addon to Nakama server & client. As suggested by @novabyte  , a script could be a quick workaround for it but down the line, it would make much more sense if made part of Core features.

Thanks once again. Ticket created as advised in [gitter](https://gitter.im/heroiclabs/nakama)

**Comment by novabyte** [comment]
@xysverma This was added to the Nakama 2 release. It's available as a socket message which can be sent by the user who owns the message. I think it covers what we discussed ✔️
