### ISSUE TITLE
The match create callbacks on server do not work if the match was created via matchmaker

### ISSUE THREAD

**Issue by anthonymurraygd** [heroiclabs/nakama#137]
To reproduce this, try and register a function in the following way(s) via Lua:

nk.register_before(some_function, "tmatchcreate")
nk.register_after(some_other_function, "tmatchcreate")

If the match is created via the matchmaker, neither callback will occur. It would be great if these were triggered when a match is created by the user or through the matchmaker.

**Comment by PlangCoder** [comment]
I have the same problem

**Comment by mofirouz** [comment]
This is indeed a valid limitation at the moment, because of the way a matchId is created when done so by the matchmaker logic (which doesn't trigger the Lua VM). @zyro wdyt of adding this to the roadmap for a future release?

**Comment by zyro** [comment]
I like it in principle, but I'd like to understand more about what the callback functions are doing here. What sort of operations are you planning to do before/after match create @anthonymurraygd and @PlangCoder?

**Comment by anthonymurraygd** [comment]
In my case, I wanted to create a record that stores match data on match creation, with the ability to clean it up if there are no users left (via "tmatchesleave").

**Comment by anthonymurraygd** [comment]
Also, if this gets implemented, it would be great to know what caused the match related callbacks to occur, similar to #36

**Comment by Tatamethues** [comment]
any suggestion for to do it right now？

**Comment by novabyte** [comment]
@Tatamethues The best way right now would be to have the host client you select write the data record as soon as the match opponents are all connected. We'll add the hooks soon but we also have some big new features for multiplayer which will solve this problem.

**Comment by novabyte** [comment]
We added a dedicated callback function to interact on the server before results are sent back to clients from the matchmaker engine. This can be done like so:

```lua
local nk = require("nakama")
local function matchmaker_matched(context, matchmaker_users)
  -- create an authoritative match
  local match_id = nk.match_create("somematchmodule", { matched_opponents = matchmaker_users })
  return match_id
end
nk.register_matchmaker_matched(matchmaker_matched)
```
