### ISSUE TITLE
Why did you name the project "nakama"?

### ISSUE THREAD

**Issue by mastern2k3** [heroiclabs/nakama#138]
Me and my friend stumbled upon this amazing framework and were wondering why did you decide on this name?

Thanks in advance!

**Comment by novabyte** [comment]
hey @mastern2k3 Thanks for the kind words. We mention the project name on our docs [here](https://heroiclabs.com/docs/social-friends/):

> Nakama is a common Japanese word that directly translates to friend or comrade. Some believe the word means "people who are considered closer than family", though that is not a part of the official definition. We feel it expresses the kind of social communities we want developers to build into their games and apps!

The full story is that we're big fans of an anime called One Piece. If you're an anime fan give it a watch. 😉 Definitely drop into the [community](https://gitter.im/heroiclabs/nakama) and ask any questions.

**Comment by mastern2k3** [comment]
Me and my friend are also great fans of the show and started shouting in excitement when we read your comment. Will join the community without a doubt. Carry on with the  great work!
