### ISSUE TITLE
Admin function to blacklist an session token

### ISSUE THREAD

**Issue by Ceiyne** [heroiclabs/nakama#139]
There should be an admin function to blacklist/ban/force-expire a session token.  

Scenario: A game may have a lengthy session expiration (say a month or a year) so that users do not have to enter their credentials every time they play.  However, if a session token becomes compromised then there should be a straightforward way to mark it as invalid (prevent it from being logged into again).

I spoke with @novabyte about this in the gitter and he suggested I add it as an issue for tracking.

**Comment by novabyte** [comment]
@Ceiyne This was added to the server in the [3.2.0 release](https://github.com/heroiclabs/nakama/releases/v3.2.0). Both session and refresh tokens can be "disabled" with a logout call. There's also functions in the server framework to programmatically execute it as well when needed.
