### ISSUE TITLE
multicode package has bug in byte shifting and type casting.

### ISSUE THREAD

**Issue by TursMA** [heroiclabs/nakama#140]
Example:
Bug:
-	return uint16(uint32(buf[0]) | uint32(buf[1]<<8)), nil  //<-----buf[1] of type byte is shifted by 8 bits and we receive 0.

Fix:
+	return uint16(uint32(buf[0]) | (uint32(buf[1]) << 8)), nil

The same issue in ReadVariableLengthUint16
-		val |= uint16(b2 << 7)

+		val |= (uint16(b2) << 7)

The same issue in ReadPacketHeader (3 places)
-		ackBits |= uint32(b << 8)

+		ackBits |= (uint32(b) << 8)

Playgroud with fixes.
https://play.golang.org/p/5QOOLBfdO3b

**Comment by zyro** [comment]
@TursMA Thanks for pointing this out! Do you want to open a PR so we can make sure you get attribution for the changes?

**Comment by zyro** [comment]
Fixed by c0a311ca998731472c3282525b0f778c123ec106.
