### ISSUE TITLE
Notification id in OnNotification doesn't match one in database

### ISSUE THREAD

**Issue by mmvlad** [heroiclabs/nakama#142]
## Description
Nakama returns wrong id for notification in OnNotification callback

## Steps to Reproduce

In Unity I execute this code:
1. Client receives "Want to chat" request
2. Client receives "Friend request"

```
 _client.OnNotification = (INNotification notification) =>
{
    Log.Info(">>>>>Notification id: " + notification.Id);

    var message = NNotificationsListMessage.Default(100);

    _client.Send(message, set =>
    {
        foreach (var result in set.Results)
        {
            Log.Info("+++Notification id: " + result.Id);
        }
    }, error =>
    {
        Log.ErrF("Error listing notifications: Code [{0}] : Message [{1}]", error.Code, error.Message);
    });
};
```

I get this
[response](https://dl.dropboxusercontent.com/content_link/v5F9xBMU0i9aGO2dTqYvn0Nl0i0Er9SaMfiaoDuy63VCCVzXFHY6OnwEGmyk4jZL/file)

You can see that after first notification I get OnNotification callback with notification id **rklj...** but after I list notifications from server the id is **sT4J...**

## Expected Result
Identical ids in OnNotification and after lising notifications from server

## Actual Result
Different ids. Though not always

## Context
Unity client

## Your Environment

"Node","server":"nakama-8bf8","name":"nakama-8bf8","version":"1.4.0+93669f8","runtime":"go1.9.2"
"Data directory","server":"nakama-8bf8","path":"/nakama/data"
"Database connections","server":"nakama-8bf8","dsns":["root@cockroachdb:26257"]
"Database information","server":"nakama-8bf8","version":"CockroachDB CCL v1.1.3 (linux amd64, built 2017/11/27 13:59:10, go1.8.3)"

**Comment by mofirouz** [comment]
This is fixed in commit 8d208e6.
