### ISSUE TITLE
Searching groups by name

### ISSUE THREAD

**Issue by RomanZhu** [heroiclabs/nakama#154]
We need to let player search groups by name

There is a lot of games doing that:
(ClashRoyale)
![ofq1ohvnrbiq6qukjwlnzg](https://user-images.githubusercontent.com/12017366/36306146-89c1ff04-1327-11e8-8b9b-660919888730.png)

**Comment by igavva** [comment]
LUA script
```     
local function find_groups (context, payload)
	local json = nk.json_decode(payload)
	local query = [[SELECT * From nakama.groups WHERE name ILIKE  ']] .. json['s'] .. [[%']]
	local parameters = {}
	local rows = nk.sql_query(query, parameters)
	return nk.json_encode(rows)	
end
```

**Comment by novabyte** [comment]
This was added in ff85736544cef401f8a3f91388733296e08a9379 and will be part of the next release. The solution suggested by @igavva will still work and is useful for occasions when you'll want to perform more complex composite queries.
