### ISSUE TITLE
Removing entry from leaderboard

### ISSUE THREAD

**Issue by RomanZhu** [heroiclabs/nakama#156]
We have specific leaderboards for users inside group
When user leaves group - he should be removed from board (we can set their value to 0, but there could be a lot of garbage over time)

**Comment by zyro** [comment]
This is now possible from clients with the leaderboard record delete operation or from Lua with the [`nk.leaderboard_record_delete(id, owner)`](https://heroiclabs.com/docs/runtime-code-function-reference/#leaderboards) function.
