### ISSUE TITLE
Error with putting string into Storage

### ISSUE THREAD

**Issue by RomanZhu** [heroiclabs/nakama#165]
If we write 
```
var m = NStorageUpdateMessage.StorageUpdateBuilder();
m.Replace("/blah", "13");
```
everything will work as expected

But if write 
```
var m = NStorageUpdateMessage.StorageUpdateBuilder();
m.Replace("/blah", "blahblah");
```
it results in
`
Error: code 'StorageRejected' with 'Storage update index 0 rejected: json: error calling MarshalJSON for type jsonpatch.lazyNode: json: error calling MarshalJSON for type json.RawMessage: invalid character 's' looking for beginning of value'.
`

We tested and got errors with Add, Replace, Test, Merge

**Comment by zyro** [comment]
@RomanZhu The values expected in update operations must be readable as JSON objects or primitives. `13` is a valid JSON number, `blahblah` is not valid JSON. Try this instead and let us know if it works as expected:

```
var m = NStorageUpdateMessage.StorageUpdateBuilder();
m.Replace("/blah", "\"blahblah\"");
```

As a side note the error message itself is a little odd as there's no `'s'` character in your example update. Is what you pasted just a snippet of a wider update operation?

**Comment by RomanZhu** [comment]
@zyro That worked, thanks
I honestly don't remember what exactly we did to get that exact message. (There was a lot of iterations)
