### ISSUE TITLE
Error handling for INClient.Connect()

### ISSUE THREAD

**Issue by Ceiyne** [heroiclabs/nakama#168]
Many Nakama methods have two callbacks - one for success and one for error.  INClient.Connect() has only one callback, and it is only called upon success.  If there is an error (e.g., server is down), then instead the OnDisconnect event is fired.  This makes specific error handling a bit challenging because you need to be able to figure out the context when OnDisconnect gets called.

Ideally, Connect would have the same dual callback design as other methods, where an error handler could be defined.  Or, if you wanted to preserve the current call signature, the existing single callback has a boolean variable that could be passed as false to indicate a failure to connect (although this would not provide as much information as other methods with dedicated error callback).

Chris and I were discussing this issue in the gitter.  My personal feeling is that with the upcoming changes to convert Nakama async calls to being Task-based, that the bigger priority would be to work on those changes instead of on the existing callback code.  Changing to Tasks will likely require changes to error handling anyway.  I'd suggest that when converting Connect over to being Task-based, it be set up to throw/report errors directly rather than calling OnDisconnect.  If you're going to preserve the existing callback-based methods (to allow developers to choose which one to use) then you may want to consider going ahead and changing the Connect callback anyway.

**Comment by novabyte** [comment]
@Ceiyne I think this is well covered in the latest Nakama .NET/Unity client. Let me know if it doesn't cover the client design you had in mind.
