### ISSUE TITLE
Nakama.storage with JSON column type

### ISSUE THREAD

**Issue by RomanZhu** [heroiclabs/nakama#170]
to use JSON feature from new Cockroach 

we installed Cockroach2.0b 2018.03.05, then we migrated nakama to it with
```
cockroach sql --insecure
SET sql_safe_updates = false;
ALTER TABLE nakama.storage DROP COLUMN value RESTRICT;
ALTER TABLE nakama.storage ADD COLUMN value JSONB;
nakama migrate up
```

then we changed nakama source in `core_storage.go`
on lines  379, 390, 405, 547, 661 we changed `$6::BYTEA` to `$6::JSON`

and we can query JSON now like
`value = {"f_money": 300"}`
`select value -> 'f_money' from nakama.storage;`
```
+------------------------+
| value::JSON->'f_money' |
+------------------------+
|                    300 |
+------------------------+
```

**Comment by igavva** [comment]
Cockroach 2.0 is released!

**Comment by mofirouz** [comment]
@igavva Thanks for the reminder. We've got something in progress that relates to this - You'll hear soon ;)

**Comment by novabyte** [comment]
@RomanZhu @igavva We've moved the schema over to use the new JSONB type with our tables. This will be part of the next release. 😉
