### ISSUE TITLE
Support paging backwards in leaderboards

### ISSUE THREAD

**Issue by sinbad** [heroiclabs/nakama#173]
As of version 1.4 Nakama does not support paging backwards in leaderboard results, only forwards. The cursor contains the details of the last record in the page and the query only goes forward (to worse results) when supplied. 

The primary use case for paging backwards is when using the existing API to find the score for the current player in a leaderboard (referred to has the 'haystack' filter). This gives you a page with the player's score in the centre, but you can only page forwards (to worse scores) from that point. A typical player is going to want to scroll up as well as down from their own score to see scores which are better than theirs as well. Not being able to page backwards makes the 'haystack' query much less useful because you can only provide a static view of the nearest scores, without scanning the entire leaderboard from the start in order to cache enough information to scroll backwards. 

The ideal API (Unity provided as an example) would be to extend the `NLeaderboardRecordsListMessage.Builder` to add an optional direction argument to `Cursor`, for example:

```csharp
var prevList = // previously populated results list, with an assumed cursor
var messageBuilder = new NLeaderboardRecordsListMessage.Builder(id);
// page forwards, implicitly (compatibility)
messageBuilder.Cursor(prevList.Cursor);
// page forwards, explicitly
messageBuilder.Cursor(prevList.Cursor, INCursor.Direction.Next);
// page backwards, explicitly
messageBuilder.Cursor(prevList.Cursor, INCursor.Direction.Previous);
```

In order to support this, the cursor types in the client, server and protocol will need to be extended to include both the data values for the last record of the page (as currently) *and* the first record, and the server will have to invert the comparison for previous. It will actually work the same way as the 'haystack' query populates the before/after halves separately with inverted tests. 

Alternatively if you didn't want to put both next and previous in one cursor, you could use 2 cursors instead:

```csharp
var prevList = // previously populated results list, has 2 cursors one for previous and one for next
var messageBuilder = new NLeaderboardRecordsListMessage.Builder(id);
// page forwards, implicitly (compatibility - Cursor is an alias for CursorNext)
messageBuilder.Cursor(prevList.Cursor);
// page forwards, explicitly
messageBuilder.Cursor(prevList.CursorNext);
// page backwards, explicitly
messageBuilder.Cursor(prevList.CursorPrevious);
```

I'm not sure which one you prefer, I prefer a single cursor but maybe the protocol changes might be easier if they're separate. 

Attention @zyro - I might have a go at this myself sometime and submit a PR depending on what option you prefer, but might take a little while for me to get to it; I'm brute-forcing and not using the 'haystack' API for now as a workaround but would like to resolve it.

**Comment by novabyte** [comment]
This has been added to the latest (prerelease) builds of the server. 😄
