### ISSUE TITLE
Need cocos2d-x client for Nakama server

### ISSUE THREAD

**Issue by kienvn** [heroiclabs/nakama#180]
:)

**Comment by AlimJaffer** [comment]
Hi @kienvn  - this is something we’re working on! Keep your eyes out for it 🙂

**Comment by Dimon4eg** [comment]
probably it's possible to use Unreal C++ client https://github.com/heroiclabs/nakama-unreal

**Comment by raz0r007** [comment]
+1.
Plz, consider it.

**Comment by mofirouz** [comment]
Just to give some updates on this issue: Nakama 2.0 uses gRPC as the non-realtime protocol and JSON over Websockets for the realtime socket (at the time of writing this comment). 

We'll be working on updating the C++/Unreal/Cocos2dx client at some point soon. However in the meantime, you can code-generate the gRPC portion of a client using [gRPC-C++](https://grpc.io/docs/tutorials/basic/c.html). This is fairly trivial and you can use the [Java client](http://github.com/heroiclabs/nakama-java) as inspiration for this.

A pull request from the community goes a very long way and we'd really appreciate all the help and effort :)

**Comment by Dimon4eg** [comment]
where is cocos2dx repo to contribute to?

**Comment by mofirouz** [comment]
@Dimon4eg I've just created a new empty repo for you to contribute to :) Feel free to open PRs against it. 

https://github.com/heroiclabs/nakama-cocos2d-x

**Comment by Dimon4eg** [comment]
thank you @mofirouz

**Comment by Dimon4eg** [comment]
@mofirouz is Nakama SDK is 1.4.0 in unreal client.
is this latest version?

**Comment by mofirouz** [comment]
@Dimon4eg Yes, the latest release of the Unreal client is compatible with Nakama 1.4.x.

The protocol is different in Nakama 2.x - Using gRPC (see link above) for non-realtime, and JSON over Websocket for realtime. There may be an option of using Protobuf over Websocket in the near future but that's not fully decided yet.

**Comment by Dimon4eg** [comment]
Hey guys!
[nakama-cocos2d-x](https://github.com/heroiclabs/nakama-cocos2d-x) is ready and works with nakama 1.4.

@mofirouz please merge PR with critical fixes

**Comment by mofirouz** [comment]
Just wanted to provide an update -

We've just released a client library for [Generic C++ client](https://github.com/heroiclabs/nakama-cpp), as well as a [Cocos2d-x C++ client library](https://github.com/heroiclabs/nakama-cocos2d-x). 

Both these libraries are compatible with the latest version of the Nakama 2.x server. Please feel free to open issues in respective repositories.
