### ISSUE TITLE
leaderboard record does not show the latest entries 

### ISSUE THREAD

**Issue by blacklightknight** [heroiclabs/nakama#187]
## Description
When a user submits his/her score to the leaderboard and fetches the leaderboard entries to see the leaderboard state, he or she can only see the details of the users who submitted their scores before him and his own. 
If say another user submits his/her score after the above user, then the above user when fetches leaderboard entries, he still cannot see the data of this new user who submitted score after him and thus the latest leaderboard state/entries are not being fetched for this previous user(who submitted score first).

## Steps to Reproduce

Let there be 2 users- A and B
1) At first, User A submits score and fetches the scores(he can only see his details -- rightly so)
2) Secondly, User B submits score and can see his details as well as User A's details (again correct).
3) But after this step when user A fetches the score to see the leaderboard position, he cannot see the data of user B but can only see his(user A's) data .

If we add another user C after this he can see the data of all three but user A can only see his data, user B cab see only his and user's A data.

## Expected Result

After user C submits his score, even user A would be able to see User's C score/data and same would be the case with user B i.e All user must be able to see the data/score of people who have submitted score in the leaderboard after they themselves have.

## Actual Result
Users can see only his data plus of those who have submitted scores before him, and he is not able to see the scores/data in the leaderboard of the users who have submitted their own scores after him.

 Sample Example
`User A Submitted score
04-19 19:06:50.482 15896-16142/com.example.admin.myapplication E/Nakama: score submitted!

User A fetching leaderboard scores
04-19 19:07:21.894 15896-16142/com.example.admin.myapplication E/Nakama: Inside viewScore callback[DefaultLeaderboardRecord(leaderboardId=‘some_id’, ownerId=Xy2dZAGIRT6SJ4ReN6uVeA, handle=yOcoeJOfYW, lang=, location=, timezone=, rank=0, score=22364, numScore=1, metadata={}, rankedAt=0, updatedAt=1524145011699, expiresAt=0)]

User B Submitted score
04-19 18:11:45.130 24308-26251/com.example.admin.myapplication E/Nakama:  score submitted!

User B fetching leaderboard scores
04-19 18:12:23.316 24308-26251/com.example.admin.myapplication E/Nakama: Inside viewScore callback[DefaultLeaderboardRecord(leaderboardId=‘some_id’, ownerId=Xy2dZAGIRT6SJ4ReN6uVeA, handle=yOcoeJOfYW, lang=, location=, timezone=, rank=0, score=22364, numScore=1, metadata={}, rankedAt=0, updatedAt=1524145011699, expiresAt=0), DefaultLeaderboardRecord(leaderboardId= ‘some_other_id’, ownerId=if7JxRxERCepAKjdg8pHlQ, handle=roQWVyXUKL, lang=, location=, timezone=, rank=0, score=22364, numScore=1, metadata={}, rankedAt=0, updatedAt=1524145336814, expiresAt=0)]

User A fetching leaderboard scores after user B has submitted and fetched his(here user B’s data should have also been fetched and shown but it’s not).
04-19 19:16:17.485 15896-16142/com.example.admin.myapplication E/Nakama: Inside viewScore callback[DefaultLeaderboardRecord(leaderboardId=’some_id’, ownerId=Xy2dZAGIRT6SJ4ReN6uVeA, handle=yOcoeJOfYW, lang=, location=, timezone=, rank=0, score=22364, numScore=1, metadata={}, rankedAt=0, updatedAt=1524145011699, expiresAt=0)]`

## Context
- [ ] Android/Java

## Your Environment
- Nakama: 1.4.1+50cb727
- Cockroach: v2.0.0
- Environment name and version: Docker version 17.09.1-ce, build 19e2cf6
- Operating System and version: MacOS Sierra version 10.12.6

**Comment by gustavotero7** [comment]
I have a similar problem, but here is listing nothing until the player set a new score, then the list leaderboard message returns only the last score submitted by the logged user, cant list others score :(

Nakama 1.4
Cockroach 1.1.6

Also tried with Nakama 1.4.1 and cockroach 2

**Comment by novabyte** [comment]
I cannot reproduce this on Nakama 2. Please upgrade and re-open if you have issues.
