### ISSUE TITLE
Support for keycloak login (Oauth)

### ISSUE THREAD

**Issue by Alcondez** [heroiclabs/nakama#188]
it would be nice to be able to extend the auth module and add another OAuth provider (in my case keycloak). The flow would be almost identical to the facebook with one exception:

The url needs to be a parameter because the keycloak serve would most likely be self-hosted.  Another way to go about this would be to decode the token and get the issuer from it.

(Fragment of decoded jwt token)
```
"jti": "6d9e2e14-0076-4e80-b037-b3b38549880f",
"exp": 1522083235,
"nbf": 0,
"iat": 1522082935,
"iss": "https://hosted-keycloak.com/auth/realms/myrealm",  <- This would be part of the url
"aud": "client",
"sub": "6e3f7b87-85n3-3456-985f-c9r46524454d",
"typ": "Bearer",
"azp": "client",
"nonce": "e846c82b-c321-4089-8457-274a45e3611a",
```
Having that, the request is pretty straigth forward:

```
curl -s -X POST  -H "Content-Type: application/x-www-form-urlencoded" -d "access_token=""MY_TOKEN" https://hosted-keycloak.com/auth/realms/myrealm/protocol/openid-connect/userinfo"
```

and the response:

```
{
  "sub": "fb28f173-3713-4c30-a879-a08b0e1665b8",
  "name": "Alejandro Conde",
  "preferred_username": "Alejandro Conde",
  "email": "email@gmail.com"
}
```

where sub is the user ID which could be stored by the nakama server

**Comment by novabyte** [comment]
@Alcondez This looks like a good addition to the server. What sort of project do you have that will use keycloak as an external identity provider?

**Comment by Alcondez** [comment]
I have a web and mobile app that lets users configure and interact with our cloud PBX. We use Keycloak  as SSO so anything I add to the project needs to go through it.

**Comment by Allan-Nava** [comment]
> @Alcondez This looks like a good addition to the server. What sort of project do you have that will use keycloak as an external identity provider?

Yeah correct

**Comment by Tom-Development** [comment]
Anymore updates on this functionality? 

We are looking at different game backends for our upcoming game but need a way to support staff to login using keycloak since we use that for central identity management.

**Comment by novabyte** [comment]
@Tom-Development The original request was to have Keycloak be supported as a user authentication option (players) but I think your ask is about support for Keycloak with the Nakama Console. Is that right?

**Comment by Tom-Development** [comment]
Hi @novabyte Yes that is correct - I must have misunderstood the request, is there any support for this feature? I did check the documentation but couldn't find any references to using 3rd party authentication providers.

**Comment by novabyte** [comment]
@Tom-Development There's no support yet for 3rd party authentication providers to be integrated with the Nakama Console but we have a wide support for social authentication providers and others for players to use to sign-in.

We did recently add multi-user profiles to the Nakama Console to support different levels of authorized role. This is a great start point for separate Nakama Console identity providers to be integrated. We can always set up a discussion on it in the new year.

**Comment by zyro** [comment]
We've kept this issue open to gauge interest, but for the moment there doesn't seem to be enough demand for this feature. Closing this for now, happy to revisit in the future if there's a need. :+1:
