### ISSUE TITLE
Need hot reloading of lua modules.

### ISSUE THREAD

**Issue by madclaws** [heroiclabs/nakama#192]
## Description
Whenever we make a change in lua modules.The changes should be effective onspot rather than restarting server.

**Comment by MindfulMe** [comment]
yep, we want something like "nodemon" but for your server

**Comment by MindfulMe** [comment]
Because it is really inconvenient when you have to reload your docker container each time (in case you're not running it locally)

**Comment by MindfulMe** [comment]
or at least it will be fine if you guys will make a hot reload for docker

**Comment by BehroozBahrameh** [comment]
some endpoint like `/-/reload` in _Prometheus_ and alert _manager_ .

**Comment by selimanac** [comment]
+1

**Comment by nomi27951** [comment]
+1 Sir

**Comment by mrpuzzler** [comment]
+1

**Comment by emircanerkul** [comment]
+1

Otherwise really hard to develop and debug.

**Comment by Mohsen7s** [comment]
Beside this feature it's easy to implement, its a must have. It's really annoying restart whole docker containers just to reload a module. +1

**Comment by shayneoneill** [comment]
+1 Would be good.

**Comment by majstorki88** [comment]
+1, and is there any plans for this? This remains open from 2018? Same situation for multiple clusters...

**Comment by novabyte** [comment]
@majstorki88 It remains open because it's a very complex task. To introduce hot reloading within a running Nakama cluster is akin to code reloading as handled by the Erlang runtime. Pull requests are always welcome 🙏

**Comment by deflinhec** [comment]
#965

**Comment by emircanerkul** [comment]
@deflinhec  if it's done and tested could you please close this issue?

**Comment by deflinhec** [comment]
It's done with final PR #966. I've tested with some of my scripts.

It would be great if someone else can test it also, just for making sure this feature works as expect.

@emircanerkul  I don't think I have the permission to close this issue.

**Comment by dragonlobster** [comment]
+1 does it also work with typescript modules/go modules

**Comment by deflinhec** [comment]
I'd create a PR for lua hot reload, for runtime match and rpc. Not so sure about how typescript perform a hot reload.

**Comment by deflinhec** [comment]
In the earlier PR I didn't handle lua hot reload properly. It only affect to rpc runtime and matches which will be created after the hot reload. The newer PR now takes effect to preexisting runtime rpc and matches.

**Comment by zyro** [comment]
More info on this [related PR comment](https://github.com/heroiclabs/nakama/pull/1009#issuecomment-2282811410).

**Comment by Ughuuu** [comment]
Why is this closed as completed? It should be closed as either not planned or won't fix instead.
