### ISSUE TITLE
lua returns wrong value for int64 numbers

### ISSUE THREAD

**Issue by rezam90** [heroiclabs/nakama#193]
## Description
In Runtime code (Lua) when I register a function as register_http, int64 values are being converted in `return` to wrong values.

## Steps to Reproduce
1. define a function in runtime modules (lua)
2. return an int64 value in a JSON

```lua
local nk = require("nakama")

local function return_int64(_, payload)
    return { id = 342161316540874753 }
end

nk.register_http(return_int64, "return_int64")
```

## Expected Result
```bash
$ curl -X POST "http://127.0.0.1:7350/runtime/return_int64?key=defaultkey" -d '{"id": "342161316540874753"}' -H 'content-type: application/json'

{ "id" : 342161316540874753 }
```

## Actual Result
```bash
$ curl -X POST "http://127.0.0.1:7350/runtime/return_int64?key=defaultkey" -d '{"id": "342161316540874753"}' -H 'content-type: application/json'

{ "id" : 342161316540874750 }
```
As you noticed the last digit is changed.

## Your Environment

- Nakama: 1.4.1
- Cockroach: v2.0.0
- Environment name and version: darwin
- Operating System and version: macOS High Sierra 10.13.1

**Comment by rezam90** [comment]
It seems lua does not have int64. here https://github.com/yuin/gopher-lua/issues/152

**Comment by zyro** [comment]
Lua doesn't have separate integer and float types. Everything is a float so in the runtime Lua's `number` type is mapped on to Go's `float64`. Looks like there's a bit of precision loss when converting to JSON. You can see it in isolation in this [playground example](https://play.golang.org/p/Kvpv4uvEpE-).

@rezam90 One typical strategy when dealing with large numbers in JSON is to convert them to strings before encoding or as part of the process. Would that work in your use case?

**Comment by zyro** [comment]
As shown this is the expected behaviour of Go's JSON encoder for large floats. To maintain precision render the number as a string before encoding.
