### ISSUE TITLE
Strip prefix recorded source file paths when compiling

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama#20]
The built binaries have source code file paths in them. This is shown when an error stack trace is printed and looks something like this:

```
nakama         | main.dbConnect(0xb56100, 0xc4200ad8e0, 0xc420011f90, 0x1, 0x1, 0x1)
nakama         |     /Users/novabyte/go/src/nakama/main.go:242 +0x2ed
nakama         | main.main()
nakama         |     /Users/novabyte/go/src/nakama/main.go:89 +0xbf9```
```

I think we should turn on `--trimpath` when compiling the binary. Relevant link: https://golang.org/cmd/compile/

**Comment by novabyte** [comment]
@mofirouz I'll make this change as part of the next milestone release.

**Comment by novabyte** [comment]
This was resolved in https://github.com/heroiclabs/nakama/commit/fb7c4da34f129f2934d0f5e4573caa0e251777f1.
