### ISSUE TITLE
Auto-renewable subscriptions

### ISSUE THREAD

**Issue by AGulev** [heroiclabs/nakama#203]
Would be great to have supports of  auto-renewable subscriptions for ios and android.

iOS documentation: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html
https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Introduction.html#//apple_ref/doc/uid/TP40010573

Android documentation: https://developer.android.com/google/play/billing/billing_subscriptions
https://developer.android.com/google/play/billing/realtime_developer_notifications

**Comment by zyro** [comment]
This was added in c3d3cc69ae69cf7f92469a63c8a574d2629af5a5 and is part available from Nakama v3.13.1 onwards.
