### ISSUE TITLE
Can I customize the extension authentication

### ISSUE THREAD

**Issue by aaaasssdd** [heroiclabs/nakama#208]
Can I customize the extension authentication, do I have the relevant documents? Thank you。

**Comment by novabyte** [comment]
Hi @aaaasssdd can you describe how you'd like to customize the authentication options?

The server is quite flexible and has support for custom authentication where user IDs are obtained from an external service. It might be easier to discuss on the [community channel](https://gitter.im/heroiclabs/nakama) but give me a quick overview of what you want to achieve.

**Comment by aaaasssdd** [comment]
I'll check if custom authentication is enough.  thank you

**Comment by novabyte** [comment]
Ok great @aaaasssdd. Have a look at the docs on it [here](https://heroiclabs.com/docs/authentication/#custom) and reopen this issue if it doesn't cover what you need. 👍
