### ISSUE TITLE
Realtime support

### ISSUE THREAD

**Issue by ylluminate** [heroiclabs/nakama#218]
What will it take here to add realtime support for the server?  This appears to offer some very attractive functionality, but one thing it really needs is a Photon-like realtime features.  

Has anyone spec'd this out to determine what needs to be done to add this yet?

**Comment by ylluminate** [comment]
Hmm, it seems that this kind of functionality might already be included: https://heroiclabs.com/docs/gameplay-multiplayer-realtime/

**Comment by novabyte** [comment]
@ylluminate We already have much more realtime support than in Photon. A few features built into the server:

- Realtime chat with optional message storage.
- Realtime status events (online indicators with messages).
- Realtime relayed multiplayer (same as what Photon offer).
- Realtime authoritative multiplayer with a fixed tick rate per match on the server.

**Comment by ylluminate** [comment]
Thanks for pointing that out @novabyte.
