### ISSUE TITLE
Enhancements for checking database state when starting

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama#22]
When starting a node we check if the database is migrated to the latest available schema. However, this is not fool-proof if the database is not fully available. 

https://github.com/heroiclabs/nakama/blob/master/cmd/migrate.go#L65

We need to return with an error and fail early here as it will cause problems down the line.

**Comment by novabyte** [comment]
This was resolved in the [0.11.2 release](https://github.com/heroiclabs/nakama/releases/v0.11.2).
