### ISSUE TITLE
Replace package satori/go.uuid

### ISSUE THREAD

**Issue by josselin-c** [heroiclabs/nakama#220]
This issue has been opened automaticaly because we think you are using satori/uuid in your code. Unfortunately, satori/uuid has a critical defect where it doesn't generate random UUIDV4s satori/go.uuid#73 and should be replaced as the maintainer has been unresponsive for 5 months with the bug still open. Alternative packages you should consider: https://github.com/google/uuid https://github.com/pborman/uuid

**Comment by zyro** [comment]
Thanks for the heads up, this is resolved in commit fa3cfa5188376f341f014144a4415db2aef269ea.
