### ISSUE TITLE
Add API to query leaderboard rank and return nearby records

### ISSUE THREAD

**Issue by handcircus** [heroiclabs/nakama#224]
Additions to the leaderboard API would allow a user to query their rank and neighbouring scores. 

The API would need to return:

* The player's numeric rank in the leaderboard
* Player's record in leaderboard
* Records above rank
* Records below rank

Suggested additional API parameters:

* Reference to User
* Count of records above player rank
* Count of records below player rank 

This is commonly used in titles such as Golf Clash and PSN leaderboards (screenshot below)
![img_543d122c439c-1](https://user-images.githubusercontent.com/362730/43386503-b2556052-93db-11e8-8bc0-e81891152c22.jpeg)

**Comment by dungttZonmob** [comment]
I'm wishing this feature too !

**Comment by mofirouz** [comment]
This feature has now landed in master (841307ec142cd7ce7451eb4ffba43750d3b4ff01) and will be available in the upcoming Nakama 2.1 release. 

As part of this changeset:

1. Ranks are calculated and cached on the server. This means that you can get not only the top X players, but also specific players' ranks and surrounding players (haystack query).

2. A new tournaments API is available - where you can define a tournament (backed by a leaderboard), join, submit records, and list records. Tournaments can have a start time, end time, a duration and a reset schedule. When the tournament duration elapses or tournament resets, the server emits events that you can match on in the Runtime to execute custom functions, for instance to distribute rewards to the top 10% of the players who participated in the tournament.

I think the combination of these two features satisfies the request in this issue. Feel free to reopen if you'd like to add more info/requests.
