### ISSUE TITLE
Trying to use cursor returned from storage_list to get public records results in error due to zero uuid

### ISSUE THREAD

**Issue by shinmai** [heroiclabs/nakama#230]
## Description
In Lua runtime code, getting public records by calling ```storage_list``` and passing the returned pagination cursor on subsequent calls to get more records, any calls after the initial one will throw an error due to the UserID being all null bytes.

## Steps to Reproduce
1. Store more than 100 public records (for example, the issue could be bypassed for any number of records below 100, which is the maximum storage_list will return in one call)
2. in Lua initialize nakama and call
```
local data, cursor nk.storage_list("", "collection", 100, nil)
data, cursor nk.storage_list("", "collection", 100, cursor)
```
4. Error about uuid being all zero bytes appears in server logs on referencing the second call to storage_list

## Expected Result
No error is thrown and server returns more records and a cursor if there are more records.

## Actual Result
Error is thrown and server returns no records.

## Context
- [X] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: 2.0.3-r1
- Cockroach: 2.0.2
- Environment name and version: Managed Cloud

**Comment by mofirouz** [comment]
Thanks for reporting this. This is now fixed on master with commit https://github.com/heroiclabs/nakama/commit/b2df2c014791143245a072a97538eaa9e9f6b8ba and will be included in the next release.
