### ISSUE TITLE
Getting chat message history using Cursor for paging, cause server error

### ISSUE THREAD

**Issue by sadegh021** [heroiclabs/nakama#232]
## Description
In Unity Client SDK there is a method for getting chat message history (ListChannelMessagesAsync). last parameter of this function is cursor for apply paging on messages.
if invoke this method without using cursor, every thing is OK and server return message history to client, but if we use cursor in this function a server error occurred.  

## Steps to Reproduce
1. Connect to nakama server and get new session
2. Invoke client.ListChannelMessagesAsync without using of cursor and store cursor from function response for next usage.
3. Reinvoke client.ListChannelMessagesAsync with stored cursor from step 2.
4. Errors reported to client and in server logs

##  Unity Code
`public string historyCursor = null;`
`public async Task<List<IApiChannelMessage>> GetMessageHistory(int messageCount, bool forward)`
`{`
`     var hisResult = await client.ListChannelMessagesAsync(session, groupChatId, messageCount, forward, historyCursor);`
`     historyCursor = hisResult.NextCursor;`
`     Debug.Log("HistoryCursor: " + historyCursor);`
`     return hisResult.Messages.ToList();`
`}`

## Unity Log
![capture 1](https://user-images.githubusercontent.com/10131365/44958605-cfb99000-aef7-11e8-8965-a40ab52a2162.JPG)

## Server Log (image)
![capture 2](https://user-images.githubusercontent.com/10131365/44958612-e95ad780-aef7-11e8-8a3d-0830210fe91b.JPG)

## Server Log (Text)
`{"level":"error","ts":"2018-09-02T18:22:26.602+0430","msg":"Error listing channel messages","error":"pq: expected tuple ($1, $2::UUID, $3::UUID, CAST($6::BIGINT AS TIMESTAMP WITH TIME ZONE), $7) to have a length of 6","stacktrace":"github.com/heroiclabs/nakama/server.ChannelMessagesList\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/server/core_channel.go:121\ngithub.com/heroiclabs/nakama/server.(*ApiServer).ListChannelMessages\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/server/api_channel.go:49\ngithub.com/heroiclabs/nakama/api._Nakama_ListChannelMessages_Handler.func1\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/api/api.pb.go:5833\ngithub.com/heroiclabs/nakama/server.apiInterceptorFunc.func1\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/server/api.go:301\ngithub.com/heroiclabs/nakama/api._Nakama_ListChannelMessages_Handler\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/api/api.pb.go:5835\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).processUnaryRPC\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1011\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).handleStream\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1249\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/Users/novabyte/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:680"}`

## Context
-  Unity

## Your Environment
- Nakama: 2.0.3
- Cockroach: 2.0.5
- Environment name and version: Unity 2018.2
- Operating System and version: Windows 10

**Comment by mofirouz** [comment]
This is now fixed on master with https://github.com/heroiclabs/nakama/commit/3ec5dbaa610ed9df38cb63c1b86c25efe0f6e5c5 - this will be in the next release of Nakama. Feel free to re-open the ticket if you think there are other problems related to this.
