### ISSUE TITLE
Username/Password Authentication 

### ISSUE THREAD

**Issue by b3hroo2** [heroiclabs/nakama#235]
According to this [page](https://heroiclabs.com/docs/authentication/#authenticate) there is no way to login with username/password 

It's nice to add
The main reason for this request is that usernames are usually shorter than emails and easier to type specially in mobile devices so it will provide a better User Experience.

**Comment by zyro** [comment]
Added in f53bf2d394cc1c449ae5c3d2328991ba41e83ba5 and will be part of the next release.

**Comment by tapmyads** [comment]
Hi is possible to register account via Username and Password only?

**Comment by novabyte** [comment]
@tapmyads It's best to ask general questions on the forum. Yes, you can authenticate users just by email/password. Have a look at the documentation: https://heroiclabs.com/docs/authentication/#email
