### ISSUE TITLE
Logger cause client(Socket) don't work properly

### ISSUE THREAD

**Issue by b3hroo2** [heroiclabs/nakama#236]
When we Init client with Logger the Socket won't work properly .
More detail : when we Create Web Socket with Logger none of listener won't call but in nakama console the log show that socket is open .

Reproduce Steps:
1.Change 
`private IClient _client = new Client("defaultkey", "127.0.0.1", 7350, false);`
 from MatchmakerWithMatch.cs from snippets to 
```
private IClient client = new Client("defaultkey", "127.0.0.1", 7350, false)
{
#if UNITY_EDITOR
  Logger = new UnityLogger(),
  Trace = true
#endif
};
```
2.attach MatchmakerWithMatch.sc to Empty Game Object and run

Nakama-unity : 2.1.0

**Comment by novabyte** [comment]
This was a bug in the .NET client used within Unity. It was resolved in https://github.com/heroiclabs/nakama-dotnet/commit/06b88199e23b86b578d33d5bdfae343d38278d36.
