### ISSUE TITLE
Modules function names clash

### ISSUE THREAD

**Issue by kageeker** [heroiclabs/nakama#239]
## Description
A module is executing a function from a different module.

## Steps to Reproduce

Example:
1. Setup 2 modules each of them having a function with the same name.
2. Execute only 1 module repeatedly and have it call that function.
3. Make the function inside the module you are executing have 1 argument only and make it debug that string.
4. Make the function inside the module you are not executing have 2 arguments and have it concat them and debug the concated string.

## Expected Result
You will get an error mentioning both modules and saying you can not concat string with nil (which means the function from the second module is executed, which shouldn't happen).

## Context
Tested on Unity.

- Nakama: 2.0.3
- Cockroach: 2.0.4
- Operating System and version: Ubuntu Linux 18.04.1

**Comment by zyro** [comment]
@kageeker It would help if you can attach the two modules (containing only the code absolutely necessary to reproduce this issue) and a `curl` command we can run to reproduce.

**Comment by kageeker** [comment]
### Running module test1 will produce the error right away.
`local nk = require("nakama")


function test(message)
nk.logger_info(message)
end

local function test1(context, payload)

test("Test 1");
return nil
end

nk.register_rpc(test1, "test1")
`

------


`local nk = require("nakama")


function test(message,msg)
nk.logger_info(message..msg)
end

local function test2(context, payload)

test("Test 1","Test 2");
return nil
end

nk.register_rpc(test2, "test2")
`

**Comment by zyro** [comment]
@kageeker This is not a bug.

The problem is you're defining a global function `test` twice, and the second time it expects 2 arguments. Because of the order the modules are loaded in the one in test2.lua (the second file) will override the first. When you call the `test1` RPC function that only passes in one argument to the `test` function which triggers an error concatenating with `nil` as the second argument.

To solve this scope the two functions to be local to the module they're in:
```
local nk = require("nakama")

local function test(message)
  nk.logger_info(message)
end

local function test1(context, payload)
  test("Test 1");
  return nil
end
nk.register_rpc(test1, "test1")
```
```
local nk = require("nakama")

local function test(message,msg)
  nk.logger_info(message..msg)
end

local function test2(context, payload)
  test("Test 1","Test 2");
  return nil
end
nk.register_rpc(test2, "test2")
```
