### ISSUE TITLE
Make it's possible to create group for more than 100 members and change default value via .yml config

### ISSUE THREAD

**Issue by Suvitruf** [heroiclabs/nakama#242]
Right now `100` is hardcoded here:

https://github.com/heroiclabs/nakama/blob/bb21e62f1043783ec6a0c3576ed05f0b997259d4/server/runtime_go_nakama.go#L1133

And, probably, here:

https://github.com/heroiclabs/nakama/blob/bb21e62f1043783ec6a0c3576ed05f0b997259d4/server/runtime_go_nakama.go#L1133

Please, make it's possible to:
1) Setup default value via .yml config.
2) Create group for more than 100 members.

**Comment by zyro** [comment]
This is resolved in dd71a09b488b28f21270fd38e1a052ad042c7d78 and will be part of the next release. The server will allow any large value for the max count field.
