### ISSUE TITLE
Error when full Source Builds

### ISSUE THREAD

**Issue by mask3000** [heroiclabs/nakama#244]
When I build source，I encounter a problem.
When I command
#protoc -I/usr/local/include -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis --go_out=plugins=grpc:. ./api/api.proto
I got：
protoc-gen-swagger/options/annotations.proto: File not found.
api/api.proto: Import "protoc-gen-swagger/options/annotations.proto" was not found or had errors.

my system is Linux n16-027-228 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

**Comment by novabyte** [comment]
@mask3000 I ran through the build process with an ArchLinux container. The docs are a little outdated you'll need to add to your imports statement with `protoc`.

> protoc -I/usr/local/include -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway --go_out=plugins=grpc:. ./api/api.proto

Also make sure to have `$GOPATH/bin` on your system `$PATH`.

I will update the README with corrections.

**Comment by mask3000** [comment]
> @mask3000 I ran through the build process with an ArchLinux container. The docs are a little outdated you'll need to add to your imports statement with `protoc`.
> 
> > protoc -I/usr/local/include -I. -I$GOPATH/src -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway --go_out=plugins=grpc:. ./api/api.proto
> 
> Also make sure to have `$GOPATH/bin` on your system `$PATH`.
> 
> I will update the README with corrections.

Thank you novabyte!
