### ISSUE TITLE
Which version of go is needed to run the project？

### ISSUE THREAD

**Issue by Liuguozhu** [heroiclabs/nakama#262]
Which version of go is needed to run the project？

**Comment by novabyte** [comment]
@Liuguozhu You don't need the Go toolchain to run the project. You only need it if you want to develop your server logic in Go or if you want to build the game server from source. We use Go 1.11.1 for the latest server release and development.

**Comment by Liuguozhu** [comment]
@novabyte Many thanks!  I has successfully build and run yesterday. 
Go version 1.10.3 ; cockroachDB version : v2.1.0
