### ISSUE TITLE
Unable to retrieve public storage records using runtime code

### ISSUE THREAD

**Issue by fayyadsufyan** [heroiclabs/nakama#269]
## Description

When records are inserted into storage engine using authenticated user with public read permission those records are not retrieved when using the runtime function nk_storage_list(nil, collection, limit, "").
It only returns those records with 00000000-0000-0000-0000-000000000000 (system user_id)

## Steps to Reproduce
1. Submit records using authenticated user with public read permission: 2
2. Use the storage_list() runtime function with user_id = nil to retrieve all public records in specific collection

## Expected Result
All records with a max of 100 results should be returned.

## Actual Result
Only records with  system user id 00000000-0000-0000-0000-000000000000 are retrieved.

## Context

-  Unity

## Your Environment
- Nakama: 2.2.0
- Cockroach: 2.1.1
- Mac OS High Sierra 10.13.6

**Comment by zyro** [comment]
Fixed in ce86bdc9fff43b66bc928191766b76d30aac99bc and will be part of the next release.
