### ISSUE TITLE
Add a server subcommand which acts as a client

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#27]
The only way right now to interact with the server is via one of our official client libraries or to generate a client impl from the [server protocol](https://github.com/heroiclabs/nakama/blob/master/server/api.proto). This is great for game development with an engine like Unity or Unreal but makes demos and administrative tasks tricky because another language/toolchain/environment is required.

It'd be great to be able to run Nakama with the necessary connection parameters as a client subcommand which could be used to perform basic tasks. For example:

`nakama client register-user --device-id "some unique ID"`

We'll need to establish how much of the surface area of the game server we'd want/need to support within the subcommand but it'd be useful to operate on the server and complement the inspection options available in the embedded dashboard.

**Comment by novabyte** [comment]
This might be handled better as a separate command line tool like `nakamactl` or similar. It depends whether we want to package the functionality with the main server. Different examples have made different choices:

- cockroachdb has a subcommand called `cockroach sql` which gives a REPL as a client connection to the server.
- postgres has a separate tool called `psql`.
- hbase has a subcommand called `hbase shell` which gives a REPL as a client connection. Similar to cockroachdb.

**Comment by mofirouz** [comment]
This is my 2c:

I would like to keep this command line tool as in the same `nakama` binary:

1. Given that we already have a `doctor` and `migrate` subcommands, I would like to keep the consistency.
2. Less management overhead, install scripts etc when you have one binary
3. Much similar build system

As a sidenote, I think we'd need a REPL like environment as we have an active WS connection to the server. (As opposed to disconnect and reconnect).

**Comment by novabyte** [comment]
I don't think this issue is needed now. We have GRPC/HTTP access, multiple client libraries, Swagger API definitions, and documentation to help learn the API and experiment.
