### ISSUE TITLE
Server v2.2.1 new duration and end_active fields are not exposed to runtime code

### ISSUE THREAD

**Issue by fayyadsufyan** [heroiclabs/nakama#272]
## Description
Using runtime code with new server version 2.2.1 does not return duration and end_active fields when using nk.tournament_list()

## Steps to Reproduce
Define a new variable that receives tournaments list and try to access the first element duration field it returns nil.
local tournaments = nk.tournament_list(1, 2)
print(tournaments[1].end_time)

## Expected Result
nk.tournament_list() should return results containing duration and end_active field

## Actual Result
No duration nor end_active fields are available

## Context
Lua runtime code

## Your Environment
- Nakama: 2.2.1
- Cockroach: 2.1.0
- MacOS High sierra

**Comment by novabyte** [comment]
As a follow up we should also expose the `end_active` and `duration` fields to leaderboard responses as well both in the server functions and the main API if it makes sense.

**Comment by zyro** [comment]
Added in aedac15452d74cde4ac42a206c5627bfddf69702 and 8d8db8901931e645ffcd97f26645944d15839742, and will be part of the next release.
