### ISSUE TITLE
I want to add some processing to offline players in realtime multiplayer

### ISSUE THREAD

**Issue by Liuguozhu** [heroiclabs/nakama#274]
I want to add some processing to offline players in realtime multiplayer. 
what should I do?

**Comment by novabyte** [comment]
@Liuguozhu Can you give me more information on your use case? It might be best if we speak over on gitter in the community channel - https://gitter.im/heroiclabs/nakama

**Comment by zyro** [comment]
Resolved over [Gitter](https://gitter.im/heroiclabs/nakama), not an issue.
