### ISSUE TITLE
Linking email overwrites existing email without warning or error

### ISSUE THREAD

**Issue by jdetter** [heroiclabs/nakama#275]
## Description

Chris wanted me to open an issue for discussion here. In my opinion there should at least be a warning in the nakama log telling you that an existing linked email was clobbered by a new one. The safest implementation would be to force the client to unlink first before linking another email.

Also the documentation is not really clear on whether or not linking multiple emails is allowed:

 > You can link one or more other login option to the current user. This makes it easy to support multiple logins with each user and easily identify a user across devices.

What this obviously means is that you can have a linked email, facebook, steam, ect. linked at the same time (one of each). However I originally assumed you could have as many email accounts linked as you want because you can have as many devices linked as you want.

The reason we came across this issue is we were thinking about ways we could recover user accounts where the user no longer has access to their email. We were considering allowing users to have an additional email account that could be linked for recovery.

## Steps to Reproduce
Here is a super simple example:

```
private async System.Threading.Tasks.Task EmailTest()
{
    await client.LinkEmailAuth("TestEmail@gmail.com", "A password");
    await client.LinkEmailAuth("AnoterTestEmail@gmail.com", "A password");
}
```

## Expected Result

Perhaps there should be an error or warning telling the client that they are overriding the linked email. Perhaps you should be allowed to link multiple email accounts to your nakama account?

## Actual Result

The linked email is overridden without error or warning.

## Context

- [X] Unity
- [ ] Unreal
- [ ] Other

**Comment by novabyte** [comment]
I looked into this issue and I don't think it requires a special error to be surfaced. It works like the other link operations that take priority on the user account. You can always use `GetAccountAsync` and check the current email address linked to the account and determine whether you'd want to overwrite it or not.

We will update the docs to be clearer that you can store more than one device ID to the user account but only one email address like all the rest of the linked account options.
