### ISSUE TITLE
 the link of production settings deployment guide is 404

### ISSUE THREAD

**Issue by Liuguozhu** [heroiclabs/nakama#276]
the link of production settings deployment guide  in the docs is 404.
![图片](https://dn-coding-net-production-pp.codehub.cn/999f8575-6296-4af3-aab0-086f29aff5e9.png)
![图片](https://dn-coding-net-production-pp.codehub.cn/0c3619cf-875b-4e70-91f7-44eccb1d99f7.png)

**Comment by zyro** [comment]
Thanks for the heads-up, this is now fixed. In the future please open issues purely related to documentation on the [nakama-docs repo](https://github.com/heroiclabs/nakama-docs).
