### ISSUE TITLE
Missing error logs in Windows under docker-toolbox

### ISSUE THREAD

**Issue by rrenderr** [heroiclabs/nakama#284]
## Description
If Lua code has runtime error in some function - the Nakama server stops running this function without any logs in console

## Example
There are the error because we can't concatenate " state " .. state

```
function M.match_loop(context, dispatcher, tick, state, messages)
  print ("first step")
  print (">> match_loop " .. " nkTime " .. nk.time() .. " state " .. state)
  print ("second step")
```

Last logs from console:
nakama         | {"level":"debug","ts":"2019-01-04T10:24:36.412Z","msg":"Processing presence event","joins":1,"leaves":0}
nakama         |  >>> match_join
nakama         | {"level":"debug","ts":"2019-01-04T10:24:36.413Z","msg":"Sending *rtapi.Envelope_Match message","uid":"235800a4-e25f-4587-8808-d28aa434a58f","sid":"03affa98-683c-4959-bdc3-e754f622e32b","envelope":"cid:\"4\" match:<match_id:\"7e43e33f-0ad0-4f87-a8e1-60b48e71d918.nakama1\" authoritative:true label:<> self:<user_id:\"235800a4-e25f-4587-8808-d28aa434a58f\" session_id:\"03affa98-683c-4959-bdc3-e754f622e32b\" username:\"RRendeRR\" > > "}
nakama         | first step

## Expected Result
Logs with stack trace in console

## Actual Result
No any logs in console

## Context
C++ client

## Your Environment
- Nakama: 2.3.0
- Cockroach: 2.1.1
- Windows 10

**Comment by zyro** [comment]
@rrenderr I ran a test with the two module files below.

init.lua:
```lua
local nk = require("nakama")

nk.run_once(function()
  nk.match_create("match")
end)
```
match.lua:
```lua
local nk = require("nakama")

local M = {}

function M.match_init(context, params)
  return {}, 1, ""
end

function M.match_join_attempt(context, dispatcher, tick, state, presence, metadata)
  return state, true
end

function M.match_join(context, dispatcher, tick, state, presences)
  return state
end

function M.match_leave(context, dispatcher, tick, state, presences)
  return state
end

function M.match_loop(context, dispatcher, tick, state, messages)
  print("first step")
  print(">> match_loop " .. " nkTime " .. nk.time() .. " state " .. state)
  print("second step")
  return state
end

function M.match_terminate(context, dispatcher, tick, state, grace_seconds)
  return state
end

return M
```

The output in the server logs is (relevant lines only):
```
first step
{"level":"warn","ts":"2019-01-04T20:03:58.926Z","msg":"Stopping match after error from match_loop execution","mid":"84f6edb3-b25b-444a-b714-1df1db5713f1","tick":0,"error":"data/modules9/match.lua:23: cannot perform concat operation between string and table\nstack traceback:\n\tdata/modules9/match.lua:23: in main chunk\n\t[G]: ?"}
```

This happens with both the default `INFO` and with the more verbose `DEBUG` level logging. Can you confirm you see the same output?

**Comment by rrenderr** [comment]
Hi @zyro,
I have copied your Lua code and tried to test. Here are last lines from console:
nakama         | {"level":"info","ts":"2019-01-08T18:27:30.699Z","msg":"Startup done"}
nakama         | first step

# Additional information:
I tested on version 2.3.0 and 2.3.1 on two separete PCs.
I started Nakama in Docker Quickstart Terminal using default docker-compose.yml from tutorial.

Also I can record a  video of the test process.

**Comment by zyro** [comment]
@rrenderr Can you share your OS version and Docker version?

**Comment by rrenderr** [comment]
Windows 10 Pro 64bit
Docker version 18.03.0-ce, build 0520e24302

**Comment by zyro** [comment]
I have used the exact `docker-compose.yml` in [the docs here](https://heroiclabs.com/docs/install-docker-quickstart/#using-docker-compose) along with the 2 Lua files in the comment above. I can see the output as expected:
```
nakama         | {"level":"info","ts":"2019-01-08T20:14:41.892Z","msg":"Startup done"}
nakama         | first step
nakama         | {"level":"warn","ts":"2019-01-08T20:14:42.702Z","msg":"Stopping match after error from match_loop execution","mid":"92df14a4-350e-45ed-af54-f72c595b6dc4","tick":0,"error":"/nakama/data/modules/match.lua:23: cannot perform concat operation between string and table\nstack traceback:\n\t/nakama/data/modules/match.lua:23: in main chunk\n\t[G]: ?"}
```

Is there any way you can verify on another machine (either Windows or another OS) because at the moment I can't reproduce. Perhaps it's an OS/environment issue?

**Comment by rrenderr** [comment]
@zyro we have checked it on Mac OS - all work fine, and we have log
nakama         | first step
nakama         | {"level":"warn","ts":"2019-01-09T11:16:34.151Z","msg":"Stopping match after error from match_loop execution","mid":"c5aa37fd-911c-4168-b90a-8069b5bc618c","tick":0,"error":"/nakama/data/modules/match.lua:23: cannot perform concat operation between string and table\nstack traceback:\n\t/nakama/data/modules/match.lua:23: in main chunk\n\t[G]: ?"}

**Comment by zyro** [comment]
Interesting that means there's something different about Docker's output handling on Windows. Do you have access to a different Windows machine? I'm not sure how to verify if this is a general issue on Windows or something specific to that one machine.

**Comment by zyro** [comment]
@rrenderr @BopoHDark Interesting, does logging continue normally after this point if more is printed by other actions in the server?

**Comment by BopoHDark** [comment]
We've found a solution - just add "tty: true" option to nakama service in docker-compose.yml  and it shows logs correctly.

**Comment by zyro** [comment]
This is an environment-specific Docker issue. We'll document the solution but there's nothing we can do in Nakama itself.
