### ISSUE TITLE
Pass custom error message from Before hooks to client

### ISSUE THREAD

**Issue by gupta-vaibhav** [heroiclabs/nakama#286]
## Description
When an error occurs inside any of the before hooks, even though the before hook returns a custom error message, this custom error message is not returned to the client. E.g. we are using custom authentication in our game. We carry out the custom authentication in the 'RegisterBeforeAuthenticateCustom' hook. Depending upon the error type encountered in the custom hook, the client needs to perform different actions. However the custom error message is not relayed back to the client.

## Steps to Reproduce
Create a simple RegisterBeforeAuthenticateCustom hook in runtime code as follows.
```
func AuthUser(ctx context.Context, logger *log.Logger, db *sql.DB, nk runtime.NakamaModule, in *api.AuthenticateCustomRequest) (*api.AuthenticateCustomRequest, error) {
    return nil, errors.New("Random error occurred")
}
```

## Expected Result
Upon calling the AuthenticateCustom function from Unity, the client should receive the custom error message text "Random error occurred"

## Actual Result
Only selected standard error messages are received at the client end.

## Context
We used Unity for the client, but the issue should reproduce on all platforms.

## Your Environment
"version":"2.0.0+dev","runtime":"go1.11.2","cpu":4
"version":"CockroachDB CCL v2.0.5 (x86_64-apple-darwin17.7.0, built 2018/08/13 20:55:02, go1.10.3)"

**Comment by zyro** [comment]
This was resolved in a previous release. Recent versions of Nakama behave as expected and return custom error messages.
