### ISSUE TITLE
Group event messages are not created or sent

### ISSUE THREAD

**Issue by casperkl** [heroiclabs/nakama#293]
## Description
Group event messages are not created or sent.
(event messages being the events described in https://heroiclabs.com/docs/social-realtime-chat/) 

## Steps to Reproduce
1. Join a group while listening to messages with another client thats part of that group.
2. Check the database "message" table.

## Expected Result
ISocket.OnChannelMessage recieves a new message with the corresponding event code.
These messages are saved in the database.

## Actual Result
Messages never arrive and they don't get saved in the database.

## Context
This was done using the Unity client.
Both running in the editor and on android builds.
Only messages sent by the users are saved in the "message" table (Code 0)

## Your Environment
- Nakama: 2.3.2+749d8b2c
- Cockroach: v2.0.4
- Environment name and version: Running nakama and cockroach locally
- Operating System and version: Windows 10 Pro

**Comment by zyro** [comment]
This is resolved in 8d9b2e0ea68204259d1f6c1f944b4558d996e1b2 and will be part of the next release.
