### ISSUE TITLE
Add server side API to control users state in groups

### ISSUE THREAD

**Issue by casperkl** [heroiclabs/nakama#296]
Additions to the server side API would allow for the server to control a users state in groups.

- Promote a user in a group
- Leave a group

**Comment by novabyte** [comment]
@casperkl I'll add your notes from our chat on gitter to the discussion:

In our case a user can only be a member of one group at a time, a user can choose to join another group and just has to confirm the switch.
In case this user was the superadmin of a clan we want to promote the next highest ranking member of the clan to superadmin before leaving. But this requires 4-5 consecutive operations from the client side at the moment.
-leave -> error
-get group users
-promote user
-promote user again(if no admin was available)
-leave

I was trying to do this in a single rpc call which handles the different cases.

---

Thanks for the feature request. @zyro let me know what you think.

**Comment by zyro** [comment]
Makes sense to add a function for group leave and group promote. We'll get to it as soon as we can unless someone contributes a PR first.

**Comment by zyro** [comment]
Added in https://github.com/heroiclabs/nakama/commit/5ae35060ff0e55a2a56133585d00a1246d37731e and will be part of the next release.
