### ISSUE TITLE
How can I develop an elo based leaderboard.

### ISSUE THREAD

**Issue by nostel** [heroiclabs/nakama#298]
Hi i'm new to Nakama,

I want to make a Elo based leaderboard.
So when a user attack another formation and win. This user win, his elo will +10, and his enemy's elo will -10.
Can I achieve that with Nakama?

**Comment by mofirouz** [comment]
Hi @nostel - You may be able to achieve this using a Leaderboard that has its `operator` set to `set` - this will allow the score value to be updated up/down, and the rank will be updated accordingly to the score. 

https://heroiclabs.com/docs/gameplay-leaderboards/#create-a-leaderboard

If you are asking to update the rank value explicitly, Nakama doesn't allow that at the moment.

**Comment by nostel** [comment]
Hi, with set operator, I can change the score of current user. How can I change the score of the opponent?

Is there a way to create a custom function/api to do that?

**Comment by mofirouz** [comment]
> Is there a way to create a custom function/api to do that?

Yes absolutely - please take some time to read the documentation:
https://heroiclabs.com/docs/runtime-code-basics/

> How can I change the score of the opponent?

Yes have a look at this function in the Runtime code (runs on the server):
https://heroiclabs.com/docs/runtime-code-function-reference/#leaderboards

```leaderboard_record_write (id, owner, username, score, subscore, metadata)```

**Comment by nostel** [comment]
Okkk, thank you very much!
