### ISSUE TITLE
Login twice with the same account

### ISSUE THREAD

**Issue by raz0r007** [heroiclabs/nakama#302]
## Description
I can login, connect and join to a match with the same Facebook account, at the same time (2 clients).

## Steps to Reproduce
1. Login with Facebook Account A, connect and join to match A with Device A.
2. Login with Facebook Account A, connect and join to match A with Device B.
3. Send data from Device B to Device A.

## Expected Result
I should not be able to login and join to the same match with the same Account.

## Actual Result
The Device B can join and send data to match A, despite of the Facebook account is the same.

## Context
* [ x ] Cocos2d-x c++ 3.17

## Your Environment
* Nakama: Server 2.4.0 and C++ SDK
* Cockroach: Build Tag 2.1.3
* Operating System and version: macOS Mojave 10.14.3

**Comment by AlimJaffer** [comment]
Hi @raz0r007 as discussed in our community channel (https://gitter.im/heroiclabs/nakama) this is not a bug, but rather a feature by design for games that wish to offer a multiple device/screen experience. 

As @zyro explained in the channel, you can handle this by allowing the client to connect but not participate in any matches if they have a second socket connected. You would implement this in the match join handling code by checking if that user is already in a match and rejecting the second attempt to join.

**Comment by Dimon4eg** [comment]
It would be great to implement this blocking mechanism on server and add option to off it. By default it should be on (block multiple joins to match) because it needed for rare cases I believe.

**Comment by novabyte** [comment]
@Dimon4eg That's a great point. Lets open an issue on the docs repo and we can show how to achieve a lockout for the same user in the multiplayer match.

**Comment by raz0r007** [comment]
> Hi @raz0r007 as discussed in our community channel (https://gitter.im/heroiclabs/nakama) this is not a bug, but rather a feature by design for games that wish to offer a multiple device/screen experience.

Can you show me a game that offers a multiple device experience? I don't understand the logic, i can't play with 2 devices at the same time. I've only 2 hands!

**Comment by novabyte** [comment]
@raz0r007 I don't want to create a disagreement about whether multi-device sign-in should or should not be in the server but have a look at [this](https://www.nytimes.com/2013/12/22/technology/master-of-his-virtual-domain.html) article which discusses power players in games like Clash of Clans and please move any further discussion onto the community channel.
