### ISSUE TITLE
Hooks should be able to return a basic string without being wrapped in the envelope 

### ISSUE THREAD

**Issue by JustinNicholls** [heroiclabs/nakama#309]
## Description
Returning a string from a function attached to a hook should not wrap it in a JSON object under key payload

should return 
```
"data"
```
not
```
{"payload": "data"}
```
when function returns a string

This is helpful when making callbacks for third party services that expect the returned data in a certain format.

## Steps to Reproduce
1. Create a function
2. Return a string in the function
3. Register the function as a hook
4. Call hook for newly created function

## Expected Result
Hook call should return a string

## Actual Result
Hook call returns the string wrapped in JSON under the key payload

## Context
- [x] Javascript

## Your Environment
nakama - 2.4.0
cockroach - 2.1.4
operating system - macOS Sierra version 10.12.6
environment - latest version of docker

**Comment by novabyte** [comment]
@JustinNicholls Was the S2S RPC function called with POST or GET from the external service?

**Comment by zyro** [comment]
This is resolved in 20d6ab3cfc2478c39498a4d261d23c9fd1906ef2 and will be part of the next release.

Hooks will accept an `unwrap` query parameter and receive/return any raw string payload without wrappers. The documentation will be updated to reflect this in time for the next release.
