### ISSUE TITLE
logger rotating bug

### ISSUE THREAD

**Issue by ZhangGuangxu** [heroiclabs/nakama#313]
## Description
Should not treat logger filename in config as a directory. First, extract the logger directory. Then, try to create logger directory if it does not exist.

## Steps to Reproduce
set logger file in nakama.yaml

```
logger:
  file: '/path/to/log/nakama.log'
```

## Expected Result
create path/to/log/nakama.log

## Actual Result
something else, mess

## Context
javascript

## Your Environment
- Nakama: 2.4.0
- Environment name and version:  
   - "runtime":"go1.10.3"
   - "runtime":"go1.11.1"
- Operating System and version:  
   - macOS 10.13.6
   - Ubuntu 16.04.5 LTS

**Comment by ZhangGuangxu** [comment]
see PULL REQUEST #312

**Comment by zyro** [comment]
Fixed in b17aa8cee2f7703ed0d5ea02f26ecb6c20b49326 and will be part of the next release.
