### ISSUE TITLE
Can't join a match in 0.11.2

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama#32]
Log when trying to call the NMatchCreateMessage and then the NMatchJoinMessage

Could not register new email profile, rows affected error
[I] New session connected uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1
[D] Sending *server.Envelope_Heartbeat message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=
[D] Received *server.Envelope_SelfUpdate message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 cid=1b5dbdf8-d209-451c-bc28-b8d19856057b
[D] Sending <nil> message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=1b5dbdf8-d209-451c-bc28-b8d19856057b
[D] Received *server.Envelope_TopicJoin message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 cid=02efb111-adde-4534-9590-50f95885d5c2
[D] Sending *server.Envelope_Topic message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=02efb111-adde-4534-9590-50f95885d5c2
[D] Processing presence diff joins=1 leaves=0
[D] Presence diff topic count joins=1 leaves=0
[D] Routing topic diff to=[{ID:{Node:nakama-8483 SessionID:aee9233b-f9f9-4a41-ba98-d5752867f5d1} Topic:room:Amycles Village UserID:861307f2-9cf8-4bd9-afbb-9afe220f0424 Meta:{}}] msg=&TopicPresence{Topic:&TopicId{Id:&TopicId_Room{Room:[65 109 121 99 108 101 115 32 86 105 108 108 97 103 101],},},Joins:[&UserPresence{UserId:[134 19 7 242 156 248 75 217 175 187 154 254 34 15 4 36],SessionId:[174 233 35 59 249 249 74 65 186 152 213 117 40 103 245 209],}],Leaves:[],}
[D] Received *server.Envelope_TopicMessagesList message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 cid=68f58b54-528b-4d93-91e7-055d92ddd270
[D] Sending *server.Envelope_TopicMessages message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=68f58b54-528b-4d93-91e7-055d92ddd270
[D] Received *server.Envelope_UsersFetch message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 cid=66f376d4-da96-4eae-ba20-b391be65844c
[D] Sending *server.Envelope_Users message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=66f376d4-da96-4eae-ba20-b391be65844c
[D] Received *server.Envelope_UsersFetch message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 cid=63929d64-4401-4685-9fb2-e9acc1e80781
[D] Sending *server.Envelope_Users message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=63929d64-4401-4685-9fb2-e9acc1e80781
[D] Received *server.Envelope_MatchCreate message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 cid=f2a15197-a170-481b-b9e9-3b9b7c376cf4
[D] Sending *server.Envelope_Match message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=f2a15197-a170-481b-b9e9-3b9b7c376cf4
[D] Processing presence diff joins=1 leaves=0
[D] Presence diff topic count joins=1 leaves=0
[D] Routing match diff to=[{ID:{Node:nakama-8483 SessionID:aee9233b-f9f9-4a41-ba98-d5752867f5d1} Topic:match:d2d9c3a8-30eb-4edd-8863-f01a393817a9 UserID:861307f2-9cf8-4bd9-afbb-9afe220f0424 Meta:{}}] msg=&MatchPresence{MatchId:[210 217 195 168 48 235 78 221 136 99 240 26 57 56 23 169],Joins:[&UserPresence{UserId:[134 19 7 242 156 248 75 217 175 187 154 254 34 15 4 36],SessionId:[174 233 35 59 249 249 74 65 186 152 213 117 40 103 245 209],}],Leaves:[],}
[D] Sending *server.Envelope_Heartbeat message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=
[D] Sending *server.Envelope_Heartbeat message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=
[D] Received *server.Envelope_MatchJoin message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 cid=3f09b039-07cc-40a1-a77b-6c6c8bfeb7d5
[D] Sending *server.Envelope_MatchPresences message uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 collation_id=3f09b039-07cc-40a1-a77b-6c6c8bfeb7d5
[I] Cleaning up closed client connection uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1 remoteAddress=192.168.1.1:62438
[I] Closed client connection uid=861307f2-9cf8-4bd9-afbb-9afe220f0424 sid=aee9233b-f9f9-4a41-ba98-d5752867f5d1
[D] Processing presence diff joins=0 leaves=2
[D] Presence diff topic count joins=0 leaves=2
[D] No local presences to report diff topic=match:d2d9c3a8-30eb-4edd-8863-f01a393817a9
[D] No local presences to report diff topic=room:Amycles Village
2017/02/19 03:40:10 http: panic serving 192.168.1.1:62438: runtime error: invalid memory address or nil pointer dereference
goroutine 43 [running]:
net/http.(*conn).serve.func1(0xc4203a00a0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1721 +0xd0
panic(0x14f6ec0, 0x18a39d0)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
nakama/server.(*UserPresence).Size(0x0, 0x1)
	/Users/novabyte/go/src/nakama/server/api.pb.go:17033 +0x26
nakama/server.(*TMatchPresences).Size(0xc420366f20, 0x171f7b5450)
	/Users/novabyte/go/src/nakama/server/api.pb.go:17298 +0x5f
nakama/server.(*Envelope_MatchPresences).Size(0xc4204280e8, 0x1)
	/Users/novabyte/go/src/nakama/server/api.pb.go:16275 +0x44
nakama/server.(*Envelope).Size(0xc420366f60, 0xc4203d2f80)
	/Users/novabyte/go/src/nakama/server/api.pb.go:15870 +0x5d
nakama/server.(*Envelope).Marshal(0xc420366f60, 0x17a5560, 0xc420366f60, 0x1fa1878, 0xc420366f60, 0x1)
	/Users/novabyte/go/src/nakama/server/api.pb.go:12310 +0x2f
nakama/vendor/github.com/gogo/protobuf/proto.Marshal(0x17a5560, 0xc420366f60, 0x2f, 0xc4203d2f80, 0x1, 0x1, 0x2f)
	/Users/novabyte/go/src/nakama/vendor/github.com/gogo/protobuf/proto/encode.go:233 +0x34b
nakama/server.(*session).Send(0xc42010a850, 0xc420366f60, 0x2, 0xc4203529e0)
	/Users/novabyte/go/src/nakama/server/session.go:131 +0x216
nakama/server.(*pipeline).matchJoin(0xc4201e69b0, 0x17aae60, 0xc420366ee0, 0xc42010a850, 0xc420366e80)
	/Users/novabyte/go/src/nakama/server/pipeline_match.go:70 +0x73b
nakama/server.(*pipeline).processRequest(0xc4201e69b0, 0x17aae60, 0xc420366ee0, 0xc42010a850, 0xc420366e80)
	/Users/novabyte/go/src/nakama/server/pipeline.go:114 +0x39d
nakama/server.(*pipeline).(nakama/server.processRequest)-fm(0x17aae60, 0xc420366ee0, 0xc42010a850, 0xc420366e80)
	/Users/novabyte/go/src/nakama/server/session_auth.go:112 +0x52
nakama/server.(*session).Consume(0xc42010a850, 0xc42014fb18)
	/Users/novabyte/go/src/nakama/server/session.go:90 +0x778
nakama/server.(*SessionRegistry).add(0xc4201e6050, 0xd94bf89cf2071386, 0x24040f22fe9abbaf, 0xc42000ab00, 0xc42014fb18)
	/Users/novabyte/go/src/nakama/server/session_registry.go:70 +0x130
nakama/server.(*authenticationService).configure.func3(0x17a6aa0, 0xc4200fa2a0, 0xc42000aa00)
	/Users/novabyte/go/src/nakama/server/session_auth.go:112 +0x2b2
net/http.HandlerFunc.ServeHTTP(0xc4201f8d50, 0x17a6aa0, 0xc4200fa2a0, 0xc42000aa00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1942 +0x44
nakama/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201e6a00, 0x17a6aa0, 0xc4200fa2a0, 0xc42000aa00)
	/Users/novabyte/go/src/nakama/vendor/github.com/gorilla/mux/mux.go:103 +0x255
net/http.serverHandler.ServeHTTP(0xc4203c6000, 0x17a6aa0, 0xc4200fa2a0, 0xc42000aa00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4203a00a0, 0x17a7060, 0xc4203902c0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2668 +0x2ce

**Comment by zyro** [comment]
@ArisTsevrenis Thanks for the report, I've been able to reproduce with a test and found root cause. Fix will be up soon.
