### ISSUE TITLE
Internal server error while loading leaderboard records around user (With limitation argument)

### ISSUE THREAD

**Issue by mohsenyz** [heroiclabs/nakama#320]
Hi, I get below error while getting leaderboard records around user. Everything is fine if I set the request limit argument to 1, but for limit > 1 this error occurs on server

{"level":"error","ts":"2019-04-01T11:05:03.599Z","msg":"Could not execute leaderboard records list query","error":"pq: syntax error at or near \"and\"","stacktrace":"github.com/heroiclabs/nakama/server.getLeaderboardRecordsHaystack\n\t/go/src/github.com/heroiclabs/nakama/server/core_leaderboard.go:557\ngithub.com/heroiclabs/nakama/server.LeaderboardRecordsHaystack\n\t/go/src/github.com/heroiclabs/nakama/server/core_leaderboard.go:483\ngithub.com/heroiclabs/nakama/server.(*ApiServer).ListLeaderboardRecordsAroundOwner\n\t/go/src/github.com/heroiclabs/nakama/server/api_leaderboard.go:254\ngithub.com/heroiclabs/nakama/apigrpc._Nakama_ListLeaderboardRecordsAroundOwner_Handler.func1\n\t/go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1618\ngithub.com/heroiclabs/nakama/server.StartApiServer.func1\n\t/go/src/github.com/heroiclabs/nakama/server/api.go:98\ngithub.com/heroiclabs/nakama/apigrpc._Nakama_ListLeaderboardRecordsAroundOwner_Handler\n\t/go/src/github.com/heroiclabs/nakama/apigrpc/apigrpc.pb.go:1620\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:966\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).handleStream\n\t/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:1245\ngithub.com/heroiclabs/nakama/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/src/github.com/heroiclabs/nakama/vendor/google.golang.org/grpc/server.go:685"}

**Comment by zyro** [comment]
Fixed in 9af808cc7eb6683fa3e83117ac9a9d36b1fefe31 and will be part of the next release.

**Comment by Mehrdadgame** [comment]
Hi 
i have problem in get leader-board data in client (unity)
my problem is get data leader-board  of  local host but i do set port and host is VPS 

Send: method='GET', uri='http://127.0.0.1:7350/v2/leaderboard/b7c182b36*****?limit=1&', body=''
