### ISSUE TITLE
API to disconnect User from server by using User Id

### ISSUE THREAD

**Issue by hk0129** [heroiclabs/nakama#325]
## Description
Currently user socket can be terminated using the session_id associated with it.

It would be useful to have an API to disconnect a user from server removing all connected sessions.
This will help admins to disconnect a player from server via RPC.

**Comment by novabyte** [comment]
This can be done with stream list operation on the notification stream for the user. This is a private stream that each user has when their socket is first connected. You can then loop over it to disconnect all sockets for the user or all but the active one. A quick example of what this code could look like is:

```go
userID, ok := ctx.Value(runtime.RUNTIME_CTX_USER_ID).(string)
if !ok {
	logger.Error("context did not contain user ID.")
	return
}

sessionID, ok := ctx.Value(runtime.RUNTIME_CTX_SESSION_ID).(string)
if !ok {
	logger.Error("context did not contain session ID.")
	return
}

// Fetch all live presences for this user on their private notification stream.
presences, err := nk.StreamUserList(streamModeNotification, userID, "", "", true, true)
if err != nil {
	logger.WithField("err", err).Error("nk.StreamUserList error.")
	return
}

for _, presence := range presences {
	if presence.GetUserId() == userID && presence.GetSessionId() == sessionID {
		// Ignore our current socket connection.
		continue
	}

	// Force disconnect the socket for the user's other game client.
	if err := nk.SessionDisconnect(ctx2, presence.GetSessionId()); err != nil {
		logger.WithField("err", err).Error("nk.SessionDisconnect error.")
	}
}
```

Hope this helps.
