### ISSUE TITLE
Add lua runtime function "read_file" to read file under config.GetDataDir() directory

### ISSUE THREAD

**Issue by ZhangGuangxu** [heroiclabs/nakama#329]
Add lua runtime function "read_file" to read file under config.GetDataDir() directory.
See PR #328.

**Comment by ZhangGuangxu** [comment]
I hope this PR could be useful.

**Comment by ZhangGuangxu** [comment]
## PURPOSE:

I need a lua runtime function to read config files from disk directly.

## HOW TO USE:

To read a file "config/game_config.json" under "config.GetDataDir()"(default is /path/to/nakama-working-directory/data), I write code like this:

```
local filename = "config/game_config.json"
local content = nk.read_file(filename)

if content then
    nk.logger_info("read content from "..tostring(filename)..": "..tostring(content).."")
 
    // you could decode json content to some object
    local some_object = nk.json_decode(content)
else
    nk.logger_info(""..tostring(filename).." is empty")
end
```

## DETAILS:

Lua runtime function "read_file" read file "/path/to/nakama-working-directory/data/config/game_config.json" and return file content. 
If this file is empty, "read_file" returns empty string. 
If any error happend in go code, error will be raised.

To describe read_file function prototype clearly, in Typescript: 
`export declare function read_file(filename: string): string | null;`

## MORE EXAMPLES
- read empty file
  - Execute this command in your shell:  `touch data/config/empty.json`
  - code like this:
    
    ```
    local filename = "config/empty.json"
    local content = nk.read_file(filename)

    if content and (#content>0) then
        nk.logger_info("read content from "..tostring(filename)..": "..tostring(content).."")
        local some_object = nk.json_decode(content)
    else
        nk.logger_info(""..tostring(filename).." is empty")
    end
    ``` 

  - Run your game server. Then you will get log info `onfig/test.json is empty`.

- read a file does not exist
  - code like this:

  ```
    local filename = "config/no_file.json"
    local content = nk.read_file(filename)

    if content and (#content>0) then
        nk.logger_info("read content from "..tostring(filename)..": "..tostring(content).."")
        local some_object = nk.json_decode(content)
    else
        nk.logger_info(""..tostring(filename).." is empty")
    end
  ```
  
  - Run your game server. Then you will get ERROR.
    
    ```
    ... ERROR: Could not complete runtime invocation
    ...
    stack traceback:
	[G]: in function 'read_file'
    ```

**Comment by mofirouz** [comment]
@ZhangGuangxu thanks for the PR.

We typically advise that one should use the `runtime.env` functionality to pass external info to the Lua Runtime.

I'm very interested in knowing why you need the config file in Lua? Is this Nakama's config file, or some other application?

**Comment by ZhangGuangxu** [comment]
@mofirouz 

My game has dozens of config files, which are json format.
My CO save the content of the config files in DB. Then read the configs from DB in lua code.
I simply would like to read configs from disk directly.

**Comment by ZhangGuangxu** [comment]
@mofirouz

Game configs, like how much exp some user needs to upgrade from level 1 to level 2, like what I should give a user when he/she request daily bonus, and so on.

**Comment by ZhangGuangxu** [comment]
@mofirouz

Some game-logic-related configs need to be loaded on the fly, and must not restart game server.
Does `runtime.env` fullfill my requirement？

**Comment by mofirouz** [comment]
Apologies for not replying sooner - somehow missed the email notifications.

The issue is that Lua is a sandboxed environment. Which means no Lua code could access host resources directly. You have three options:

1. Write to the DB and consume from it - as you have mentioned above.
2. Base64 JSON content and pass through via `runtime.env`
3. Use Go (as plugins) (see here) to load files from the file system. Lua runtime and Go runtime can coexist in a project but they can't communicate to each other.

Hope this help.s

**Comment by yomunsam** [comment]
> @mofirouz
> 
> My game has dozens of config files, which are json format.
> My CO save the content of the config files in DB. Then read the configs from DB in lua code.
> I simply would like to read configs from disk directly.

We used third-party tools to turn JSON into Lua table, which seems to be working properly at the moment.
