### ISSUE TITLE
Error thrown when install using Docker-Compose

### ISSUE THREAD

**Issue by gucheng117** [heroiclabs/nakama#336]
## Description

Error thrown when install using Docker-Compose,
Stoped at bellow logs:
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Found runtime modules","count":0,"modules":[]}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Starting Console server for gRPC requests","port":7348}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Starting Console server gateway for HTTP requests","port":7351}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.933Z","msg":"Starting API server for gRPC requests","port":7349}
nakama         | {"level":"info","ts":"2019-04-22T09:26:48.934Z","msg":"Starting API server gateway for HTTP requests","port":7350}
nakama         | {"level":"info","ts":"2019-04-22T09:26:49.177Z","msg":"Startup done"}
^CGracefully stopping... (press Ctrl+C again to force)

## Steps to Reproduce
install using Docker-Compose

## Your Environment
- Nakama:2.4.0
- Cockroach: v2.1.4
- Operating System and version: CentOS7.6

**Comment by gucheng117** [comment]
docker-compose version 1.24.0

**Comment by mofirouz** [comment]
This is normal server operation, seems like you’ve stopped the server manually yourself. 

I don’t see any errors being thrown here. What are you referring to here? 

(Ps please only comment on one issue, not multiple)

**Comment by gucheng117** [comment]
It stopped at this log, and didn't move on to the next step.
nakama         | {"level":"info","ts":"2019-04-22T09:26:49.177Z","msg":"Startup done"}
It means the installation was successful？

**Comment by novabyte** [comment]
@gucheng117 I think you're confused. `"Startup done"` means the server has fully started and all subsystems have initialized. I think it will be quickest to ask any more questions in the community channel: https://gitter.im/heroiclabs/nakama

**Comment by gucheng117** [comment]
@novabyte OK, thank you.

**Comment by tanjunior** [comment]
Adding `tty: true` under nakama services fixes the issue
