### ISSUE TITLE
Dev Console - Status page shows Incorrect Authoritative Matches count

### ISSUE THREAD

**Issue by hdjay0129** [heroiclabs/nakama#338]
## Description
Authoritative matches count is being shown 0 on status page of dev console even if there are  active authoritative matches running on server. 

## Steps to Reproduce
1 - start nakama server 
2 - start few authoritative matches
3 - view on dev console status page - the count of authoritative matches

## Expected Result
Dev console status page should show the correct count of active authoritative matches.

## Actual Result
Dev console status page show 0 authoritative matches count.

## Context
nakama "2.5.0+10a07a7b"

## Your Environment
Windows 10

**Comment by zyro** [comment]
Looks like a mislabeled variable, thanks for reporting it! Fixed in f9d7db2235623bbd5a326a6034b849d181b781db and will be part of the next release.
