### ISSUE TITLE
Dev Console - User's friends info is not populated correctly

### ISSUE THREAD

**Issue by hdjay0129** [heroiclabs/nakama#339]
## Description
When viewing user's friends list on the dev console, there are empty rows corresponding to user's friends.

![nofriends](https://user-images.githubusercontent.com/17492225/56796980-4f062600-6831-11e9-8935-c1a643469d39.PNG)

## Context
nakama "2.5.0+10a07a7b"

## Your Environment
Windows 10

**Comment by zyro** [comment]
Thanks for the report! This is fixed in ac170882b678e9cfb22a4f09b8586d6dcf378aaf and will be part of the next release.
