### ISSUE TITLE
Developer console account wallet update error: "Wallet must be a valid JSON object"

### ISSUE THREAD

**Issue by fsufyan** [heroiclabs/nakama#340]
## Description
Updating account wallet from console dashboard not working: "Wallet must be a valid JSON object"

![Screen Shot 2019-04-28 at 9 32 56 AM](https://user-images.githubusercontent.com/36089616/56861799-d3c58100-69a4-11e9-804f-d3bbadd59bbc.png)

## Steps to Reproduce
1. Login and click on any user entry.
2.Try to update wallet from Account tab.
3."Wallet must be a valid JSON object" message is displayed and no update is performed.

## Expected Result
Account wallet update success.

## Actual Result
No update performed and error message "Wallet must be a valid JSON object" is displayed.

## Your Environment
- Nakama: 2.5.0
- Cockroach: 2.1.6
- MacOS 10.13.4 HighSierra

**Comment by zyro** [comment]
Thanks for reporting this! This is fixed in 14f1197632ba525ea14a75c6d5cc57550ad1da3e and will be part of the next release.
