### ISSUE TITLE
Storage write from developer console not working on system user: "Requires a valid user ID"

### ISSUE THREAD

**Issue by fsufyan** [heroiclabs/nakama#341]
## Description
Cannot modify objects that belong to system user "00000000-0000-0000-0000-000000000000" using console UI it gives an error: "Requires a valid user ID".
![Screen Shot 2019-04-29 at 12 23 07 PM](https://user-images.githubusercontent.com/36089616/56890644-5409e600-6a7a-11e9-9291-40f3e29e747e.png)

## Steps to Reproduce
1. Login and open Storage
2.Try to modify objects with system user
3."Requires a valid user ID" is displayed and no data is modified

## Expected Result
Successfully modify object value.

## Actual Result
"Requires a valid user ID" is displayed and no data is modified.

## Context
- Developer Console UI

## Your Environment
- Nakama: 2.5.0
- Cockroach: 2.1.6
- MacOS HighSierra 10.13.4

**Comment by zyro** [comment]
Thanks for reporting this! This is fixed in 56c495bac134e345118aea3b6808e94b6bd3e164 and will be part of the next release.
