### ISSUE TITLE
Expose user email in admin UI

### ISSUE THREAD

**Issue by Suvitruf** [heroiclabs/nakama#344]
Hello there. Would be nice, if you expose user email in admin UI.

**Comment by mofirouz** [comment]
There is a potential privacy issue. What’s the reason for displaying user’s email address?

**Comment by Suvitruf** [comment]
> 
> 
> What’s the reason for displaying user’s email address?

More convenient. 

> 
> 
> There is a potential privacy issue.

But we can get it directly from databases anyway.

**Comment by mofirouz** [comment]
> More convenient 

This is not a reason. What would you use a user’s email for? 

> But we can get it from the database anyways.

Please refer to the GDPR guidelines of “data processor” and “data controller”. I wonder if exposing this field could move the needle to Nakama becoming a data processor and it would have privacy complications.

@zyro and @novabyte - we may want considering removing fields that could be viewed as PPI from the console.

**Comment by zyro** [comment]
This is possible as of [Nakama 2.7.0](https://github.com/heroiclabs/nakama/releases/tag/v2.7.0).
