### ISSUE TITLE
golang client availability

### ISSUE THREAD

**Issue by jesst3r** [heroiclabs/nakama#346]
Greetings, is there golang client library available? Cannot find any.
Thanks in advance!:)

**Comment by novabyte** [comment]
Hey @jesst3r we have a Go package for our GRPC client code which lets you use most of the API available here: https://godoc.org/github.com/heroiclabs/nakama/apigrpc#NakamaClient
Does that cover what you're looking for?

**Comment by jesst3r** [comment]
> 
> 
> Hey @jesst3r we have a Go package for our GRPC client code which lets you use most of the API available here: https://godoc.org/github.com/heroiclabs/nakama/apigrpc#NakamaClient
> Does that cover what you're looking for?

Thank you so much!:) It is really awesome, but it seems, that it is missing realtime multiplayer features (ex: CreateMatch, SendMatchState, OnMatchState) :/

**Comment by mofirouz** [comment]
Hi @jesst3r - The realtime portion of the API is Protobuf and you can find it here:
https://github.com/heroiclabs/nakama/blob/master/rtapi/realtime.proto

**Comment by jesst3r** [comment]
> 
> 
> Hi @jesst3r - The realtime portion of the API is Protobuf and you can find it here:
> https://github.com/heroiclabs/nakama/blob/master/rtapi/realtime.proto

thank you so much, you guys, are the best :) thank you, for your titanic work:)

**Comment by mofirouz** [comment]
Thanks for the kind words. I'll close the issue now, feel free to re-open.
