### ISSUE TITLE
"error":"json: cannot unmarshal object into Go value of type []*server.importStorageObject"

### ISSUE THREAD

**Issue by AlexeyIS** [heroiclabs/nakama#347]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/heroiclabs/nakama) and ask any questions you have or mention any problems you've had getting started with the server.

Please provide as much information as you can with this issue report. If you believe it may be an issue with one of the client libraries please report it on their [own trackers](https://github.com/heroiclabs?utf8=%E2%9C%93&q=nakama%20AND%20sdk&type=&language=).

## Description
Getting 'Failed to upload the file' error when uploading json file to Storage in admin panel. 
Logs: `{"level":"warn","ts":"2019-05-21T11:03:22.819-0700","msg":"Could not parse JSON file.","error":"json: cannot unmarshal object into Go value of type []*server.importStorageObject"}`

$ ./nakama --version
2.5.1+8216d5cc

Json I am trying to upload:
`{
    "items": [
        {
            "desc": null,
            "id": "3423",
            "name": null,
            "parameters": null,
            "quantity": 0,
            "tags": null,
            "type": 0
        }
    ],
    "version": "1"
}
`
## Steps to Reproduce
1. Login as admin to 
2. Go to Storage
3. Select Import Json file
4. drag and drop json file.
5. Error appears: Failed to upload the file. 

## Expected Result
No error is thrown and json file uploaded

## Actual Result
The error appears: Failed to upload the file. 
Terminal logs: `{"level":"warn","ts":"2019-05-21T11:03:22.819-0700","msg":"Could not parse JSON file.","error":"json: cannot unmarshal object into Go value of type []*server.importStorageObject"}`

## Context

- [ ] Unity
- [ ] Unreal
- [x] Other(web)

## Your Environment
- Nakama: 2.5.1+8216d5cc
- Cockroach: v2.1.6
- Environment name and version:
- Operating System and version: OSX 10.14.4

**Comment by mofirouz** [comment]
The file you are trying to upload doesn’t match the required format by the system. 

Where is the origin of the file?

**Comment by AlexeyIS** [comment]
@mofirouz Here is the file I try to upload [config.txt](https://github.com/heroiclabs/nakama/files/3203980/config.txt)
Could you please advice on the format for json file?

**Comment by mofirouz** [comment]
I meant what has generated the config.txt file

**Comment by AlexeyIS** [comment]
@mofirouz oh sorry, It was just manually created.

**Comment by mofirouz** [comment]
Ah ok, was there a particular specification you followed to create the JSON records? Ie how did you come up with that structure?

**Comment by AlexeyIS** [comment]
@mofirouz  The end goal is to pull this data from Unity later. The specification for that particular json is coming from internal needs.

**Comment by mofirouz** [comment]
This is the format that the JSON importer expects:

```
[
  {
    "collection": "testcollection",
    "key": "testkey",
    "user_id": "fb912423-82cb-4e3a-8f67-42c37be19a3c",
    "value": "{\"hello\": \"world\"}",
    "permission_read": 2,
    "permission_write": 1
  },
  {
    "collection": "testcollection",
    "key": "testkey2",
    "user_id": "9e997e08-7e81-4d3b-a3d3-3458f7c5e5e1",
    "value": "{\"hello\": \"world\"}",
    "permission_read": 1,
    "permission_write": 1
  }
]
```

**Comment by novabyte** [comment]
@mofirouz We should make a note to add this advice to the docs for the expected import format with the Developer Console. 📓

**Comment by AlexeyIS** [comment]
Thanks for the help guys! I wanted to mention, great that you have such a quick feedback time!
