### ISSUE TITLE
Get migration failed after running command of migration down

### ISSUE THREAD

**Issue by Kobe-Wang** [heroiclabs/nakama#353]
## Description
Hi,

After I run command of migration down, I get the failed error message. Thus, I traced the migration code; I find that the leaderboard table is created the index for the category column as  duration_start_time_end_time_category_idx. However, the migration down did not add to drop this index before the category column is drop.

https://github.com/heroiclabs/nakama/blob/f082f324517ff74612656551c64edb66c30d0468/migrate/sql/20180805174141-tournaments.sql#L46

https://github.com/heroiclabs/nakama/blob/f082f324517ff74612656551c64edb66c30d0468/migrate/sql/20180805174141-tournaments.sql#L65

## Steps to Reproduce

1. Run migration down after migration up
```
$ nakama migrate down
```

## Expected Result

```
{"level":"info","ts":"2019-06-25T18:16:31.570+0800","msg":"Successfully migrated back"...}
```

## Actual Result

```
{"level":"fatal","ts":"2019-06-25T18:13:06.355+0800","msg":"Failed to migrate back","count":0,"error":"pq: column \"category\" is referenced by existing index \"duration_start_time_end_time_category_idx\" handling 20180805174141-tournaments.sql"...}
```

## Your Environment
- Nakama: 2.5.1
- Cockroach: 2.1.7

**Comment by zyro** [comment]
Fix merged and update ready in cef15f91d3f58398a5a19dd63b84e85b3a677095. This will be part of the next release, thanks for the help @Kobe-Wang!
