### ISSUE TITLE
Add GetTournament to server runtime API

### ISSUE THREAD

**Issue by gupta-vaibhav** [heroiclabs/nakama#356]
## Description
GetTournament(s) function is required in NakamaModule, to retrieve a single / multiple tournaments by id.

## Steps to Reproduce
--NA--

## Expected Result
--NA--

## Actual Result
--NA--

## Context
--NA--

## Your Environment
--NA--

**Comment by zyro** [comment]
Added in f35e8b2a2a9fe3b6950e8994bc85485a4acc0a59 and will be part of the next release.
