### ISSUE TITLE
Add public API to detect whenever given e-mail was already registered

### ISSUE THREAD

**Issue by Shelim** [heroiclabs/nakama#358]
Currently there is no official API to check whenever given e-mail was already registered (which may be needed to deviate between login attempt and registration attempt)

There is actually a possibility to check this out with existing API:

 1. Try to log-in with e-mail and random, long password (like 96-letters) and create flag set to false
 2. You will get either authentication failed (if user exists) or resource not found (if user does not exists)

Note that this workaround may be (a bit) broken in next version of Nakama, if you - for example - start informing users about failed login attempts.

It would be nice to be able to check that without such workaround.

One way, without adding new API func, would be to allow null (or empty) second argument (password) to `AuthenticateEmailAsync`. Currently when trying to pass empty string you will get "password too short" error.

**Comment by Shelim** [comment]
Bump?

**Comment by novabyte** [comment]
@Shelim I'm not sure what the value is in this API. To give an endpoint to check if the email address is already registered will allow external bad actors to probe the system with lists of email addresses. How do you suggest we handle that scenario?

**Comment by Shelim** [comment]
@novabyte 
It is still possible to probe e-mail with current code (see my workaround). The value of the API would be to distinguish the case of login from the case of registering an account in UI before actually registering an account (which - for example - might need customized username)

**Comment by zyro** [comment]
Most systems I can think of offer the user a choice between login/register, rather than trying to figure out which should be used automatically.

The API as it stands allows both cases as far as I can see:
* Set `create` to `false` for pure login. This always fails if the account doesn't exist, or the password is bad.
* Set `create` to `true` to enable registration. This will fail if the email is already in use and the password does not match. If it succeeds the `created` flag in the response will be `true` if the account is new and therefore registration succeeded, or `false` if the account existed and the user selected the same password coincidentally - I think it's fine to treat this as just a successful login attempt.

Is there a variation or scenario I'm missing here?

**Comment by Shelim** [comment]
@zyro 

Actually there is; We want to give user ability to merge accounts if they are about to create the new one, before they do so. Already created accounts cannot be merged, link can be made only pre-creating new account.

We displays - for each account provider:
 - This is new account. Are you returning user?
     - If yes, log in onto your other device then go to settings -> link e-mail (or other provider) with this account
     - If no, give us your desired user name (and double-verified password for e-mail)

**Comment by zyro** [comment]
You can't link more than one email to any user account, so I assume you have another authentication method enabled. If that's the case how about authenticating that first, then offering the user the option to link an email account?

There's also the option to unlink the email from one user, then link it to another. It's less trivial than the option above but still doable.

**Comment by Shelim** [comment]
@zyro 
I mean following scenario:

User X has registered Device ID-based account on their mobile. They attempt to login to PC with e-mail. They got the message I mentioned, following which they log in on their mobile, and link e-mail there. They they click "It's done!" on PC side and are logged in to their shared account. Ideally the link to e-mail is passed to their mobile via QR code scanned directly from PC.

**Comment by zyro** [comment]
Having considered this for a while I don't think there's a strong enough case for adding this feature.

What decides it for me is that there's already a pattern that makes this possible in rare cases where it's needed. I feel it shouldn't be a common feature because users should know if they have an email account or not, rather than the client attempting to guess for them.

**Comment by frantic-developer** [comment]
> Most systems I can think of offer the user a choice between login/register, rather than trying to figure out which should be used automatically.
> 
> The API as it stands allows both cases as far as I can see:
> 
>     * Set `create` to `false` for pure login. This always fails if the account doesn't exist, or the password is bad.
> 
>     * Set `create` to `true` to enable registration. This will fail if the email is already in use and the password does not match. If it succeeds the `created` flag in the response will be `true` if the account is new and therefore registration succeeded, or `false` if the account existed and the user selected the same password coincidentally - I think it's fine to treat this as just a successful login attempt.
> 
> 
> Is there a variation or scenario I'm missing here?

I've set up my app this way, here is the scenario I am currently unable to handle:

1. Account exists for a given email
2. user signs up using same email / same password and a different username
3. account creation is done again, new username overwrites the old one, and everything after hook is processed normally as if its a new account

Currently I have no way of checking if an account already exists for a given email at before auth stage, but there are many ways to check if a username exists / userId / and getting an account that way.

this makes email auth kind of annoying to deal with right now

have there been any work arounds for this? or what's best practice in this situation to avoid users signing up multiple times with the same email / password
