### ISSUE TITLE
Received: status=BadRequest, contents='{"error":"http: request body too large","message":"http: request body too large","code":3}'

### ISSUE THREAD

**Issue by AlexeyIS** [heroiclabs/nakama#359]
## Description
Error thrown on WriteStorageObjectsAsync.
What is the size cap for the body? Is there a way to set a limit for that? 
Thank you. 

## Steps to Reproduce
var objectIds = await client.WriteStorageObjectsAsync(session, new WriteStorageObject
{
  Collection = "Data",
  Key = "game",
  Value = "a long json string.........
});

## Expected Result
No error is thrown and results are returned by server.

## Actual Result
Received: status=BadRequest, contents='{"error":"http: request body too large","message":"http: request body too large","code":3}'

## Context

- [x] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: 2.5.1+8216d5cc
- Cockroach: v2.1.6
- Environment name and version: 
- Operating System and version: OS X 10.14.5

**Comment by novabyte** [comment]
Hi @AlexeyIS. This is a better question for our [forum](https://forum.heroiclabs.com/latest) next time. You can see on the [server settings](https://heroiclabs.com/docs/install-configuration/#socket) page that we have an option used to limit the maximum size of a message between client and server:
"--socket.max_message_size_bytes someval". The default size is 4096 bytes.

You should adjust this value for your game to match an upper limit on what you expect the size of your largest data message would look like. The reason we have this value is to protect against an attack vector known as a distributed "slow clients" attack.

**Comment by AlexeyIS** [comment]
Thanks, @novabyte, for some reason, didn't think about the forum:/
