### ISSUE TITLE
Banned users can still execute RPC if they have stored session

### ISSUE THREAD

**Issue by Shelim** [heroiclabs/nakama#361]
## Description
Banned user successfully executed RPC if they have valid stored session; There is no way to determine if user is banned via RPC API. This is extremely important if session token is set to be valid for lengthy period of time

## Steps to Reproduce
1. Log-in via any client
2. Ban user you've just logged in via admin console
3. Execute RPC by client

## Expected Result
RPC should be denied

## Actual Result
RPC was executed and returned valid data

## Context
Tried on Unity and Nakama 2.5.1+8216d5cc and login via device Id

**Comment by Shelim** [comment]
Bump?

**Comment by novabyte** [comment]
Hey @Shelim. I've added this to the development backlog for us to tackle. 👍
