### ISSUE TITLE
Unlink facbook id from user account without oauth token

### ISSUE THREAD

**Issue by oscargoldman** [heroiclabs/nakama#366]
The current unlink facebook api requires a oauth token that matches the current user. With the facebook unity sdk, it pulls the user from the installed facebook app. If a user changes accounts in facebook, there's a mismatch between oauth token and current nakama user, and unlinking fails. 

feature request to make facebook token optional, so we unlink based on facebook and nakama user id instead.

**Comment by jquentin-lion** [comment]
I agree. If we provide an unlink button, it should unlink even if the user is not logged in to that account anymore. So there could be a tokenless unlink function for this case.
