### ISSUE TITLE
Can't see the Nakama Server IP

### ISSUE THREAD

**Issue by FruityMountainCorporation** [heroiclabs/nakama#372]
Hi everyone !

I'm trying to install Nakama on a remote VPS. But I don't know where to see the nakama server IP. I know the VPS one but 
## Description
When I start Nakama on my VPS, I can't see the IP of the server. Where can I find it ?
So I tried the basic connection client code provided by the docs, but on the Unity logs I only see
`System.Threading.Tasks.Task`1[Nakama.ISession]
UnityEngine.Debug:Log(Object)
clientobject:Start() (at Assets/Scripts/Networking/clientobject.cs:15)
`
Can you help me please ?
## Steps to Reproduce
1. `nakama`
2. `	void Start ()
	{
		var client = new Client("http", "37.59.232.249", 7350, "defaultkey");
		const string email = "hello@example.com";
		const string password = "somesupersecretpassword";
		var session = client.AuthenticateEmailAsync(email, password);
		Debug.Log(session);
	}`

## Result
`{"level":"info","ts":"2019-08-27T09:31:20.449Z","msg":"Nakama starting"}
{"level":"info","ts":"2019-08-27T09:31:20.449Z","msg":"Node","name":"nakama","version":"2.6.0+b28f8d96","runtime":"go1.12","cpu":1,"proc":1}
{"level":"info","ts":"2019-08-27T09:31:20.449Z","msg":"Data directory","path":"/home/arenarush/data"}
{"level":"info","ts":"2019-08-27T09:31:20.449Z","msg":"Database connections","dsns":["root@127.0.0.1:26257"]}
{"level":"info","ts":"2019-08-27T09:31:20.457Z","msg":"Database information","version":"CockroachDB CCL v19.1.4 (x86_64-unknown-linux-gnu, built 2019/08/06 15:34:13, go1.11.6)"}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Initializing leaderboard rank cache"}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Leaderboard rank cache initialization completed successfully","cached":[],"skipped":[]}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Initialising runtime","path":"/home/arenarush/data/modules"}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Initialising runtime event queue processor"}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Runtime event queue processor started","size":8192,"workers":8}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Initialising Go runtime provider","path":"/home/arenarush/data/modules"}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Go runtime modules loaded"}
{"level":"info","ts":"2019-08-27T09:31:20.461Z","msg":"Initialising Lua runtime provider","path":"/home/arenarush/data/modules"}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Lua runtime modules loaded"}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Allocating minimum runtime pool","count":16}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Allocated minimum runtime pool"}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Found runtime modules","count":0,"modules":[]}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Starting Console server for gRPC requests","port":7348}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Starting Console server gateway for HTTP requests","port":7351}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Starting API server for gRPC requests","port":7349}
{"level":"info","ts":"2019-08-27T09:31:20.462Z","msg":"Starting API server gateway for HTTP requests","port":7350}
{"level":"info","ts":"2019-08-27T09:31:20.610Z","msg":"Startup done"}
`

## Context
- [ ] Unity 2017
- [ ] Ubuntu 18.04

## Your Environment
- Nakama: 2.6.0+b28f8d96
- Cockroach:  v19.1.4
- Operating System and version: Ubuntu 18.04

**Comment by mofirouz** [comment]
This isn't an issue on Nakama server or the client library. Please post this on the forum to get help:

https://forum.heroiclabs.com
