### ISSUE TITLE
Missing Binaries for 2.7.0 release

### ISSUE THREAD

**Issue by sNakiex** [heroiclabs/nakama#374]
Please add binaries for the 2.7.0 release: https://github.com/heroiclabs/nakama/releases/tag/v2.7.0

**Comment by novabyte** [comment]
This is blocked on a discussion I've raised with the `xgo` team. I'll see what we can achieve with that or we'll fork `xgo` to maintain it as part of our build/release process. https://github.com/techknowlogick/xgo/issues/37

**Comment by novabyte** [comment]
@sNakiex My pull request for `xgo` was accepted and I've been able to cross-compile binaries for the 2.7.0 release:

https://github.com/heroiclabs/nakama/releases/v2.7.0
