### ISSUE TITLE
Plain websocket client

### ISSUE THREAD

**Issue by Salamdev** [heroiclabs/nakama#379]
Hi.
As did for rest api (curl), please add plain websocket client or document. I am using qt quick (qml) and it does not support official js client. I can do rest api in qml by xmlhttprequest but for real time I want something to do that or some tutorial about this.thanks
[https://developer.mozilla.org/en-US/docs/Web/API/WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket)
[https://doc.qt.io/qt-5/qml-qtwebsockets-websocket.html](https://doc.qt.io/qt-5/qml-qtwebsockets-websocket.html)

**Comment by novabyte** [comment]
@Salamdev I think this is a better question for the forums: https://forum.heroiclabs.com. We can discuss it there. 👍
