### ISSUE TITLE
Latency display

### ISSUE THREAD

**Issue by julienBouysset** [heroiclabs/nakama#38]
## I would like a feature that allows you to view the latency of all players in a session.
**Do not hesitate to rephrase my request my English and not very good**

Being able to see both own latency with the server, But also the latency of other players with the server.

To avoid having too much server call and to avoid having an exponential load n², It is necessary to recover the latency between a player and the server and not between the players.

To gain performance this information should be updated every x milliseconds. Would be good to be able to choose in the options the time of refreshing of this information, according to the game. (for exemple : fps 200 milliseconds, mmorpg 1 or 2 seconds)

If possible have two different function to call them if necessary. For example I will ask the latency of the other players that when I display the scores dashbord.

If possible also have a function to have the latency of the server closest and the server of the current session.

# Original text :
## Je voudrais une fonctionnalité qui permet d'afficher la latence de tous les joueurs d'une session

Pouvoir à la fois voir ça propre latence avec le serveur. Mais également la latence des autres joueurs avec le serveur.

Pour éviter d'avoir trop d'appel serveur et pour éviter d'avoir une charge exponentielle n², il faut récupère la latence entre un joueur et le serveur et non entre les joueurs.

Pour gagner en performance ces informations devraient être missent a jours tous les x millisecondes. se serait un plus de pouvoir choisir dans les options le temps de rafraîchissement de ces informations, selon le jeu.

Si possible avoir deux fonction différente pour les appeler au besoin. pour exemple je vais demander le ping des autre joueurs que quand j'affiche le panneux des scores.

Si possible avoir également une fonction pour avoir la latance du serveur le plus proche et du server de la session actuel.

**Comment by novabyte** [comment]
Messages received into an authoritative match handler are tagged with a receive timestamp as soon as they're received off the socket. This can be used to calculate compute time spent in the match loop invocation. It's also very easy to attach timestamps to messages sent by clients and calculate the RTT and therefore latencies from/to various peers.
