### ISSUE TITLE
Identity provider for Apple Sign In

### ISSUE THREAD

**Issue by grant-sessiongames** [heroiclabs/nakama#380]
According to the latest iOS update, making available the Apple Sign In authentication will be required when the application uses any other third party identification platform (ie Facebook).

https://developer.apple.com/sign-in-with-apple/get-started/

We will need an Identity Provider added for Apple Sign In added to Nakama to be in compliance.

Thank you.

**Comment by allfake** [comment]
Now apple apply this rule.
When you submit app and have third party login, but not provide apple sign in.
Your app will be rejected.

**Comment by zyro** [comment]
Added in 4b92d9fb24cd281bf6de00e0c1d3ab82f22029ba, and will be part of the next release.

**Comment by chiehwen** [comment]
@zyro Could I know next release date ?

**Comment by zyro** [comment]
@chiehwen We're aiming to cut the next release before the end of the month. :+1:
