### ISSUE TITLE
Can I horizontal scale with myself ?

### ISSUE THREAD

**Issue by PePoDev** [heroiclabs/nakama#381]
I want to know. Can I horizontal scale Nakama Server with my own server. And use orther function like replica, backup, etc in your enterprise version.

Or I MUST buy your enterprise version only for scale or backup feature ?

**Comment by novabyte** [comment]
@PePoDev Yes, but please ask questions on the [forums](https://forum.heroiclabs.com/).

**Comment by kienvn** [comment]
I found some projects with nakama cluster, but I'm not sure it works:

https://github.com/renowncoder/nakama-doublemo-cp

https://github.com/doublemo/nakama-cluster
