### ISSUE TITLE
Cannot build admin console following instructions in README.me

### ISSUE THREAD

**Issue by crowder** [heroiclabs/nakama#382]
## Description

From the `console/ui` directory, running `yarn run build` as instructed by README.me results in the following failure for me:

<pre>
yarn run v1.19.0
$ react-scripts build
Creating an optimized production build...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`

<--- Last few GCs --->

[5939:0x427ac20]   139338 ms: Scavenge 1219.5 (1288.0) -> 1207.1 (1288.0) MB, 41.8 / 0.0 ms  (average mu = 0.998, current mu = 0.998) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x136d539]
Security context: 0x1ef3a94c08a1 <JSObject>
    1: set [0x1ef3a94c64c1](this=0x1f53b1df97b1 <Map map = 0xc20c96c0ed1>,0x1b0436522991 <String[12]: 36068,220535>,2)
    2: recursiveTypeRelatedTo(aka recursiveTypeRelatedTo) [0x1221a080351] [<my path>/3rdparty/nakama/console/ui/node_modules/typescript/lib/typescript.js:~44114] [pc=0x22f5a964bdb8](this=0x1c2e39dc04a9 <undefined>,0x3881c96c8681 <TypeObject m...

FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: 0x9d33e0 node::Abort() [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 2: 0x9d4596 node::OnFatalError(char const*, char const*) [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 3: 0xb32dbe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 4: 0xb33139 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 5: 0xcde455  [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 6: 0xedbf15 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 7: 0xedc055 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 8: 0xedc69b v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::EnsureGrowable(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>) [<my path>/.nvm/versions/node/v12.11.1/bin/node]
 9: 0xfcede8 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [<my path>/.nvm/versions/node/v12.11.1/bin/node]
10: 0x136d539  [<my path>/.nvm/versions/node/v12.11.1/bin/node]
Done in 145.07s.
</pre>

## Steps to Reproduce

1. Nearly fresh ubuntu server install
2. Running node version v12.11.1
3. No local code changes

## Expected Result

Admin console builds successfully.

## Actual Result

Error above is received.

## Context

Trying to build Nakama by hand as instructed in README.me

## Your Environment

> uname -a
`Linux osboxes 5.0.0-31-generic #33-Ubuntu SMP Mon Sep 30 18:51:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

> node --version
`v12.11.1`

> go version
`go version go1.13.1 linux/amd64`

**Comment by novabyte** [comment]
@crowder I can't reproduce this issue. Might have been due to an older NPM release.
