### ISSUE TITLE
Once records for a user exceed a certain threshold in total size, they no longer show in the consle

### ISSUE THREAD

**Issue by oscargoldman** [heroiclabs/nakama#383]
We're experiencing an issue where exceeding approximately 5mb of data's worth of records for a user, they no longer appear in the console. Selecting records in the particular user's account shows zero records. The records are actually in the db and behave normally, they just can't be viewed in the console.

**Comment by zyro** [comment]
Fixed in 420ad8b25728abb49dadf137b4412ef8d040354e and will be part of the next release.
