### ISSUE TITLE
Adding 0 points to an incremental leaderboard causes discrepancies in the record list

### ISSUE THREAD

**Issue by DaniM** [heroiclabs/nakama#384]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/heroiclabs/nakama) and ask any questions you have or mention any problems you've had getting started with the server.

Please provide as much information as you can with this issue report. If you believe it may be an issue with one of the client libraries please report it on their [own trackers](https://github.com/heroiclabs?utf8=%E2%9C%93&q=nakama%20AND%20sdk&type=&language=).

## Description

Adding 0 points to an incremental leaderboard causes discrepancies in the record list

## Steps to Reproduce

Rename the extension of the attached file to .go (it's a go module). Build an .so and start the server with it.
Using postman or any other tool for sending requests.
1) Auth
2) Send this request to this RPC
URL : `http://<url>/v2/rpc/lb_admin`
BODY: `"{ \"command\":\"ADD\",\"id\":\"<id>\", \"score\":0 }"`
3) Send this request to this RPC
URL : `http://<url>/v2/rpc/lb_admin`
BODY: `"{ \"command\":\"GET\",\"id\":\"<id>\" }"`

## Expected Result

There shouldn't be any discrepancies in the "me/owner" position and the real position on the leaderboard

## Actual Result

The response shows discrepancies between the "owner" position and its real position on the leaderboard

## Context

- [ ] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: 2.6.0
- Cockroach: 2.1.6
- Environment name and version:
- Operating System and version: OSX 10.14.2 Mojave
[go_module.txt](https://github.com/heroiclabs/nakama/files/3742802/go_module.txt)

**Comment by novabyte** [comment]
@DaniM A lot of improvements have been made to leaderboards and tournaments since the 2.6.0 release. I can't reproduce this issue. Please reopen if it's still an issue once you've updated.
