### ISSUE TITLE
[ Security Violation ] API call for custom RPC with http_key executes 

### ISSUE THREAD

**Issue by danieltamas** [heroiclabs/nakama#385]
API calls including the http_key now execute custom functions that alter the database ie: update a user. This should not happen without a valid session and the **Authorization** bearer

## Description
When running a POST **fetch()** call from the client ( Browser ) to a custom RPC + http_key the server executes

## Steps to Reproduce
Create a custom RPC function on the server which updates custom columns in the users table

## Expected Result
Fail without proper authorisation since this is a **write** operation

## Actual Result
The function finishes and updates the DB record(s) even if the call is not authorised / logged in

## Context
- Javascript ( but it's valid for all contexts )

## Your Environment
- Nakama: 2.7.0
- Database: 19.1.5

**Comment by novabyte** [comment]
@danieltamas This is not a security violation at all. The `http_key` is required to be used with server to server function calls as covered [in our documentation](https://heroiclabs.com/docs/runtime-code-basics/#server-to-server). You must not embed it in your game client code.

Use the JavaScript function in the client sdk which takes a session token when you want to use it in your browser game. The RPC function which takes the `http_key` is if you want to use the SDK with a server to server function call. This is the same across all our SDKs.

**Comment by danieltamas** [comment]
Ah. got it. You are correct plus you just solved a debate here. However, maybe it would be useful to call it **api_key** or **secret_key** as this is why it lead to this confusion

**Comment by novabyte** [comment]
@danieltamas That's a good point. We could rename it but it would break our promise of backwards compatibility so we'd have to support both options as inputs and overload them in the server to combine to a single value. I'll make a note to talk about it with the team.
