### ISSUE TITLE
[NRtClient::onTransportMessage] NRtError: BAD_INPUT

### ISSUE THREAD

**Issue by stonekase** [heroiclabs/nakama#394]
Before you submit an issue we recommend you drop into the [community forum](https://forum.heroiclabs.com) and ask any questions you have or mention any problems you've had getting started with the server.

Please provide as much information as you can with this issue report. If you believe it may be an issue with one of the client libraries please report it on their [own trackers](https://github.com/heroiclabs?utf8=%E2%9C%93&q=nakama%20AND%20sdk&type=&language=).

## Description

Error thrown by CPP client 

## Steps to Reproduce

Create a Nakama CPP client on xcode 

then add to matchmaker 

    void joinMatcher(const int32_t& minCount,const int32_t& maxCount,const string& query,
                     NStringMap stringProperties,NStringDoubleMap numericProperties){
        
        auto successCallback = [](const NMatchmakerTicket& ticket)
         {
           std::cout << "Matchmaker ticket: " << ticket.ticket << std::endl;
         };

         //int32_t minCount = 2;
        // int32_t maxCount = 4;
         //string query = "*";
         //NStringMap stringProperties;
        // NStringDoubleMap numericProperties;
         //stringProperties.emplace("region", "africa");
         //numericProperties.emplace("rank", 8.0);
        std::cout << "minCount: " << minCount << std::endl;

         _rtClient->addMatchmaker(
             minCount,
             maxCount,
             query,
             stringProperties,
             numericProperties,
             successCallback);
        
        _listener.setMatchmakerMatchedCallback([](NMatchmakerMatchedPtr matched)
        {
          std::cout << "Matched! matchId: " << matched->matchId << std::endl;
        });
    }

## Expected Result

[NRtClient::onTransportMessage] NRtError: BAD_INPUT

## Actual Result

[NRtClient::updateStatus] ...
[NWebsocketCppRest::send] sending 31 bytes binary ...
minCount: 2
[NRtClient::addMatchmaker] ...
[NWebsocketCppRest::send] sending 6 bytes binary ...
[NWebsocketCppRest::operator()] socket message received 95 bytes
[NWebsocketCppRest::operator()] socket message received 3 bytes
Status updated
[NWebsocketCppRest::operator()] socket message received 211 bytes
[NWebsocketCppRest::operator()] socket message received 44 bytes
[NRtClient::onTransportMessage] NRtError: BAD_INPUT
Invalid minimum count, must be >= 2
[NWebsocketCppRest::operator()] ping

## Context

- [ ] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: X.X.X
- Database: X.X.X
- Environment name and version:
- Operating System and version:
Nakama 2.7.0
I am using :
Mac OS Catalina
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	1037.40.124.0.0 (iBridge: 17.16.11081.0.0,0)
  Serial Number (system):	C02XHCN8JG5J
  Hardware UUID:	B43B190C-C4C5-58B3-9BE4-0CF3FB691206
  Activation Lock Status:	Enabled

**Comment by mofirouz** [comment]
This is a client issue. Please reopen it on the respective client library:

https://github.com/heroiclabs/nakama-cpp
https://github.com/heroiclabs/nakama-unreal
https://github.com/heroiclabs/nakama-cocos2d-x

Thanks.
