### ISSUE TITLE
Docs should mention keys must be base64 encoded

### ISSUE THREAD

**Issue by Godatplay** [heroiclabs/nakama#398]
## Description
Documentation should mention the server key must be base64 encoded

## Expected Result
A mention that keys should be base64 encoded in the Configuration section, such as roughly in the same place as the warnings about "change your keys when you go into production!"

## Actual Result
No mention anywhere in the docs. When connecting with a key that is not base64 encoded, the response is an invalid server key error.

## Context
- [x] Unity

## Your Environment
Nakama v2.8.0 (in Docker)
CockroachDB v19.2.0 (in Docker)
nginx & Letsencrypt cert routing to ports via https TLS

**Comment by zyro** [comment]
There's no requirement for keys to be Base64 strings, any random value should be fine. What key value did you use?

**Comment by Godatplay** [comment]
Oh, weird... I used a password generator, with symbols enabled. Are there some symbols that aren't allowed?

**Comment by Godatplay** [comment]
Here's an example: `AMk^:E}^M>sbp+KkYJRmpyL4*Y4YMW}**.8^iU4PiyFJ*h?>FYKEWsPt*s}_ZFPA`

**Comment by Godatplay** [comment]
Have you all been able to confirm this? It's not just me, right?

**Comment by novabyte** [comment]
@Godatplay How did you set the server key? By YML configuration or on the command line?

**Comment by Godatplay** [comment]
Oh, good question, by YML

**Comment by novabyte** [comment]
@Godatplay I ran these steps.

1. Use quotes in the YML configuration file for Nakama:

   ```yml
   socket:
     server_key: "AMk^E}^M>sbp+KkYJRmpyL4*Y4YMW}**.8^iU4PiyFJ*h?>FYKEWsPt*s}_ZFPA"
   ```

2. Start the database server and game server:

   ```
   brew services start postgres
   nakama --database.address "$USER@127.0.0.1:5432/nakama" --logger.level DEBUG --config ./nakama.yml
   ```

3. Run a curl command to authenticate a new user.

   ```
   curl "http://127.0.0.1:7350/v2/account/authenticate/device" --data "{\"id\": \""$(uuidgen)"\"}" --user "AMk^E}^M>sbp+KkYJRmpyL4*Y4YMW}**.8^iU4PiyFJ*h?>FYKEWsPt*s}_ZFPA:"
   ```

NOTE: I removed the `:` (colon) from the server key you'd created because it makes it difficult to use `--user` in curl but causes no problem with Nakama.

I can't see any kind of issue with using a password that comes from a generator.

**Comment by Godatplay** [comment]
Thanks for your help. I'm on Ubuntu 18.04, Nakama and Cockroach run via Docker Compose, and I get to my server via nginx & Letsencrypt. My only remaining thought is this could have to do with using HTTPS? I'll see if I can find some time to try removing the `:` and disabling HTTPS and see if that changes anything.
