### ISSUE TITLE
Server and cluster information

### ISSUE THREAD

**Issue by julienBouysset** [heroiclabs/nakama#40]
### I would like to have the possibility that the player then get the following information:

- retrieves the alias or name of the server where it and connect in socket.
- retrieves the latency of the server where it and connect in socket. # 38

- retrieves the alias or name of the server where it locates the room.
- retrieves the latency of the server where it locates the room. # 38

All this information will allow the players to better understand their latency with the servers and the room even to choose which room they want to join.

**Comment by novabyte** [comment]
This can all be achieved with the authoritative multiplayer engine and a timestamp attached to messages sent by clients. The name of the server which hosts the match is encoded into the matchid although this information does not need to be processed by clients directly. A client can join any server and Nakama will route messages inter cluster to the correct match handler on the match host server.
