### ISSUE TITLE
Incorrect Content-Type header in response for server-to-server communication

### ISSUE THREAD

**Issue by valashko** [heroiclabs/nakama#401]
## Description
I believe these are 2 separate but related issues:
1. `Content-Type` in response is controlled by `Accept-Encoding` instead of `Accept` in request
2. Given request contains `Accept-Encoding: identity`, `Content-Type` in response is reported as `text/plain` despite Nakama actually sends json (both with `&unwrap=true` and without)

## Steps to Reproduce
- Create a lua module, which responds anything to incoming request
- Send GET request with headers [`Accept-Encoding: gzip, deflate` or `Accept-Encoding: identity`], `Accept: application/json`

## Expected Result
Server response has `Content-Type: application/json`

## Actual Result
Server response has `Content-Type: application/x-gzip` or `Content-Type: text/plain; charset=utf-8`

## Your Environment
- Nakama: 2.8.0
- Database: does not matter
- Environment name and version: does not matter
- Operating System and version: does not matter

**Comment by novabyte** [comment]
Thanks for the report @valashko. We'll have a look at this as part of the final release before Christmas.

**Comment by valashko** [comment]
Any updates on the issue?

**Comment by alykhvar-gsn** [comment]
The issue is also reproduceable on nakama v2.12.0-r3+f26161c when you add header `Accept-Encoding: gzip, deflate, br`.

```
curl -v -H 'Accept-Encoding: gzip, deflate, br' 'http://example.com/v2/rpc/endpoint'

> Host: example.com
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
> Accept: */*
> Accept-Encoding: gzip, deflate, br
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200
< cache-control: no-store, no-cache, must-revalidate
< content-encoding: gzip
< vary: Accept-Encoding
< date: Thu, 11 Jun 2020 13:46:29 GMT
< content-length: 147
< via: 1.1 google
< alt-svc: clear
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 147)
* stopped the pause stream!
* Connection #0 to host example.com left intact
* Closing connection 0
```
