### ISSUE TITLE
Request: Add Demote Operation In Group

### ISSUE THREAD

**Issue by ernesernesto** [heroiclabs/nakama#402]
## Description
As explained in https://forum.heroiclabs.com/t/handling-demote-for-the-receiving-user/383/2 we want to have a way from the client to easily demote user in a group. While current method to demote is available via removing from group and then re-added it, from the pov of the user being demoted will received two messages, kicked and then added, which will cause confusion to that user. It would be better to handle it if we have message code for Demotion and a way for a client to demote user

## Context
- [x] Unity

## Your Environment
- Nakama: 2.8.0

**Comment by sesposito** [comment]
Resolved in #445
