### ISSUE TITLE
Request: Pagination of storage records and filter by collection name

### ISSUE THREAD

**Issue by oscargoldman** [heroiclabs/nakama#403]
we have a lot of system owned records and in the console there's no way to see them all or filter them by collection name. It seems there's a max limit of how many records will display for a user, and no pagination controls to see additional records. Alternately or in addition, to be able to filter records per user by collection name would be handy.

**Comment by novabyte** [comment]
@oscargoldman This is solved in the 3.0 release which will be out soon. We've overhauled the Console UI to support better filter and pagination options with the storage engine. 👍
