### ISSUE TITLE
Help needed for creating multiple tournaments

### ISSUE THREAD

**Issue by SinaZK** [heroiclabs/nakama#405]
SinaZK
1m
Hi, Currently I’m working on a game very similar to toon blast (mobile platform) and I want to use nakama for tournament backend. Currently I’ve got around 60K downloads for my game. My game has more than 300 puzzle levels. Now I want to to add tournament to my game which every tournament has around 30 to 50 players in it which they are around similar levels. Each tournament last around 3 to 5 days. How should I implement this in nakama? I have the current level of each player in nakama user metadata. It seems I should create around 2K tournaments and add the players to their respected tournament. How should I do that?

**Comment by mofirouz** [comment]
GitHub issues are not the place to post questions. I see you’ve already found the forum and copy pasted your question there.

https://forum.heroiclabs.com/t/help-needed-for-tournament-design
