### ISSUE TITLE
Problem with users_get_username

### ISSUE THREAD

**Issue by SinaZK** [heroiclabs/nakama#406]
the user.id from users_get_username users returned is nil and i can't use it for joining the tournament. 
`local usernames = {"b7865e7e", "c048ba7a"}
local users = nk.users_get_username(usernames)
for _, u in ipairs(users)
do
  local message = ("id: %q, displayname: %q"):format(u.id, u.display_name)
  nk.logger_info(message)
end`

all output ids are nil.

**Comment by zyro** [comment]
Should be `u.user_id`.
