### ISSUE TITLE
Not able to do CURL on local.

### ISSUE THREAD

**Issue by ANURAGX** [heroiclabs/nakama#408]
curl "http://127.0.0.1:7350/v2/account/authenticate/custom?create=true&username=allmight" \
  --user "defaultkey:" \
  --data '{"id": "someuniqueidentifier"}'

The above mentioned curl is not working.
The OS used is Mac catalina.
Built the source version of Nakama using Intellij.

<img width="1680" alt="Screenshot 2020-01-05 at 1 38 33 PM" src="https://user-images.githubusercontent.com/5199691/71777028-bf6c6600-2fc0-11ea-84aa-3eaeeef279ae.png">
<img width="1680" alt="Screenshot 2020-01-05 at 1 38 50 PM" src="https://user-images.githubusercontent.com/5199691/71777029-c004fc80-2fc0-11ea-8c33-e002858e404d.png">

**Comment by mofirouz** [comment]
It seems like Nakama is not running on your machine. Please make sure you have the database setup and running. 

Please follow the guides online:
https://heroiclabs.com/install-binary/

Your output clearly mentions connection refused which means Nakama hasn’t started properly. 

If you have questions or problems using Nakama please consider using the forum - GitHub issues are for bugs or feature discussions.
