### ISSUE TITLE
Server use Error IDs when returning errors to the client

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama#41]
This was asked in Gitter. 

> Will there be proper Error ID in the future?
For example, when a user is the last admin and calls NGroupLeaveMessage.Default, an error would be thrown stating that he is the last admin, so he cant leave, he has to remove the guild. But currently I cant handle the error, according to the reasons on why he cant leave the group because there could be many errors that might be thrown back to me

It would be useful to return Error IDs to the client so that developers can match on IDs (rather than strings) and handle client code nicer.

This could be tackled along with issue #9.

**Comment by novabyte** [comment]
This is a great improvement we can make which'll help developers easily handle error states in game client code. I propose we use the same design pattern as Google for error codes:

https://cloud.google.com/apis/design/errors

Have a look at `google.rpc.Code` as well - https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto

**Comment by novabyte** [comment]
Added in https://github.com/heroiclabs/nakama/commit/a3f6988b264fb6f6c8ebb6ef7d998bc9469a2133.
