### ISSUE TITLE
Server Crash after using dispatcher to send broadcast to nakama-godot client

### ISSUE THREAD

**Issue by stonekase** [heroiclabs/nakama#410]
Before you submit an issue we recommend you drop into the [community forum](https://forum.heroiclabs.com) and ask any questions you have or mention any problems you've had getting started with the server.

Please provide as much information as you can with this issue report. If you believe it may be an issue with one of the client libraries please report it on their [own trackers](https://github.com/heroiclabs?utf8=%E2%9C%93&q=nakama%20AND%20sdk&type=&language=).

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

## Steps to Reproduce
1. Register a new user
2. Connect to server socket
3. add to matcher
4. join match after on_matched is called
5 send broadcast to clients using nill in game loop then error.

## Expected Result
{"level":"info","ts":"2020-02-06T12:41:39.650+0100","msg":"My body no go gree","mid":"937ced6b-5005-4097-a90f-8f2c55d08ed9"}
{"level":"info","ts":"2020-02-06T12:41:39.650+0100","msg":"User added to match 'table: 0xc000a28000'","mid":"937ced6b-5005-4097-a90f-8f2c55d08ed9"}
{"level":"debug","ts":"2020-02-06T12:41:39.650+0100","msg":"Processing presence event","joins":1,"leaves":0}
{"level":"debug","ts":"2020-02-06T12:41:39.650+0100","msg":"Sending *rtapi.Envelope_Match message","uid":"889c3b43-eeb1-4c73-983f-bc76ca04ac9d","sid":"396d69ac-d185-4198-a95e-f20014763ca7","envelope":"cid:\"2\" match:<match_id:\"937ced6b-5005-4097-a90f-8f2c55d08ed9.nakama-node-1\" authoritative:true label:<value:\"Quickplay\" > size:1 presences:<user_id:\"1831b11b-2da0-4e46-a2be-f8e8a5d3f530\" session_id:\"826cc6e4-5aca-40f2-8c36-5bfed282da97\" username:\"ashtonkase\" > self:<user_id:\"889c3b43-eeb1-4c73-983f-bc76ca04ac9d\" session_id:\"396d69ac-d185-4198-a95e-f20014763ca7\" username:\"G:10115341080\" > > "}
{"level":"warn","ts":"2020-02-06T12:41:40.589+0100","msg":"Stopping match after error from match_loop execution","mid":"937ced6b-5005-4097-a90f-8f2c55d08ed9","tick":0,"error":"runtime error: invalid memory address or nil pointer dereference\ngoroutine 412 [running]:\ngithub.com/yuin/gopher-lua.(*LState).PCall.func1(0x52b6b08, 0xc0004553f0, 0xc001293bc0, 0x0, 0x0, 0x2)\n\tgithub.com/yuin/gopher-lua@v0.0.0-20190514113301-1cd887cd7036/state.go:1964 +0x633\npanic(0x4f067e0, 0x5fb2470)\n\truntime/panic.go:679 +0x1b2\ngo.uber.org/atomic.(*Bool).Load(...)\n\tgo.uber.org/atomic@v1.4.0/atomic.go:233\ngithub.com/heroiclabs/nakama/v2/server.(*RuntimeLuaMatchCore).broadcastMessage(0xc00119e140, 0xc0004553f0, 0x2)\n\tgithub.com/heroiclabs/nakama/v2@/server/runtime_lua_match_core.go:513 +0x2a\ngithub.com/yuin/gopher-lua.callGFunction(0xc0004553f0, 0x0, 0xc0012b2ac0)\n\tgithub.com/yuin/gopher-lua@v0.0.0-20190514113301-1cd887cd7036/vm.go:163 +0x40\ngithub.com/yuin/gopher-lua.init.3.func26(0xc0004553f0, 0xc07c140205, 0xc001272000, 0x0)\n\tgithub.com/yuin/gopher-lua@v0.0.0-20190514113301-1cd887cd7036/vm.go:764 +0x3ae\ngithub.com/yuin/gopher-lua.mainLoopWithContext(0xc0004553f0, 0xc001272000)\n\tgithub.com/yuin/gopher-lua@v0.0.0-20190514113301-1cd887cd7036/vm.go:60 +0x11d\ngithub.com/yuin/gopher-lua.(*LState).callR(0xc0004553f0, 0x5, 0xffffffffffffffff, 0x2)\n\tgithub.com/yuin/gopher-lua@v0.0.0-20190514113301-1cd887cd7036/state.go:1191 +0x248\ngithub.com/yuin/gopher-lua.(*LState).Call(...)\n\tgithub.com/yuin/gopher-lua@v0.0.0-20190514113301-1cd887cd7036/state.go:1943\ngithub.com/yuin/gopher-lua.(*LState).PCall(0xc0004553f0, 0x5, 0xffffffffffffffff, 0x0, 0x56030e0, 0xc00098f1c0)\n\tgithub.com/yuin/gopher-lua@v0.0.0-20190514113301-1cd887cd7036/state.go:2006 +0x136\ngithub.com/heroiclabs/nakama/v2/server.(*RuntimeLuaMatchCore).MatchLoop(0xc00119e140, 0x0, 0x50a7440, 0xc00092b620, 0xc00092baa0, 0x4041d8c, 0xc00040bfd8, 0x8, 0x0)\n\tgithub.com/heroiclabs/nakama/v2@/server/runtime_lua_match_core.go:454 +0x2bf7\ngithub.com/heroiclabs/nakama/v2/server.loop(0xc0013b8ea0)\n\tgithub.com/heroiclabs/nakama/v2@/server/match_handler.go:256 +0x91\ngithub.com/heroiclabs/nakama/v2/server.NewMatchHandler.func2(0xc0013b8ea0)\n\tgithub.com/heroiclabs/nakama/v2@/server/match_handler.go:182 +0x157\ncreated by github.com/heroiclabs/nakama/v2/server.NewMatchHandler\n\tgithub.com/heroiclabs/nakama/v2@/server/match_handler.go:169 +0x6ac\n\nstack traceback:\n\t[G]: in function 'broadcast_message'\n\tdata/modules/quickplay.lua:56: in main chunk\n\t[G]: ?"}

## Context
Using Nakama-Godot official plugin v1.0

## Your Environment

- Nakama: 2.9.1+8f527a71
- Database: CockroachDB CCL v19.2.2 (x86_64-apple-darwin14, built 2019/12/11 01:27:47, go1.12.12)
- Environment name and version: 
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
- Operating System and version:
OSX Catalina

=============GDSCRIPT ======
extends Control

var game_center = null
var _settings = {
	"credentials": {
		"display_name":"",
		"email":"",
		"password":""
	}
}

var scheme = "http"
export var host = "192.168.1.31"
#export var host = "127.0.0.1"
export var port = 7350
var server_key = "defaultkey"
var client := Nakama.create_client(server_key, host, port, scheme)

var session : NakamaSession = null
var socket = null

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	Settings.save_settings(_settings)
	Settings.load_settings(_settings)
	# check if the user login details is available 
	if  OS.get_name() == "iOS" and Engine.has_singleton("GameCenter"):
		game_center = Engine.get_singleton("GameCenter")
		#var result = game_center.get_instance_id()
		if game_center.is_authenticated():
			game_center.request_identity_verification_signature()
		else:
			$Label.set_text("An error Occured, Exiting")
			$Timer.start(3)
	elif OS.get_name() == "Android":
		pass
	elif OS.get_name() == "OSX":
		var file2Check = File.new()
		var doFileExists = file2Check.file_exists(Settings.SAVE_PATH);
		if (doFileExists):
			var display_name = Settings.get_setting(_settings,"credentials", "display_name")
			var email = Settings.get_setting(_settings,"credentials", "email")
			var password = Settings.get_setting(_settings,"credentials", "password")
			if(email != null && password != null && display_name != null && email != "" && password != ""  && display_name != ""):
				session  = yield(client.authenticate_email_async(email, password,display_name), "completed")
				print("Printing session :: ",session.token)
				if session.is_valid() :
					$Label.set_text("Searching for players")
					socket = Nakama.create_socket_from(client)
					socket.connect("connected", self, "_on_socket_connected")
					socket.connect("closed", self, "_on_socket_closed")
					socket.connect("received_error", self, "_on_socket_error")
					socket.connect("received_matchmaker_matched", self, "_on_received_matchmaker_matched")
					socket.connect("received_match_state", self, "_on_received_match_state")
					socket.connect("received_match_presence", self, "_on_received_match_presence")
					yield(socket.connect_async(session), "completed")
					#var ticket = yield(socket._send_async({ "matchmaker_add": {"min_count": 2,"max_count": 2,"query": "*"}}),"completed")
					var ticket = yield(socket.add_matchmaker_async("*",2,2,{},{}),"completed")
					print("Ticket : ",ticket.ticket)
					print("Done")
				else:
					$Label.set_text("An error Occured, Exiting")
					$Timer.start(2)
					pass	
			else:
				$Label.set_text("An error Occured, Exiting")
				$Timer.start(2)
		else :
			$Label.set_text("An error Occured, Exiting")
			$Timer.start(2)
	
func _on_socket_connected():
	print("Socket connected.")

func _on_socket_closed():
	print("Socket closed.")

func _on_socket_error(err):
	printerr("Socket error %s" % err)
	
func _on_received_matchmaker_matched(p_matchmaker_matched):
	$Label.set_text("Player Matched")
	print("Player Matched %s" % p_matchmaker_matched.match_id)
	#Now join the match
	var join = yield(socket.join_matched_async(p_matchmaker_matched),"completed")
	print("Join Match : ",join)
	#print("Matched")
	
func _on_received_match_state(p_match_state):
	print("Received Match State %s" % p_match_state)
	
func _on_received_match_presence(p_match_presence_event):
	print("Received Presence  event %s" % p_match_presence_event)
	
func _process(delta: float) -> void:
	if  OS.get_name() == "iOS" and Engine.has_singleton("GameCenter"):
		check_events()

func _on_FadeIn_fade_finished() -> void:
	get_tree().change_scene("res://scenes/Home.tscn")

func _on_Timer_timeout() -> void:
	$FadeIn.show()
	$FadeIn.fade_in()
	
func check_events():
	while game_center.get_pending_event_count() > 0:
		var event = game_center.pop_pending_event()
		if event.type == "authentication":
			if event.result == "ok":
				pass
			else:
				$Label.set_text("An error Occured, Exiting")
				$Timer.start(2)
		elif event.type == "identity_verification_signature":
			if event.result == "ok":
				#logging to nakama using the gotten credentials
				#authenticate_game_center_async(p_bundle_id : String, p_player_id : String, p_public_key_url : String,
				#p_salt : #String, p_signature : String, p_timestamp_seconds : String, p_username = null, p_create : bool = true, p_vars = null)
				print(event)
				session  = yield(client.authenticate_game_center_async("whotfire",event.player_id,event.public_key_url,event.salt,event.signature,  str(event.timestamp),  str(event.player_id),true),"completed")
				print("Printing session :: ",session.token)
				if session.is_valid():
					$Label.set_text("Searching for players")
					socket = Nakama.create_socket_from(client)
					socket.connect("connected", self, "_on_socket_connected")
					socket.connect("closed", self, "_on_socket_closed")
					socket.connect("received_error", self, "_on_socket_error")
					socket.connect("received_matchmaker_matched", self, "_on_received_matchmaker_matched")
					socket.connect("received_match_state", self, "_on_received_match_state")
					socket.connect("received_match_presence", self, "_on_received_match_presence")
					yield(socket.connect_async(session), "completed")
					
					var ticket = yield(socket.add_matchmaker_async("*",2,2,{},{}),"completed")
					print("Ticket : ",ticket.ticket)
					print("Done")
				else:
					$Label.set_text("An error Occured, Exiting")
					$Timer.start(2)	
					pass
			else:
				$Label.set_text("An error Occured, Exiting")
				$Timer.start(2)

**Comment by novabyte** [comment]
@stonekase Please can you share the Lua code you've configured for the matchmaker callback?

**Comment by stonekase** [comment]
> @stonekase Please can you share the Lua code you've configured for the matchmaker callback?


Match_init
===========
local nk = require("nakama")

-- For example let's create a two player authoritative match.
local function matchmaker_matched(context, matched_users)
  -- print matched users
  for _, user in ipairs(matched_users) do
    local presence = user.presence
    nk.logger_info(("Matched user '%s' named '%s'"):format(presence.user_id, presence.username))
    for k, v in pairs(user.properties) do
      nk.logger_info(("Matched on '%s' value '%s'"):format(k, v))
    end
  end

  nk.logger_info("Creating a Quickplay match")
  local modulename = "quickplay"
  local setupstate = {invited = matched_users}
  local matchid = nk.match_create(modulename, setupstate)
  return matchid
end
nk.register_matchmaker_matched(matchmaker_matched)


=====================quickplay===================

local nk = require("nakama")
--local du = require("debug_utils")

local M = {}

function M.match_init(context, setupstate)
  local state = {
    presences = {}
  }
  nk.logger_info("Timaya don come again")
  local tickrate = 1 -- per sec
  local label = "Quickplay"
  return state, tickrate, label
end

function M.match_join_attempt(context, dispatcher, tick, state, presence, metadata)
  local acceptuser = true
  return state, acceptuser
end

function M.match_join(context, dispatcher, tick, state, presences)
  nk.logger_info("My body no go gree")
  for _, presence in ipairs(presences) do
    state.presences[presence.session_id] = presence
    nk.logger_info(("User added to match '%s'"):format(state.presences[presence.session_id]))
  end
  return state
end

function M.match_leave(context, dispatcher, tick, state, presences)
  for _, presence in ipairs(presences) do
    state.presences[presence.session_id] = nil
  end
  return state
end

function M.match_loop(context, dispatcher, tick, state, messages)
  for _, presence in pairs(state.presences) do
    --nk.logger_info(("Presence %s named %s"):format(presence.user_id, presence.username))
    --.broadcast_message(101, "", nil, nil)
  end
  for _, message in ipairs(messages) do
    nk.logger_info(("Received %s from %s"):format(message.data, message.sender.username))
    local decoded = nk.json_decode(message.data)
    for k, v in pairs(decoded) do
      nk.logger_info(("Message key %s contains value %s"):format(k, v))
    end
    print("Data Message : '%s'", message.data)
    print("Data Sender : '%s'", message.sender)
    -- PONG message back to sender
    local status, result = pcall(dispatcher.broadcast_message(1, message.data, nil,{message.sender}))
    if (not status) then
      nk.logger_error(("Error occurred: %q"):format(result))
    end
  end
  local opcode = 1234
  local message = { ["hello"] = "world" }
  local encoded = nk.json_encode(message)
  local presences = nil -- send to all.
  local sender = nil -- used if a message should come from a specific user.
  dispatcher.broadcast_message(opcode, encoded, presences, sender)
  return state
end

function M.match_terminate(context, dispatcher, tick, state, grace_seconds)
  local message = "Server shutting down in " .. grace_seconds .. " seconds"
  dispatcher.broadcast_message(2, message)
  return nil
end

return M

**Comment by zyro** [comment]
Thanks for reporting this! Fixed in https://github.com/heroiclabs/nakama/commit/76d7c1404eced863f1b08598b04682e2f7d810b9 and will be part of the next release. If you need to you can use 2.8.0 for now, it's unaffected by this issue.
