### ISSUE TITLE
Update username in leaderboard records

### ISSUE THREAD

**Issue by Goutte** [heroiclabs/nakama#413]
## Steps to Reproduce

Example:
1. Create a new leaderboard
2. Create a user with username "AAA"
3. Add a record for them to the leaderboard
4. Update username "AAA" to "BBB"
5. List leaderboard records.  Username is still "AAA"

## Expected Result
Get "BBB" as username in the record when listing the leaderboard.

Would also be coherent if the username got updated when a new record was submitted.

## Environment

- Nakama: 2.9.1+31694947

## Disclaimer

New (very) to Nakama.  Loving it 😍
I'm not entirely sure what usernames are about and whether we should rely on them at all when fetching leaderboard records instead of individually fetching user profiles from their IDs to get the display name.  (multiple requests overhead?)  But there is no such API yet for Gdscript, and the username not updating is weird behavior anyway.

---

Happily tested Nakama (with on-demand leaderboard creation, since all maps are generated using a seed) on [Octron Mania](https://framagit.org/godotrio/octron-mania) (it's FLOSS).

**Comment by zyro** [comment]
Usernames are a convenient unique label for the user. They're designed to be more human-readable than user IDs so they're useful for example when [adding friends](https://heroiclabs.com/docs/social-friends/#add-friends) by name. They're stored alongside various other pieces of data (like leaderboard scores) where you might usually want to see the username at the same time, and we want to save another round trip to the server or a separate lookup.

Updating usernames on leaderboard score submissions was added in [Nakama 2.10.0](https://github.com/heroiclabs/nakama/releases/tag/v2.10.0) - I would start by updating to at least this release, unless there's a particular reason you need to stay on 2.9.1?

Also when changing the username make sure to re-authenticate the user immediately after, get a new session token, and discard the old one. Nakama session tokens also act as an edge cache and encode the username to save lookup time.

**Comment by Goutte** [comment]
Thanks @zyro !  It makes sense now. :)
I overlooked the 2.10.0 release, and the 2.11.0 as well.  Sorry about the bother.

---

And thanks for the tip about the session ; I'm still experimenting a lot, this will help during the refactoring.
