### ISSUE TITLE
Could not open Go module

### ISSUE THREAD

**Issue by dongshimou** [heroiclabs/nakama#417]
## Description

run  `nakama` load .so module error. 

## Your Environment

- Nakama: v2.11.1 (https://github.com/heroiclabs/nakama/releases/download/v2.11.1/nakama-2.11.1-darwin-amd64.tar.gz)
- Database: 
- Environment name and version: golang v1.13.8
- Operating System and version: darwin/amd64

## error

"plugin.Open(\"xxxx/nakama-module/libhello\"): plugin was built with a different version of package internal/cpu","stacktrace":"github.com/heroiclabs/nakama/v2/server.openGoModule\n\tgithub.com/heroiclabs/nakama/v2/server/runtime_go.go:2057\ngithub.com/heroiclabs/nakama/v2/server.NewRuntimeProviderGo\n\tgithub.com/heroiclabs/nakama/v2/server/runtime_go.go:1971\ngithub.com/heroiclabs/nakama/v2/server.NewRuntime\n\tgithub.com/heroiclabs/nakama/v2/server/runtime.go:465\nmain.main\n\tgithub.com/heroiclabs/nakama/v2/main.go:130\nruntime.main\n\truntime/proc.go:203"}

**Comment by dongshimou** [comment]
module code
```go
package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"

	"github.com/heroiclabs/nakama-common/runtime"
)

func InitModule(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, initializer runtime.Initializer) error {
	logger.Info("start InitModule")
	// Register the RPC function.
	if err := initializer.RegisterRpc("hello", Hello); err != nil {
		logger.Error("Unable to register: %v", err)
		return err
	}
	logger.Info("InitModule success")
	return nil
}
func Hello(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, payload string) (string, error) {
	logger.Info("call hello")
	meta := make(map[string]interface{})
	// Note below, json.Unmarshal can only take a pointer as second argument
	if err := json.Unmarshal([]byte(payload), &meta); err != nil {
		// Handle error
		logger.Error("Unmarshal err:%v", err)
		return "", err
	}
	//NotificationSend(ctx context.Context, userID, subject string, content map[string]interface{}, code int, sender string, persistent bool) error
	userId, ok := ctx.Value(runtime.RUNTIME_CTX_USER_ID).(string)
	if !ok {
		// User ID not found in the context.
		return "", errors.New("userId not found!")
	}
	logger.Info("userid:%v", userId)
	if err := nk.NotificationSend(ctx, userId, "233", map[string]interface{}{"hello": "world"}, 0, "master", false); err != nil {
		logger.Error("NotificationSend err:%v", err)
		return "", err
	}

	return "Success", nil
}

```

**Comment by zyro** [comment]
@dongshimou The error message `plugin was built with a different version of package internal/cpu` is a little cryptic but it's the Go runtime's way of saying the application and the shared object you're trying to load were built with different versions of the Go runtime.

You'll see in Nakama's startup logs that 2.11.1 was built with Go 1.14.1. Update your local environment and build your module again with Go 1.14.1.

I'll close this now since it's not a Nakama issue. If you need more help head over to [the forum](https://forum.heroiclabs.com).

**Comment by dongshimou** [comment]
when i upgrade v1.14.1.
plugin was built with a different version of package github.com/golang/protobuf/proto"

i found the diff:

https://github.com/heroiclabs/nakama/blob/master/go.mod#L29
https://github.com/heroiclabs/nakama-common/blob/master/go.mod#L6

**Comment by novabyte** [comment]
@dongshimou That's a good catch thanks. We'll apply the dependency updates but in the meantime for your project you should be able to do:

```
env GO111MODULE=on go get "github.com/golang/protobuf@v1.3.5"
```

So it will be added to your modfile.
