### ISSUE TITLE
rpc error

### ISSUE THREAD

**Issue by dongshimou** [heroiclabs/nakama#418]
## Description

cpp client

```cpp
        auto jstr=R"( {"abdefawdc":"233"} )";
        m_realtime_client->rpc("hello",jstr, [&](const Nakama::NRpc &rpc) {
                Nakama::NLogger::Debug(rpc.payload, "hello-callback");
            });
```
some error happend;
`
[libprotobuf ERROR ../../../../third_party/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:626] String field 'nakama.api.Rpc.payload' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
`

if i use the `m_client->rpc("hello",jstr)`.

the server goland code will get the truncation payload.
```
func Hello(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, payload string) (string, error) {
	logger.Info("call hello : %s", payload)
//other code
}
```
log :
`
{"level":"info","ts":"2020-04-03T11:15:14.251+0800","msg":"call hello : awdc\":\"233\"} \u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u00000^\u000b\u000f\u0000p\u0000\u0000\u0000_\u000b\u000f\u0000p\u0000\u0000\nhello\u0000\u0000\u0000\u0000\u0000\u0000","runtime":"go"}
`

## Your Environment
- Nakama: v2.11.1 
- Database: 
- Environment name and version: golang v1.14.1
- Operating System and version: darwin/amd64

## error
`
[libprotobuf ERROR ../../../../third_party/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:626] String field 'nakama.api.Rpc.payload' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
`

**Comment by novabyte** [comment]
@dongshimou This looks like a bug in the CPP client rather than the server. @Dimon4eg Could you take a look?

**Comment by Dimon4eg** [comment]
@novabyte I've tested that string with local 2.11.1 server and with `clientrpc` lua module:
```cpp
auto jstr = R"( {"abdefawdc":"233"} )";
rtClient->rpc("clientrpc.rpc", jstr, successCallback);
```

It works fine.
Could you please try to reproduce on go module?

@dongshimou that log from server or client?
What client version do you use?

**Comment by dongshimou** [comment]
@Dimon4eg 

client log:
`[libprotobuf ERROR ../../../../third_party/grpc/third_party/protobuf/src/google/protobuf/wire_format_lite.cc:626] String field 'nakama.api.Rpc.payload' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.`

client version: https://github.com/heroiclabs/nakama-cpp/releases/download/v2.3.0/nakama-cpp-sdk_2.3.0_mac.7z

client code :
```
auto jstr=R"( {"abdefawdc":"233"} )";
m_realtime_client->rpc("hello",jstr, [&](const Nakama::NRpc &rpc) {
                Nakama::NLogger::Debug(rpc.payload, "hello-callback");
            });
```

**Comment by dongshimou** [comment]
server code : golang
```
func Hello(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, payload string) (string, error) {
	logger.Info("call hello : %s", payload)
//other code
}
```

server version:  v2.11.1

server log: 
i got the abnormal result.
`{"level":"info","ts":"2020-04-03T11:15:14.251+0800","msg":"call hello : awdc\":\"233\"} \u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000\u00000^\u000b\u000f\u0000p\u0000\u0000\u0000_\u000b\u000f\u0000p\u0000\u0000\nhello\u0000\u0000\u0000\u0000\u0000\u0000","runtime":"go"}`

it should be : 
`{"level":"info","ts":"2020-04-03T11:15:14.251+0800","msg":"call hello : \"abdefawdc \":\"233\"}","runtime":"go"}`

**Comment by zhaoshichen1** [comment]
@Dimon4eg Hi Boss, could you take a look at this problem? It seems like C++ client issue

**Comment by dongshimou** [comment]
@novabyte hi, do you have any suggestion?

**Comment by Dimon4eg** [comment]
@dongshimou Tested your go rpc with server 2.11.1 and latest C++ client from Windows 10 and Mac 10.15.4
Cannot reproduce.
Logs:
```
[NWebsocketCppRest::NWebsocketCppRest]
[NRtClient::NRtClient] Created
[NRtClient::connect] ...
[NWebsocketCppRest::connect] ...
[NRtClient::operator ()] connected
[NWebsocketCppRest::operator ()] socket message received 176 bytes
Joined User ID: d4fbd0c5-b455-4c03-84d8-cfe6046f17a6 Username: OnLZqtMGtG Status:
[Nakama::RestClient::rpc] ...
rpc response:  {"abdefawdc":"233"}
[NRtClient::rpc] ...
[NWebsocketCppRest::send] sending 73 bytes text ...
[NWebsocketCppRest::operator ()] socket message received 73 bytes
rpc response:  {"abdefawdc":"233"}
```

**Comment by novabyte** [comment]
@Dimon4eg and I have tried to reproduce your issue with these 3 different RPC functions:

```go
func execRpc(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, payload string) (string, error) {
	logger.Debug("execRpc received: %v", payload)
	return payload, nil
}

func execRpcNil(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, payload string) (string, error) {
	logger.Debug("execRpc received: %v", payload)
	return "", nil
}

func execRpcErr(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, payload string) (string, error) {
	logger.Debug("execRpc received: %v", payload)
	return "", runtime.NewError("threw an error", 3)
}
```

It all works as expected. I suspect the problem is somewhere else in your Go code.
