### ISSUE TITLE
Disable various subsystems via resource limits.

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#42]
This has been requested via the community. The initial goal is to be able to disable login/registration by game clients.

A larger internal goal is to be able to "Turn off" various subsystems like chat persistence or at least disable them in the socket pipeline so game clients cannot use those features. This can be useful for games which control more behaviour via our script runtime. Depends on https://github.com/heroiclabs/nakama/issues/5

**Comment by JoshuaStrunk** [comment]
I would argue this does not depend on your scripting runtime (#5). 

I envision a more likely scenario being a developer/team has an authoritative environment they are comfortable in and they need to handle some orchestration from it. Basically a way of allowing things to be server/admin API controlled. For things like login/registration allow for a configured secret server/admin key. For anything that is handled through a real-time client connection you could allow for superuser/ admin client connections which can act as though they are any user. Updating data, creating group, games, etc... 

Forgive me if this seems silly, have only really been diving into APIs and still need time to actually experiment and test out Nakama to fully understand what is there.

**Comment by mofirouz** [comment]
There is also a requirement for some games (e.g. Poker) where a user cannot be logged in multiple times. #132

**Comment by novabyte** [comment]
This can be achieved with simple server runtime code now. For example:

```go
// Place code inside InitModule
messageIDs := []string{"ChannelJoin", "ChannelLeave", "ChannelMessageSend", "ChannelMessageUpdate", "ChannelMessageRemove", "MatchCreate", "MatchmakerAdd", "MatchmakerRemove", "StatusFollow", "StatusUnfollow", "StatusUpdate"}
rtBeforeDisableMessage := func(ctx context.Context, logger *log.Logger, db *sql.DB, nk runtime.NakamaModule, envelope *rtapi.Envelope) (*rtapi.Envelope, error) {
	return nil, errors.New("disallowed")
}
for _, id := range messageIDs {
	if err := initializer.RegisterBeforeRt(id, rtBeforeDisableMessage); err != nil {
		return err
	}
}
```

That code example will disable most realtime messages in the socket pipeline. There's equivalent functions to disable features in the API although these are easier to disable with a load balancer in front of the game server as normal.

It's also possible to disable a user from concurrent play sessions with our streams API. 🏆
