### ISSUE TITLE
is Leaderboard support filter by Country

### ISSUE THREAD

**Issue by takaaptech** [heroiclabs/nakama#420]
Hi!
I am a newbie and After reading the document about the Nakama server and Leaderboard session I still can not find how to filter user by country.
For example, I want to have a leaderboard for all user and each user has a leaderboard in his/her country.
Thank so much!

**Comment by mofirouz** [comment]
Please use the forum for asking general questions. Issue tracker is used to report bugs within Nakama. 

In your case, the question was asked previously on the forums and the answer is here:
https://forum.heroiclabs.com/t/nakama-leaderboard-filter-by-region/284
