### ISSUE TITLE
Consider adding Link* to runtime_go_nakama.go/runtime_lua_nakama.go

### ISSUE THREAD

**Issue by leoncarl** [heroiclabs/nakama#422]
## Description
It would be nice to be able to call into:

- LinkCustom
- LinkDevice
- LinkEmail
- LinkFacebook
- LinkFacebookInstantGame
- LinkGameCenter
- LinkGoogle
- LinkSteam

From Before/After plugin hooks much like you can do with Authenticate*

**Comment by zyro** [comment]
Added in 103beb4af7919ad3055d0eae3993c1d1a8c354fb and will be part of the next release.
