### ISSUE TITLE
Consider adding GetMatch to runtime

### ISSUE THREAD

**Issue by leoncarl** [heroiclabs/nakama#423]
## Description
Consider allowing runtime access to the `MatchRegistry` `GetMatch` much like `ListMatches` is exposed as this will allow plugins to fetch Matches by ID (if known) instead of doing a search via ListMatches for a known label or iterating through ALL matches to find the one with the known ID.

**Comment by zyro** [comment]
Added in 8deab9e756cbdacb9b2eeed3c6cb0555520c2d52 and will be part of the next release.
