### ISSUE TITLE
How do we send message in match reliable and unrelible?

### ISSUE THREAD

**Issue by ahoogol** [heroiclabs/nakama#425]
How do we send message in match reliable and unrelible?
I found this:
_socket.SendMatchStateAsync
But it has not a parameter to say it to send over UDP(unreliable) or TCP(reliable)!
Some messages is suited to be sent unreliable, for example positions for characters change frequently.

**Comment by mofirouz** [comment]
This is not an issue in Nakama. GitHub issues are only used for tracking bugs. If you have development questions, please ask them on the forum:

https://forum.heroiclabs.com
