### ISSUE TITLE
nk.tournament_record_write updates UpdateTime even if no change

### ISSUE THREAD

**Issue by ooochris** [heroiclabs/nakama#428]
## Description
when I call "nk.tournament_record_write" on a tournament that as Best as score operator, the score and number of attempts is not updated if it's not a best score(good!) but the updateTime of that player record is updated. It's a bit annoying to check who got first to a certain score.

## Steps to Reproduce
1. Create a tournament with score operator best.
2. add a score for player x
3.  call nk.tournament_record_write for player x with a smaller score than in step 2

## Expected Result
the ranking record should stay untouched

## Actual Result
the update time has been changed

**Comment by zyro** [comment]
Changed in f94236cb0098ca55a7539c3bffb66c09fc5b802f and will be part of the next release.
