### ISSUE TITLE
Expose disable time for an account/accounts

### ISSUE THREAD

**Issue by ciroduran-at-zynga** [heroiclabs/nakama#429]
Hi, I'm using Nakama 2.9.1, and I'm looking at the ban/unban functionality. Specifically, I'm looking on how to get the ban status. Banning and unbanning seems pretty much straightforward, and can be called from the runtime. But the disable time doesn't seem to be exposed on the api, which is useful for a external tool to determine whether to show the right ban/unban action for an account.

`GetAccount` in `core_account.go` returns the time as the second parameter, after and outside of the user account. But the runtime module ignores this information

```func (n *RuntimeGoNakamaModule) AccountGetId(ctx context.Context, userID string) (*api.Account, error) {
	u, err := uuid.FromString(userID)
	if err != nil {
		return nil, errors.New("invalid user id")
	}

	acc, _, err := GetAccount(ctx, n.logger, n.db, n.tracker, u)
	return acc, err
}```

It seems that `GetAccount` is not directly accessible. I would understand that exposing the disable time to customers is not advisable, it makes sense not to show them information about that. I was hoping to display the ban status in our admin tool, but it seems that I'm only able to ban/unban the user, without being able to check out whether they're effectively banned or not

Would it be possible to expose the disable time in the runtime? It could be a separate call not available to logged in users.

**Comment by zyro** [comment]
Added in c90c13c90ea731a646c990fc96f017245a423cdd and will be part of the next release.
