### ISSUE TITLE
Negative matches count in the Developer console

### ISSUE THREAD

**Issue by rrenderr** [heroiclabs/nakama#430]
## Description
We had a load test session. After stoping all load bots we have negative matches count in the Developer console.

## Actual Result
```
Status responce:
{"nodes":[{"name":"nakama-0","match_count":-2,"goroutine_count":82,"avg_latency_ms":89.76673211055822,"avg_rate_sec":0.40743243243243243,"avg_input_kbs":0.025665338189752248,"avg_output_kbs":0.05015447576482733},{"name":"nakama-1","match_count":-5,"goroutine_count":78,"avg_latency_ms":87.4634154085484,"avg_rate_sec":0.4177827380952381,"avg_input_kbs":0.026063755580357117,"avg_output_kbs":0.05087207612537209}]}
```
<img width="1283" alt="screen" src="https://user-images.githubusercontent.com/18209996/82658070-1486dc80-9c2f-11ea-9248-b3aee2f0f1a4.png">

## Your Environment
- Nakama: 2.10.0
- Environment name and version: QA

**Comment by zyro** [comment]
Fixed in d093d0564a0baca4f45bba49622a87666ef886c1 and will be part of the next release.
