### ISSUE TITLE
Error in log: duplicate key value violates unique constraint \"user_device_pkey\"

### ISSUE THREAD

**Issue by ooochris** [heroiclabs/nakama#434]
I get quite a few of those errors in our logs.

Talked with Chris that this error could be put on a Debug level or silenced somehow.

Thanks

**Comment by novabyte** [comment]
Thanks @ooochris. We should eliminate these log lines or make them DEBUG level. They're a misnomer. Not an error at all just a constraint check on the database row.

**Comment by novabyte** [comment]
This is resolved in https://github.com/heroiclabs/nakama/commit/8929782f7d8099d320a7793addddf1257421901c and was part of the 2.15.0 release.
