### ISSUE TITLE
3box.io decentralized account integration

### ISSUE THREAD

**Issue by DreadKnight** [heroiclabs/nakama#436]
I think it will be awesome if Nakama would work out of the box with this decentralized Ethereum based user registration system, which can even store private data. It's awesome stuff for the next gen dapps, as you don't bother with hosting the user data yourself anymore, which can relieve quite a bit of stress.

https://3box.io
https://3box.io/hub
https://3box.io/products/profiles
https://3box.io/products/storage
Easy to deal with and there's even good documentation (implements with JavaScript).

Here's mine as an example, it even shows some [Kudos](https://gitcoin.co/kudos) that I have
https://3box.io/0x21f53db4d2eacde70a2e4f0407d073c971ec1a33

You can read more about dapps here:
https://ethereum.org/dapps
https://blockgeeks.com/guides/dapps
https://en.wikipedia.org/wiki/Decentralized_application

**Comment by novabyte** [comment]
@DreadKnight I had a look at the 3box API and I don't see a need to add official support for 3box. It's also really unclear how large the interest in support for it is right now. It looks to me like it could be added to your game as a custom authentication based account provider via a before hook.
