### ISSUE TITLE
Proposal to use basic auth in headers instead of body for console API

### ISSUE THREAD

**Issue by lugehorsam** [heroiclabs/nakama#440]
The C# client code generator produces incorrect code from the console API because it doesn't know how to generate a method for the `/v2/console/authenticate` operation.

This happens because the operation in the `console.swagger.json` omits `BasicAuth` as a security option and opts to authenticate via a body param in lieu of the headers.

https://github.com/heroiclabs/nakama/blob/master/console/console.swagger.json#L737

The following would make the client generate a successful method:

(1) Remove the `consoleAuthenticateRequest` parameter.
(2) Use `BasicAuth` as the security option. 

Of course, the client code generator could be modified to accommodate this, but frankly it would make the code a lot more brittle. If this is something that is not a big deal to do on the backend, that would be better. But always up for thinking about alternatives.

**Comment by novabyte** [comment]
@lugehorsam I think this is a good move especially if it standardizes out the differences when we utilize our codegen tools. I think we go for it but must make the console UI changes to accommodate it too.

**Comment by lugehorsam** [comment]
Great, I can do it next week.
