### ISSUE TITLE
Password update in Devconsole doesn't update without another field also updated.

### ISSUE THREAD

**Issue by TheDevTom** [heroiclabs/nakama#443]
## Description
When using the console API to update the password, you have to send an additional field along with the new password in the body in order for it to update, this can't be UserId either, providing any other field seems to work fine. 

## Expected Result
Update the password

## Actual Result
Doesn't update the password

## Context

WebAPI 

## Your Environment

- Nakama: 2.11.1+5a218d6a
- Database: Cockroach DB

**Comment by zyro** [comment]
Fixed in cdd5cc18847ffd8a26a0e07ecd1035edd30f00c3 and will be part of the next release.
