### ISSUE TITLE
Suggestion: Create officer level in groups

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama#45]
Currently Admin is the only promotion one could get but that creates issues with the owner as they get the same privileges as him. The owner should be the only one able to delete the group and assign a new owner.

**Comment by mofirouz** [comment]
@ArisTsevrenis For what it's worth - Groups have a specific field called owner ID and that can never change. However one admin could remove other admins (incl the owner which is treated as an admin).

Could you walk me through the use case you have and why removing the original admin is problematic?

**Comment by ArisTsevrenis** [comment]
@mofirouz Sure thing, I had the same chat with @zyro yesterday as well. The problem is that if the owner has left, there's no way to know who the current owner is. Im not saying to remove the admin privilege but imagine it as 3 layers:
Owner: Can do what Admins can do + Delete Group + Assign Owner
Officer/Admin: Can do everything that admins do now apart from deleting groups
Member: Same as now

**Comment by zyro** [comment]
We've gone through this at standup and agreed it makes sense to have an explicit owner role.

**Admins** will lose the ability to delete groups, but retain all other privileges.

The **owner** will be unique and will have the ability to delete the group or transfer ownership to another member/admin. They will be prevented from leaving the group unless they transfer ownership first.

@ArisTsevrenis Does this cover your use case? Are there any other actions you'd restrict to owners only, perhaps renaming the group once #46 is in effect?

**Comment by ArisTsevrenis** [comment]
It does! I think just by the fact that you create the owner as an entity it will be available to programmers to put together in their end logic whether they'd allow admins to change the name of the group or otherwise and with that you keep your generic architecture as well. win-win.

**Comment by JoshuaStrunk** [comment]
The ability for Admins/Owners to demote others back down to Member and Owners to remove other Owners would also be handy. Just for generic architecture sake. Then can be up to developers to add checks on if the demotions should be allowed. Better than having to do custom logic of remove user then re-add user to get demotion logic if it was not supported in base architecture.

**Comment by novabyte** [comment]
This was added in 4ab4a0a162b7a6887bf6099b4612ce685537f735.
