### ISSUE TITLE
[Unity SDK] output from MatchJoinAttemp isn't right

### ISSUE THREAD

**Issue by androuinremi** [heroiclabs/nakama#453]
Issue created from this post : https://forum.heroiclabs.com/t/authoritative-join-attempt-question/926

Using golang, I’ve created my own match class. When a player try to join the match I’m using the function MatchJoinAttempt. to decide if he can or not
When I’m rejecting a join attempt, I want to reply the reason to the player. So as the documentation says, I’m returning the reason as a string. The problem is, I don’t know how to retrieve this string from the client side. Because I reject the join attempt, the function is throwing an exception. And the exception message is always (Match join rejected).

**Comment by mofirouz** [comment]
Please create this in the correct respective client repo:

https://github.com/heroiclabs/nakama-unity
