### ISSUE TITLE
Correct way of using nk.storage_write ?

### ISSUE THREAD

**Issue by skitsanos** [heroiclabs/nakama#454]
I've been through the docs and can't figure out something here.  I'm trying to write an object,  but I can't see there is no record getting created. Am I missing something?

```lua
local doc = {title='test'}
nk.storage_write({ collection = "app_store", key = "content", user_id = nil, value = doc })
```

## Environment
- Nakama: 2.12.0+650b506a
- Database: CCL v20.1.4 @ 2020/07/29 22:51:52 (go1.13.9)
- Operating System and version: MacOS 10.15.6

**Comment by mofirouz** [comment]
You aren't setting the correct permissions on this object. See: https://heroiclabs.com/docs/storage-access-controls/#object-permissions

Most importantly, GitHub Issues are only used for actual server issues/improvements. If you have questions please use the forum:

https://forum.heroiclabs.com

**Comment by novabyte** [comment]
@skitsanos The API is batch orientated. You can see an example on the function reference:

https://heroiclabs.com/docs/runtime-code-function-reference/#storage

In your specific example you should update it to look like:

```lua
local doc = {title='test'}
nk.storage_write({
    { collection = "app_store", key = "content", user_id = nil, value = doc }
})
```

As @mofirouz mentioned it'd be best to ask these kinds of questions on the forums. Thanks 🙏
