### ISSUE TITLE
Group names aren't unique

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama#46]
I have tried and created the same group twice with the same exact data, this is very confusing as there's no way for users to know each and all different groups.

**Comment by novabyte** [comment]
@ArisTsevrenis We spoke about this request on standup today and have agreed it makes sense to change the default server behaviour to require unique group names rather than just group id determine uniqueness. We'll make this change as part of the 0.12.0 release of the server.

**Comment by zyro** [comment]
Agreed, User IDs and handles are a good precedent for that and exist for the same reasons. I think that pattern makes sense for Group IDs and names as well.

**Comment by novabyte** [comment]
Added in https://github.com/heroiclabs/nakama/commit/a3f6988b264fb6f6c8ebb6ef7d998bc9469a2133.

@ArisTsevrenis You will have to wipe your database and reapply the migrations for this to take effect. You should run `nakama migrate redo` with the newest Nakama release which will be out shortly.
