### ISSUE TITLE
Add a config flag which toggles more detailed logging for authentication failure

### ISSUE THREAD

**Issue by twalters-zyn** [heroiclabs/nakama#464]
https://github.com/heroiclabs/nakama/blob/3ffe2a4b10bddc1895c8d25f08ce7d96dca2835a/server/core_authenticate.go#L131

Currently, the server does not clearly report to the client that the account has been disabled. Although this is done intentionally, it may be worth adding an option to change this

**Comment by novabyte** [comment]
@twalters-zyn We had an internal discussion and decided that the original obscurity goal with the response code returned when a player was banned did not outweigh the convenience to be able to check for it within game client code. We've updated the default to use a permission denied status code. It's a backwards compatible change. This resolves your requirement and is part of the latest server release (2.14.0).
