### ISSUE TITLE
[Feature] Add runtime equivalent to LeaderboardRecordsList for tournaments

### ISSUE THREAD

**Issue by LionJerry** [heroiclabs/nakama#470]
Seems to be only missing on the runtime as the client has this api

https://forum.heroiclabs.com/t/leaderboardrecordslist-for-tournaments/1045

**Comment by sesposito** [comment]
@LionJerry apologies for the late reply on this, you can currently list tournament records by passing in a tournament id to the `LeaderboardRecordsList` function. 

We'll still be adding a separate function for tournaments to make the API more consistent.
