### ISSUE TITLE
[Feature] Request to add support for bitwise operations in Lua

### ISSUE THREAD

**Issue by ParallxStudio** [heroiclabs/nakama#474]
Add support for LUA bitwise operations (set bit, read bit , shift right/left ...

**Comment by novabyte** [comment]
@ParallxStudio I suggested you open this issue based on our discussion on the forums but had forgotten we already have full support for the backport of bitwise operations into the Lua VM:

https://github.com/heroiclabs/nakama/blob/master/server/runtime_lua_bit32.go

You can see the documentation on how these functions work from the `"bit32"` module in the Lua manual:

https://www.lua.org/manual/5.2/manual.html#6.7

I think this solves the issue but let me know if it doesn't cover your use case.
