### ISSUE TITLE
How to support Chinese?

### ISSUE THREAD

**Issue by LinXunxi** [heroiclabs/nakama#478]
## Description
How to support Chinese?

## Steps to Reproduce

1. Register a new user
2. Connect to server socket
3. Send message to fetch current user's friends
4. Receive a message

## Expected Result
displays "???" when the message received is have Chinese.

## Context
//Callback
OnChannelMessageCallbackEvent(const NChannelMessage& message)
{
FString JsonValue = FString(message.content.c_str());
// JsonValue displays "???" when the message received is have Chinese.
}

-  Unreal C++ 

## Your Environment
- Nakama: 2.12.0
- Database: v19.2.5
-Unreal : 4.25.3

**Comment by novabyte** [comment]
@LinXunxi I don't think this is an issue with the server but could be a problem with how UTF-8 is handled in the Unreal C++ client. I'll leave this open but will also open an issue to track the problem on the client SDK.

**Comment by LinXunxi** [comment]
> @LinXunxi I don't think this is an issue with the server but could be a problem with how UTF-8 is handled in the Unreal C++ client. I'll leave this open but will also open an issue to track the problem on the client SDK.

So do I have to change the message encoding to UTF-8?

**Comment by LinXunxi** [comment]
> @LinXunxi I don't think this is an issue with the server but could be a problem with how UTF-8 is handled in the Unreal C++ client. I'll leave this open but will also open an issue to track the problem on the client SDK.

ok, it can do, think.  

now code : 
Send:
RtClientPtr->writeChatMessage(TCHAR_TO_UTF8(*channel),TCHAR_TO_UTF8(*message).......);
Receive:
FString JsonValue = FString(UTF8_TO_TCHAR(message.content.c_str()));
