### ISSUE TITLE
[Feature Request] Return a future from functions C++

### ISSUE THREAD

**Issue by Bambofy** [heroiclabs/nakama#484]
## Description
Using the functions that run on another thread e.g. client->authenticateDevice() don't return any way to control their execution, please can you return a future from these functions so i can await them? Thanks!

**Comment by novabyte** [comment]
@Bambofy I think this issue is better opened as a feature request on the CPP client SDK. This repository is for the game server. - https://github.com/heroiclabs/nakama-cpp
