### ISSUE TITLE
Twitter Authentication 

### ISSUE THREAD

**Issue by Kc-io** [heroiclabs/nakama#487]
Need a twitter based Authentication, mostly Arabic clients wants to add twitter as a authentication.
Also there is a large number of users who don't use Facebook and active in twitter

Below is the link of reference
https://vipbaloot.com/play/#/home

**Comment by novabyte** [comment]
@Kc-io We've not had any game studios ask for this feature since this issue was opened. I think we can consider this again in the future if there's enough demand for Twitter authentication as a sign-in feature.

**Comment by ryanprice** [comment]
We are in the Web3 communities and would like to see Twitter authentication for Browser games with nakama server, perhaps there are others still interested in this.

**Comment by novabyte** [comment]
@ryanprice In your Web3 games you could create a custom authentication flow with our server framework feature that uses Twitter to authorize the player. - https://heroiclabs.com/docs/nakama/concepts/authentication/#custom
