### ISSUE TITLE
Facebook login - required fields

### ISSUE THREAD

**Issue by OtterBlitzStudio** [heroiclabs/nakama#488]
Hey,

I run into an issue with the `AuthenticateFacebookAsync`. 
After receiving the FB token the Server tries to do the request to fetch the user data. 
With this request it sends some extra fields.
I did not find any place where we need this information gender,locale,timezone.
https://github.com/heroiclabs/nakama/blob/4b92d9fb24cd281bf6de00e0c1d3ab82f22029ba/social/social.go#L198

The problem is that those fields are not active by default:
![FB_Fields](https://user-images.githubusercontent.com/74243222/98666969-10ba5400-234e-11eb-8462-4273865dd459.png)

I tried to create a new app and clicked on the "Develop a game or connect with one".
But those apps don't have the "gender,locale,timezone" fields set.
The workaround was to create a "Develop linked functions"-App.
![CreateApp](https://user-images.githubusercontent.com/74243222/98667612-e917bb80-234e-11eb-81e9-a08b8d007b02.png)

To avoid such an error in the future could you remove the fields if they are not required or could you add some extra information to the documentation about the FB authentication? 

Thank you

**Comment by novabyte** [comment]
@OtterBlitzStudio Thanks for the detailed report. I think we should just remove those fields from the request we send to fetch the user profile with Facebook. I think there's probably been an API change in the Facebook graph which makes it problematic to request those fields. Do you want to open a pull request? 😄

**Comment by OtterBlitzStudio** [comment]
I could do it, but:

1. I haven't cloned the repo until now. It should not be so hard, but I'm not a go developer ^.^

2. Maybe there could be some side effects. I guess the complete line could be deleted and then the documentation needs some changes:
var perms = new List<string>(){"public_profile", "email"}; (https://heroiclabs.com/docs/authentication/#facebook) 

To test all of this requires some time, so I think it should be faster if you do it by yourself. 
Otherwise, I could check it at the weekend. :P

**Comment by zyro** [comment]
Fixed in https://github.com/heroiclabs/nakama/commit/dd51571d2194529fef2eb9355732dacf7d6eac7e and will be part of the next release.
