### ISSUE TITLE
Performance of rUDP vs ENet?

### ISSUE THREAD

**Issue by ylluminate** [heroiclabs/nakama#496]
I've seen some negative sentiment and remarks about rUDP over the years, which has surprised me since it seems to be a solid performant option with a nice Plan 9 implementation model / example.  Have you tested it against [ENet](http://enet.bespin.org/Features.html) and, if so, what advantages / disadvantages have you seen or believe may exist?

**Comment by novabyte** [comment]
@ylluminate This is a huge discussion and would be great to talk through but isn't a good fit for an issue tracker. I think open a thread on the [forums](https://forum.heroiclabs.com/). Thanks 🙏

**Comment by ylluminate** [comment]
@novabyte 	thanks so much for pointing me over there - posted this there and waiting for moderation. 👍🏻
