### ISSUE TITLE
Add background jobs and event signals to script runtime.

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#5]
An embedded script runtime capable of background jobs and socket message handlers. Used to power custom game logic and server-authoritative code.

**Comment by novabyte** [comment]
## Design update

The capabilities of the script runtime are broken down into 5 major components:

- __Before/After message hooks__

**Comment by brinca** [comment]
So while the scripting runtime is being developed, the only option to control the server authoritatively is to have like a "control panel" app (either outside the game or hidden within) that monitors the server and issues commands (messages) when appropriate, right?

If that is the case, is there some sort of super user that can be used to have access and manipulate all other users data?

**Comment by zyro** [comment]
@brinca Until the script runtime is available you can control data directly through the DB, just make sure to observe the constraints of the game server. What kind of behaviour do you want to control/enforce authoritatively right now?

**Comment by brinca** [comment]
Well, for now we need to:
1. Store common configuration data (minimum version number to force an update, game stats tweakable by the game designers, etc), that is supposed to be pulled by each user when a game session is started
2. Create common challenges (public events where any player can participate), spawned from time to time, with different characteristics (sorted by a server script)
3. Manage player wallet and calculate rewards (should definitely not be done on the client... ;))

Although not a priority for now, to make it harder to eavesdrop/tamper with the communication it would be great to be able to implement our own encryption system (e.g. messages payload would be encrypted on the client, using a temporary shared key, and then decrypted on the server through a custom script, before being reinjected into the normal Nakama flow).

BTW, I think the database is hosted in HeroicLabs' cloud, so I don't know if we have direct access to it...

One last thing.. Lua is nice but JavaScript would be nicer... ;)

**Comment by novabyte** [comment]
Thanks for your thoughts @brinca 😄 

> Store common configuration data

This can be achieved in the meantime (before we launch the script runtime) with a SQL script which inserts the configuration data. A quick example is:

```sql
INSERT INTO storage (id, bucket, collection, record, value, version, read, write, created_at, updated_at)
VALUES (uuid_v4(), 'my_bucket', 'my_collection', 'my_record', b'{"value":"here"}', uuid_v4(), 1, 0, 1492802366746, 1492802366746)
```

The `read` and `write` columns in the storage table indicate access permissions on records.

> Create common challenges (public events where any player can participate), spawned from time to time, with different characteristics (sorted by a server script)

This will definitely need the script runtime for easy support although you could use a cron script to write records into the storage table for clients to read.

> Manage player wallet and calculate rewards (should definitely not be done on the client... ;))

The will definitely require **direct invocation** or **before hooks** in the script runtime to achieve. I completely agree it needs to be handled authoritatively especially with external services which offer webhooks for reward callbacks (within some Ad networks).

> Although not a priority for now, to make it harder to eavesdrop/tamper with the communication it would be great to be able to implement our own encryption system

This will be possible with AES encryption functions which can be called on payloads received via direct script invocation. You can use this approach to encrypt client/server payloads for specific custom game logic requirements.

> BTW, I think the database is hosted in HeroicLabs' cloud, so I don't know if we have direct access to it...

We do have a managed cloud in development but it is not available yet. It's timed to launch next month. We don't have a hosted database solution right now. You run Nakama server with the database engine (cockroachdb) on whatever server environment or cloud provider you prefer.

> One last thing.. Lua is nice but JavaScript would be nicer... ;)

We have a lot of experience with Lua and prefer the built-in coroutine model over JavaScript's answer to concurrency. We'll put together guides which will help developers who prefer JavaScript to quickly switch over to Lua code for their game projects. Lua has a great history of success and performance in the games industry. 😄

**Comment by novabyte** [comment]
The first phase of this work is completed in https://github.com/heroiclabs/nakama/commit/c7221f8c609ade175808f70f7333ce548c4adf56 as part of the 0.13.0 release. You'll need the latest Unity client (0.6.0) or greater.

We've implemented **before/after** message hooks, **rpc** (direct invocation), and **http** (new feature) server functions with the Lua runtime.

**Comment by novabyte** [comment]
The 2.1.0 release covers all we need to add for this functionality now. Event hooks for leaderboard resets and tournament resets is now implemented. The rest of the capabilities are covered in our authoritative multiplayer engine, direct RPC support, and before/after hooks.
