### ISSUE TITLE
[Feature] Expose socket.port to runtime code

### ISSUE THREAD

**Issue by mnarimani** [heroiclabs/nakama#501]
We have multiple instances of Nakama. One for production and multiple for development.

We use Nakama as Account Manager/Matchmaker. Nakama starts a Unity instance to handle game server logic.

Game server needs to know the player information, so it needs to connect back to the Nakama. But the problem is that it doesn't know which Nakama instance was responsible for launching it.

The solution is to pass the Nakama port as an argument when launching the Unity Game Server. But Go runtime does not have access to specified port in configurations.

**Comment by novabyte** [comment]
@mnarimani As a workaround in the meantime you could place the server port into a runtime environment variable and extract it from the context object in the runtime:

```
nakama --socket.port 7350 --runtime.env "SERVER_PORT=7350" --logger.level DEBUG
```

**Comment by novabyte** [comment]
After more deliberation I think its easy enough to pass in the port parameter as an environment variable to the server that we don't need to mirror the server configuration into the server framework.
