### ISSUE TITLE
Use an error code to mark a storage operation which fails the OCC check

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#51]
This was requested by the community.

Right now it's difficult to use the optimistic concurrency support in our storage subsystem because errors are not reported back in an easily useable way. The error codes added in the 0.12.0 release should be extended to include support for OCC intents which fail.

**Comment by zyro** [comment]
The [0.13.0 release](https://github.com/heroiclabs/nakama/releases/tag/v0.13.0) has improved error reporting for storage operations rejected by OCC.
