### ISSUE TITLE
API Explorer sends requests twice

### ISSUE THREAD

**Issue by oae** [heroiclabs/nakama#529]
## Description

API Explorer sends requests twice

## Steps to Reproduce

1. log in to the admin dashboard
2. Navigate to API Explorer
3. Send a request to any endpoint
4. Check browser network log or server log

## Expected Result

No double request is sent

## Actual Result

Everything is executed twice

## Context

![image](https://user-images.githubusercontent.com/1043714/105227317-33e55900-5b72-11eb-95b7-49de01170315.png)

![image](https://user-images.githubusercontent.com/1043714/105227637-99d1e080-5b72-11eb-9f90-308e13c81c9f.png)

## Your Environment

- Nakama: `heroiclabs/nakama:3.0.0`
- Database: `postgres:9.6-alpine`
- Environment name and version: `Docker version 20.10.2, build 2291f61`
- Operating System and version: `Windows 10 Pro Build 21292.1010`

**Comment by mofirouz** [comment]
Thanks. This is fixed in here: https://github.com/heroiclabs/nakama/commit/c8cbe4efa5219c9a1c8f119a6a2456ad33ccf744

Will be included in releases after 3.0.0z
