### ISSUE TITLE
AcceptInvite addFriend attempts results in NError RuntimeException returned.

### ISSUE THREAD

**Issue by JoshuaStrunk** [heroiclabs/nakama#53]
## Description

`NError(Code=RuntimeException,Message=Failed to add friend)` When doing a send AddFriendMessage against a user who is in state `FriendState.Invite`
## Steps to Reproduce

1. Get two users in an invited friend state
2. attempt to "accept" the invite from the invited user

## Expected Result
Invite to be accepted no RuntimeException returned to the client and both user to be in `FriendState.Friend`

## Actual Result

NError(Code=RuntimeException,Message=Failed to add friend)

[server-log](https://github.com/heroiclabs/nakama/files/862287/nakama-a4f7.txt)
[custom client logs](https://github.com/heroiclabs/nakama/files/862288/nakama-clientcustom.txt)

## Context

- [x] Unity
- [ ] Other

## Your Environment
- Nakama: 0.12.0+cc414be
- Cockroach: beta-20170309
- Environment name and version: AWS Lightsail 512 MB RAM, 1 vCPU, 20 GB SSD
- Operating System and version: Ubuntu 16.04.1 LTS

**Comment by zyro** [comment]
@JoshuaStrunk Thanks for the report, I can confirm there was an issue and I've opened #55 to address it.

**Comment by zyro** [comment]
This is fixed in 76ac761754fb5ab8fb4a69d6998845d8e9572bd4.
