### ISSUE TITLE
nk.MatchCreate 

### ISSUE THREAD

**Issue by louis030195** [heroiclabs/nakama#533]
## Description

Nakama fail to create match with nk.MatchCreate (Go).

The same code worked on 2.15.0.

## Steps to Reproduce

My authoritative code

```go
package main

import (
    "context"
    "database/sql"
    "github.com/heroiclabs/nakama-common/runtime"
    "github.com/louis030195/hivegum/internal"
)

const (
    CasualGame = "Casual"
)

func Register(initializer runtime.Initializer) error {
    createMatch := func(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule) (runtime.Match, error) {
        return &hivegum.Match{}, nil
    }
    if err := initializer.RegisterMatch(CasualGame, createMatch); err != nil {
        return err
    }
    if err := initializer.RegisterMatchmakerMatched(hivegum.MakeMatch); err != nil {
        return err
    }
    if err := initializer.RegisterAfterRt("MatchmakerAdd", hivegum.AfterMatchmakerAdd); err != nil {
        return err
    }
    if err := initializer.RegisterBeforeRt("MatchmakerAdd", hivegum.BeforeMatchmakerAdd); err != nil {
        return err
    }
    if err := initializer.RegisterAfterRt("MatchmakerRemove", hivegum.AfterMatchmakerRemove); err != nil {
        return err
    }
    if err := initializer.RegisterBeforeRt("MatchmakerRemove", hivegum.BeforeMatchmakerRemove); err != nil {
        return err
    }
    if err := initializer.RegisterBeforeRt("ChannelMessageSend", hivegum.BeforeChannelMessageSend); err != nil {
        return err
    }
    return nil
}

func InitModule(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, initializer runtime.Initializer) error {
    if err := Register(initializer); err != nil {
        return err
    }
    logger.Info("Registered hooks successfully")
    return nil
}
```

```go
func MakeMatch(ctx context.Context, logger runtime.Logger, db *sql.DB, nk runtime.NakamaModule, entries []runtime.MatchmakerEntry) (string, error) {
    for _, e := range entries {
        logger.Info("Matched user '%s' named '%s'", e.GetPresence().GetUserId(), e.GetPresence().GetUsername())
        for k, v := range e.GetProperties() {
            logger.Info("Matched on '%s' value '%v'", k, v)
        }
    }
    seed := time.Now().UnixNano()
    rand.Seed(seed)

    // Randomize the players
    rand.Shuffle(len(entries), func(i, j int) { entries[i], entries[j] = entries[j], entries[i] })

    // Pass params to Match
    params := map[string]interface{}{
        "seed":    seed,
        "players": entries,
    }
    // Create a Casual type game
    matchId, err := nk.MatchCreate(ctx, "Casual", params)
    if err != nil {
        logger.Error("Failed to create match: %v", err.Error())
        return "", err
    }

    return matchId, nil
}
```

## Expected Result

Create a match with success

## Actual Result

>{"level":"info","ts":"2021-01-23T18:06:17.724Z","caller":"main.go:172","msg":"Startup done"}
{"level":"info","ts":"2021-01-23T18:06:42.957Z","caller":"server/session_ws.go:80","msg":"New WebSocket session connected","uid":"46a00f3c-e4f6-4500-862a-8fcf74d8cdc6","sid":"bf8c716a-5da5-11eb-bd7b-b0c05538f87f","format":0}
{"level":"info","ts":"2021-01-23T18:06:43.475Z","caller":"server/runtime_go_logger.go:59","msg":"BeforeMatchmakerAdd","runtime":"go"}
{"level":"info","ts":"2021-01-23T18:06:43.476Z","caller":"server/runtime_go_logger.go:59","msg":"AfterMatchmakerAdd","runtime":"go"}
{"level":"info","ts":"2021-01-23T18:06:56.770Z","caller":"server/session_ws.go:80","msg":"New WebSocket session connected","uid":"f9b53ced-5ff0-47a7-b09e-44e6d412419b","sid":"c7c826ff-5da5-11eb-bd7b-b0c05538f87f","format":0}
{"level":"info","ts":"2021-01-23T18:06:57.521Z","caller":"server/runtime_go_logger.go:59","msg":"BeforeMatchmakerAdd","runtime":"go"}
{"level":"info","ts":"2021-01-23T18:06:57.523Z","caller":"server/runtime_go_logger.go:59","msg":"AfterMatchmakerAdd","runtime":"go"}
{"level":"info","ts":"2021-01-23T18:07:02.533Z","caller":"server/runtime_go_logger.go:59","msg":"Matched user '46a00f3c-e4f6-4500-862a-8fcf74d8cdc6' named 'yryr'","runtime":"go"}
{"level":"info","ts":"2021-01-23T18:07:02.533Z","caller":"server/runtime_go_logger.go:59","msg":"Matched user 'f9b53ced-5ff0-47a7-b09e-44e6d412419b' named 'ergger'","runtime":"go"}
{"level":"error","ts":"2021-01-23T18:07:02.685Z","caller":"server/runtime_go_logger.go:73","msg":"Failed to create match: error creating match: MatchInit returned invalid tick rate, must be between 1 and 60","runtime":"go","source":"github.com/louis030195/hivegum/internal/casual_match.go:86"}
{"level":"error","ts":"2021-01-23T18:07:02.685Z","caller":"server/matchmaker.go:375","msg":"Error running Matchmaker Matched hook.","error":"error creating match: MatchInit returned invalid tick rate, must be between 1 and 60"}

## Context
- [x] Unity
- [ ] Unreal
- [ ] Other

## Your Environment

- Nakama: 3.0.0
- Database: cockroachdb/cockroach:v20.2.4
- Environment name and version:
- Operating System and version: k3s, Deployment
>Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4+k3s1", GitCommit:"2532c10faad43e2b6e728fdcc01662dc13d37764", GitTreeState:"clean", BuildDate:"2020-11-18T22:11:18Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by zyro** [comment]
@louis030195 You've not shared what your match code looks like, but based on the error your Go match handler's `MatchInit` function returns a tick rate value outside the allowed `[1,60]` range. Can you check if that's the case?

**Comment by louis030195** [comment]
My bad it was indeed an error in MatchInit instead, thanks !
