### ISSUE TITLE
Feature Enhancement: Improve the reported logger caller location for plugins

### ISSUE THREAD

**Issue by joshgarnett** [heroiclabs/nakama#534]
Tested on Nakama 2.14.1

When using the runtime.Logger within a go plugin the caller location is reported as server/runtime_go_logger.go instead of the file and location within the go plugin itself.  

Example Code:
```
[game.go:48] nkLogger.Info("Testing log without context")
[game.go:49] nkLogger.WithField("foo", "bar").Info("Testing log with context")
```

Log output:

```
{"level":"info","ts":"2021-01-23T21:08:51.101Z","caller":"server/runtime_go_logger.go:59","msg":"Testing log without context","runtime":"go"}
{"level":"info","ts":"2021-01-23T21:08:51.101Z","caller":"server/runtime_go_logger.go:59","msg":"Testing log with context","runtime":"go","foo":"bar"}
```

In the above case, I would have expected it to set caller to game.go:48 and game.go:49.  

With accurate caller locations it will make it much easier for teams to debug issues that occur when testing or in production.  Thanks!

**Comment by zyro** [comment]
Changed in cac84a99616f216883ffce606479be043124422f and will be part of the next release.
