### ISSUE TITLE
Console failing to load resources when using Windows Binary

### ISSUE THREAD

**Issue by TheDevTom** [heroiclabs/nakama#535]
## Description
When using the Windows Binary the console fails to load, displaying a white screen and showing 404 errors when loading resources in the browser. 

This is a locally ran instance, not in docker reproduced on 3 machines upgraded from 2.15 to 3.0 and also clean installs.

## Steps to Reproduce

1. Replace the 2.15 Binary with 3.0
2. Start Server and migrate up
3. Navigate to console on :7351, redirects automatically to /ui and then displays a white page with 404 errors in console.

## Expected Result
To see console.

## Actual Result
404 errors.

## Context
Chrome, Firefox, Edge, all happens.

## Your Environment

- Nakama: 3.0
- Database:  CCL v20.2.2
- Operating System and version: Windows 10

**Comment by novabyte** [comment]
@TheDevTom This is solved in the [3.1.0 release](https://github.com/heroiclabs/nakama/releases/v3.1.0) of the server. Please re-open if the issue persists.
