### ISSUE TITLE
Custom group ID to perform group related features.

### ISSUE THREAD

**Issue by saychong** [heroiclabs/nakama#54]
I am using Parse server currently and have already generated a guild ID for all of my users.
I am wondering if its possible to use group related functions like, `JoinGroup` or `CreateGroup` with my own Parse generated guild ID.

**Comment by zyro** [comment]
@saychong Nakama's schema needs to use predictable, immutable IDs to reference groups but we've enabled group lookups by name as of 76ac761754fb5ab8fb4a69d6998845d8e9572bd4.

Starting next release you'll be able to achieve what you need through:
1. Set the group name to your generated value when each group is created in Nakama.
2. Users looking to join can then use group fetch by name to find the right group. This will give them the group ID to use in further operations.
3. Once they're a member all group operations work as expected.

Does this cover your use case?

**Comment by saychong** [comment]
Yes it will work. Thanks for the quick update.
