### ISSUE TITLE
positive detection on VirusTotal

### ISSUE THREAD

**Issue by Wafflily** [heroiclabs/nakama#547]
https://www.virustotal.com/gui/file/a9935e0de20d6f3576c2548efcb826e64977f532a5a70f911eab2995dead335d/detection

**Comment by novabyte** [comment]
@Wafflily I think it's obvious that this is a false positive from that antivirus tool. You can see from the codebase that we bundle JavaScript as part of the Console UI into the server binary. It's all clear and transparent in our code on GitHub.

I suggest you report the false positive to VirusTotal.

**Comment by Wafflily** [comment]
Nano confirmed it's a false positive and assured they corrected their detection. The last build does not trigger detection.
