### ISSUE TITLE
`console.max_message_size_bytes` does not work in Nakama Console 3

### ISSUE THREAD

**Issue by mnarimani** [heroiclabs/nakama#559]
When large amount of data is stored in storage, you cannot navigate to Storage menu in Nakama Console. You'll get this error:
`grpc: received message larger than max (4439891 vs. 4194304)`

The solution is to increase `console.max_message_size_bytes` in configuration file but it does not work. Storage menu will fail with the same error regardless of the value that you put in `console.max_message_size_bytes`.

**Comment by zyro** [comment]
Fixed in 54aedd5159e9f7b370ba2592eaf9abf713ebd48e and will be part of the next release.
