### ISSUE TITLE
Unable to Unlink facebook account

### ISSUE THREAD

**Issue by ldhongen1990** [heroiclabs/nakama#56]
Error is predicted to be located at the Unlink validation code.

## Description
Unity received INError from server when attempting to Unlink facebook:
Could not unlink facebook: 'Check profile exists and is not last link'.

This ALSO occurs when trying to unlink Email.
Unlinking CustomID works however.

## Steps to Reproduce
1. Register a new user using CustomID (NAuthenticateMessage.Custom) with nakama
2. Login
3. Connect
4. Now link facebook
5. Now unlink facebook <-- unable to unlink

## Expected Result
1. No error, server should reply with facebook successfully unlinked.

## Actual Result
Server responded with Error message 'Check profile exists and is not last link'

## Context
- [X] Unity 5.5.1p2, Nakama Client UnityPackage v0.5.0

## Your Environment
- Nakama: 0.12.0+cc414be

- Cockroach:
Build Tag:    beta-20170309
Build Time:   2017/03/16 07:25:18
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8
C Compiler:   4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)
Build SHA-1:  dd3a574da6734faebf523d7cc2df244ab662527d
Build Type:   development

- Environment name and version: Docker 17.03.0-ce-mac2 (15654)
- Operating System and version: OSX El Capitan 10.11.3

**Comment by zyro** [comment]
@ldhongen1990 Thanks for the report, this is now fixed in 76ac761754fb5ab8fb4a69d6998845d8e9572bd4.
