### ISSUE TITLE
Subscribing to a server shutdown event from a plugin

### ISSUE THREAD

**Issue by rgngl** [heroiclabs/nakama#573]
## Description
Currently, we are launching a gRPC server from a nakama plugin to listen to some events from another service we have. I've been reading the documentation and the nakama source code, but it seems there's no way to subscribe to such event. 

It would be very useful for us to detect, so we can gracefully shutdown the grpc server we have running.

**Comment by aidandon** [comment]
+1 for this. I'm looking to clean up/flush some resources in the module/plugin when shutting down. thx

**Comment by zyro** [comment]
This is now achievable via the `context.Context` passed to the module's `InitModule` function. The server will cancel this context as part of the shutdown process. Monitor that context for cancellation and cleanup any resources as needed. 👍
