### ISSUE TITLE
Is nakama really support cocos-js ??

### ISSUE THREAD

**Issue by jhyoo2** [heroiclabs/nakama#583]
Hello Admin.

First of all, I was really happy when I find your service, cause there is not much back-end sass service for cocos creator. 
So I decide to learn more about your service and I think I might be a huge fan of your service.

But!!

I found your example or cocos sdk which you support is totally incomplete.

**for example - email auth**

[your website example]
const email = "email@example.com";
const password = "3bc8f72e95a9";
client.authenticateEmail(email, password, true, "mycustomusername")
  .then(function(session) {
      cc.log("Authenticated successfully. User ID:", session.user_id);
    },
    function(error) {
      cc.error("authenticate failed:", JSON.stringify(error));
    });

this is example I see in your web-site. I try this example so many time, and everytime I get fail message, even nakama server is working very well.

And then I found this example is UNMATCH with cocos-sdk!

below is your sdk for supporting cocos. 

[actual function]
  Client.prototype.authenticateEmail = function (request) {
     **...**
      fetchOptions.headers = __assign({}, headers);
      fetchOptions.body = JSON.stringify({
         ** email: request.email,**
         ** password: request.password**
      });
      return Promise.race([
          fetch(this.configuration.basePath + urlPath + urlQuery, fetchOptions).then(function (response) {
              if (response.status >= 200 && response.status < 300) {
                  return response.json();
              }
              else {
                  throw response;
              }
          }),
          new Promise(function (_, reject) {
              return setTimeout(reject, _this.configuration.timeoutMs, "Request timed out.");
          }),
      ]).then(function (apiSession) {
          return Session.restore(apiSession.token || "");
      });
  };

To call e-mail auth function, In your website example, I thought all I should do is sending e-mail and password as parameter.
But actually I should send request object as a parameter which contains e-mail and password  as a variable.

=============================================================================

I know your service is pretty good and very organized sass service. But after I experience this, I so worried that every example in your web-site have same error like this. and I also I have afraid I encounter same error after I publish my game to the market.

So I request you to make your website example correctly or please update cocos sdk!

thank you very much.

the sdk now I'm using is here : https://github.com/heroiclabs/nakama-cocos2d-x-javascript/releases/tag/v2.0.0

**Comment by novabyte** [comment]
@jhyoo2 Thanks for the detailed email. You're right the code examples in the docs for the Cocos Creator compatible client are outdated. I've opened a documentation issue to track updates for it which you can follow [here](https://github.com/heroiclabs/nakama-docs/issues/197).

In the meantime you can also look at the JavaScript client code examples in the docs because the Cocos Creator compatible client is derived from that client SDK.

I will close this issue because its a documentation task and not an issue with the game server.

**Comment by lugehorsam** [comment]
Hey @jhyoo the issue actually wasn't the docs, it's that the cocos-2d-js v2.0 release was out of date. I released a new one today that should match what exists in the docs.
