### ISSUE TITLE
nkruntime.Nakama.usersGetId() createTime and updateTime not a number

### ISSUE THREAD

**Issue by Meneleus** [heroiclabs/nakama#584]
According to the `index.d.ts` the `User` structure's `createTime` and `updateTime` should be `number` but if I look at the JSON returned by `usersGetId` they are in a time format with `{"Seconds":number,"Nanos":number}`.

I have not tested other methods and time fields to see if it's consistently wrong/different.

Either the format needs to be updated so that we get the Seconds/Nanos fields or the JSON should only returns the seconds as a number.

**Comment by sesposito** [comment]
Thanks for opening the issue @Meneleus. Resolved in #585.
