### ISSUE TITLE
Request: Specify which user(s) in a match should receive the match data being sent

### ISSUE THREAD

**Issue by prodigga** [heroiclabs/nakama#59]
In most situations I've encountered, broadcasting MatchEventData to all connected users is good enough and does the job. However there are some instances where it would be good to be able to send data to a specific client or clients.

For example: a new client joins the match, the client asks an existing player for a history of the match so they can "catch up" and join the game. We could designate one of the existing players as the "master" who responds to these requests from incoming players, but the master has no choice but to broadcast the entire game history state to ALL clients, even though we only need to send this data to the client that has just joined the match. The other clients would just need to ignore the match history data being broadcasted by the master client, and that's just a waste of bandwidth/server resources.

There are lots of small examples like this where 2 clients need to exchange some data between each other, and the other clients have to know to ignore that that because it isn't really "targetted" at them.

I propose adding a Builder for NMatchDataSendMessage and adding a SetTargetClients method to the builder.

To broadcast to everyone, the API remains the same:
`var message = NMatchDataSendMessage.Default(matchId, opCode, data);`

To broadcast to specific clients, the API mimics the "buildeR" API used for topics etc:

`var message = NMatchDataSendMessage.Builder(matchId, opCode, data).SetTargetClients(listOfIDs).Build();`

**Comment by novabyte** [comment]
Thanks for the detailed breakdown of what you need. @zyro and I will discuss how to achieve it and make it part of the 0.13.0 release

**Comment by zyro** [comment]
This has landed on master in 46e50e1052123dcef13e8dcc3f657d8f99800e91.
