### ISSUE TITLE
Keycloak integration like other SSO

### ISSUE THREAD

**Issue by Allan-Nava** [heroiclabs/nakama#590]
Is interesting to integrate Keycloak https://www.keycloak.org/

**Comment by novabyte** [comment]
@Allan-Nava This is a duplicate of https://github.com/heroiclabs/nakama/issues/188 . I think we can continue to track demand for the feature request there.

**Comment by Allan-Nava** [comment]
> @Allan-Nava This is a duplicate of #188 . I think we can continue to track demand for the feature request there.

Ok sorry!
