### ISSUE TITLE
Nakama migrate problem using Cockroach Cloud Free Plan

### ISSUE THREAD

**Issue by raz0r007** [heroiclabs/nakama#602]
## Description
The command "nakama migrate up" doesn't work correctly when we want to use it in a Cockroach Cloud Free DB. The error that we get is: cannot access virtual schema in anonymous database.

If we use a local cockroach DB it works. It's only happening using a Cloud Free DB.

## Steps to Reproduce
1. Register/create an account in Cockroach Cloud Free Tier.
2. Execute the command "nakama migrate up ....." pointing to that Cloud DB.

## Expected Result
Nakama DB migrated correctly.

## Actual Result
We get an error: **cannot access virtual schema in anonymous database (SQLSTATE 42704)**

## Your Environment

- Nakama: 2.14.1 (It's happening in all versions)
- Operating System: Linux (Ubuntu)

**Comment by Andrea-Miele** [comment]
[Link of the help request on heroiclabs forum](https://forum.heroiclabs.com/t/database-hosted-on-cockroack-cloud-error-cannot-access-virtual-schema-in-anonymous-database-sqlstate-42704)

**Comment by Andrea-Miele** [comment]
There are two errors : sometimes "cannot access virtual schema in anonymous database (SQLSTATE 42704)", sometimes "EOF"

**Comment by Andrea-Miele** [comment]
[This is a manual solution](https://forum.heroiclabs.com/t/database-hosted-on-cockroack-cloud-error-cannot-access-virtual-schema-in-anonymous-database-sqlstate-42704/1556/15?u=andrea-miele)
