### ISSUE TITLE
ListLeaderboardRecordsAroundOwnerAsync does not return #1 rank if owner is #2

### ISSUE THREAD

**Issue by newatlanta19006** [heroiclabs/nakama#607]
## Description

When using call to get LeaderboardRecordsAroundOwnerAsync (in my case, from a .Net server), if I am the rank 2 owner it will not return rank 1 as a result as expected. 

## Steps to Reproduce
1. Create a leaderboard (in my case, descending with set operator)
2. Have an owner ranked 2 
3. Use the LeaderboardRecordsAroundOwnerAsync to retrieve leaderboard entries

## Expected Result
Rank 1 record should return (along with other records behind my rank)

## Actual Result
Retrieved only records behind my rank

## Context
.Net client (ASP .NETCore Server) version 2.7 client

## Your Environment
- Nakama: 3.2.1+6790d453
- Database: 19.1.5
- Environment name and version: AWS Ubuntu 18.04.5 LTS

Here is the current leaderboard status: 
![image](https://user-images.githubusercontent.com/721127/116747253-7957c480-a9b2-11eb-857c-61aef3d75b61.png)

Here is my code snippet:

var leaderboardRecordList = await client.ListLeaderboardRecordsAroundOwnerAsync(session, leaderboardId, ownerid, null, 20);

Here is the return with first 2 results expanded, as you can see, the first entry should be rank 1 but instead it returns my own entry and all ranks behind my entry.

![image](https://user-images.githubusercontent.com/721127/116747658-161a6200-a9b3-11eb-903b-18a121c504b3.png)

**Comment by DaveOak** [comment]
I believe this bug also causes the function to fail to return rank 1 when the owner ID is rank 1 (the list starts from rank 2 in this case), thereby omitting the owner from the list. This is only the case when the number of entries in the tournament exceeds the number of entries requested.

**Comment by zyro** [comment]
We're investigating a fix for this, keep an eye on https://github.com/heroiclabs/nakama/pull/605 for details.
