### ISSUE TITLE
[Feature Request] List Leaderboards

### ISSUE THREAD

**Issue by jasonwinterpixel** [heroiclabs/nakama#622]
Related discussion: https://forum.heroiclabs.com/t/retrieving-leaderboards-info-posible-somehow/398/5

Nakama should expose a list_leaderboards api.

Our usecase is that we would like our game clients to render information about when the next leaderboard reset will be. It is not simple to synchronize the 'cron formatted' reset schedule across clients and nakama deployments. Currently, there is no built in way to get the reset schedule for a leaderboard. There are many ways that this could be approached, but having an api to list the leaderboards is a good start (perhaps optionally taking a list of leaderboard IDs).

There is go code in that forum post for an RPC that would return the leaderboard info. This issue is about building that into Nakama itself.

**Comment by sesposito** [comment]
Resolved in #625
