### ISSUE TITLE
Regexp unicode classes not working inside JS runtime

### ISSUE THREAD

**Issue by pi-kei** [heroiclabs/nakama#629]
## Description

Regexp unicode classes not working inside JS runtime

## Steps to Reproduce

All of these lines return same string on any input (for example `abc ... абв !!!`):

```ts
const output = input.replace(/\P{L}/gu, '');
const output2 = input.replace(/\P{Letter}/gu, '');
const output3 = input.replace(/\PL/gu, '');
const output4 = input.replace(/\p{L}/gu, '');
const output5 = input.replace(/\p{Letter}/gu, '');
const output6 = input.replace(/\pL/gu, '');
```

## Expected Result

Regexp work as expected and found chars replaced.

## Actual Result

Nothing changed in resulting string.

## Context

JavaScript runtime

## Your Environment

- heroiclabs/nakama:3.3.0

**Comment by sesposito** [comment]
The Nakama js runtime support is powered by the https://github.com/dop251/goja/ library, if the regexes above do not work as they should, please consider opening an issue there.
