### ISSUE TITLE
Nakama integration with roku

### ISSUE THREAD

**Issue by Allan-Nava** [heroiclabs/nakama#631]

**Comment by novabyte** [comment]
@Allan-Nava can you give more description, present the issue as a feature request, and what the advantages of official Roku integration are?

**Comment by Allan-Nava** [comment]
You are right! 
https://developer.roku.com/en-ot/overview you can develop games on Roku

**Comment by Allan-Nava** [comment]
Any news?

**Comment by zyro** [comment]
We've kept this open for a while to gauge interest, but the demand does not seem to be high. Custom authentication integrations will always be possible, but we're trying to keep the built-in options to only the most common so we can reduce the maintenance burden.

If there is more interest in the future, happy to revisit this at a later date. :+1:
