### ISSUE TITLE
leaderboardRecordsList not return the expected record

### ISSUE THREAD

**Issue by Molder72** [heroiclabs/nakama#637]
## Description
Calling the leaderboardRecordsList function with a specific ownerId and a limit of 1, does not return the expected recor that is the record that containing the ownerId, instead it simply returns the record that has a higher score than the others.

from my tests, ownerId is not take in consideration, it always returns an arrey based on the leaderborard id ordered by score, so if another recor has the highest score it will always be the first on the list.

## Steps to Reproduce
having some records in the leaderboard_record database table, call the leaderboardRecordsList function.
this is my specific case.

strting with this records in the cocroachdb table leaderboard_record
![image](https://user-images.githubusercontent.com/3873065/124399018-233c3000-dd19-11eb-90ae-aa98b58b13ea.png)
and calling the function 
nk.leaderboardRecordsList( "USR_GLO", ["54f98200-b547-4862-a491-f0d7ef56bd7f"], 1 );
return the record line 6 (pictured)
this returned record have owner_id 5eca83ff-ae78-4065-adcf-cee5273d7353

## Expected Result
the recor in line 5 (picture)
USR_GLO ---- 54f98200-b547-4862-a491-f0d7ef56bd7f

## Actual Result
the recor in line 6 (picture)
USR_GLO  ---- 5eca83ff-ae78-4065-adcf-cee5273d7353

## Context
in the server, using TypeScript

## Your Environment
- Nakama: 3.3.0
- Database: cockroachdb v20.2.10
- Language: TypeScript
- Operating System and version: ubuntu (old)

**Comment by zyro** [comment]
@Molder72 The `nk.leaderboardRecordsList` returns an object with a few different fields. Which one are you examining for your results?

You should be looking at `ownerRecords` for records matching a set of owner user IDs you've supplied. The `records` field will always contain listed records. It's designed to allow a single function call to power both a "top scores" view as well as a "my score" view.

**Comment by Molder72** [comment]
I checked again, in fact I was using **records** instead **ownerRecords**.
And thanks to your explanations I understand why there are 2 arrays.
I thought **ownerRecords** was always empty.
and that's the problem.
**ownerRecords** always returns empty.

in the serve I launch this code (TypeScrip)

    try {
        lrl =  nk.leaderboardRecordsList( "USR_GLO", ["54f98200-b547-4862-a491-f0d7ef56bd7f"] );
        logger.info(" #######  owner-noLimit ownerRecords: ", lrl.ownerRecords);
        logger.info(" #######  owner-noLimit records:      ", lrl.records);
    } catch(error) {
        logger.info(" @@ ERROR 1 @@");
    }

    try {
        lrl = nk.leaderboardRecordsList( "USR_GLO", ["54f98200-b547-4862-a491-f0d7ef56bd7f"], 1 );
        logger.info(" #######  owner-Limit 1 ownerRecords: ", lrl.ownerRecords);
        logger.info(" #######  owner-Limit 1 records:      ", lrl.records);
    } catch(error) {
        logger.info(" @@ ERROR 2 @@");
    }

    try {
        lrl =  nk.leaderboardRecordsList( "USR_GLO", ["54f98200-b547-4862-a491-f0d7ef56bd7f"], 5);
        logger.info(" #######  owner-Limit 5 ownerRecords: ", lrl.ownerRecords);
        logger.info(" #######  owner-Limit 5 records:      ", lrl.records);
    } catch(error) {
        logger.info(" @@ ERROR 3 @@");
    }

    try {
        let ownerIds: string[] = [];
        lrl =  nk.leaderboardRecordsList( "USR_GLO", ownerIds );
        logger.info(" #######  owner-empty ownerRecords: ", lrl.ownerRecords);
        logger.info(" #######  owner-empty records:      ", lrl.records);
    } catch(error) {
        logger.info(" @@ ERROR 4 @@");
    }


with these database records
![image](https://user-images.githubusercontent.com/3873065/124511011-5a701700-ddd5-11eb-98b0-ef1c19625de5.png)

my purpose is to read the line 2 the record with score = 3

but this is what return

#######  owner-noLimit ownerRecords: %!(EXTRA []interface {}=**[]**)
#######  owner-noLimit records:      %!(EXTRA []interface {}=**[]**)

#######  owner-Limit 1 ownerRecords: %!(EXTRA []interface {}=**[]**)
#######  owner-Limit 1 records:      %!(EXTRA []interface {}=[map[expiryTime:<nil> leaderboardId:USR_GLO numScoore:1 ownerId:5eca83ff-ae78-4065-adcf-cee5273d7353 rank:1 **score:3** subscore:0 username:value:\"EzHZkVmEBL\"]])","api_id":"creategroup","mode":"after"}

#######  owner-Limit 5 ownerRecords: %!(EXTRA []interface {}=[])
#######  owner-Limit 5 records:      %!(EXTRA []interface {}=[map[expiryTime:<nil> leaderboardId:USR_GLO numScoore:1 ownerId:5eca83ff-ae78-4065-adcf-cee5273d7353 rank:1 score:3 subscore:0 username:value:\"EzHZkVmEBL\"] map[expiryTime:<nil> leaderboardId:USR_GLO numScoore:1 ownerId:54f98200-b547-4862-a491-f0d7ef56bd7f rank:2 score:1 subscore:0 username:value:\"DTcQShSfSK\"]])","api_id":"creategroup","mode":"after"}

#######  owner-empty ownerRecords: %!(EXTRA []interface {}=[])
#######  owner-empty records:      %!(EXTRA []interface {}=[])

//-----------------------------------------------------------------------//

After that i'm try to read the same recor from Unity this time.
and surprise, work as expected, from Unity I can read the record 2 whith score = 3

from unity
IApiLeaderboardRecordList records = await connection.Client.ListLeaderboardRecordsAsync(connection.Session, "USR_GLO", new string[] { "54f98200-b547-4862-a491-f0d7ef56bd7f" });

this is the unity debug
![image](https://user-images.githubusercontent.com/3873065/124512912-dcfad580-ddd9-11eb-96ae-bc20200c14a3.png)
