### ISSUE TITLE
[JS] Incorrect validation on update group maxCount

### ISSUE THREAD

**Issue by bencami22** [heroiclabs/nakama#644]
## Description
Incorrect validation on group maxCount leaving the value to remain 0, and then being discarded.

This is caused by a fault condition check here:

https://github.com/heroiclabs/nakama/blob/d94a708115c3a899439236bd02c60965e20b3743/server/runtime_javascript_nakama.go#L5317

## Expected Result
maxCount is set as part of the update.

## Actual Result
maxCount is discarded.

## Context
- [ ] Unity
- [ ] Unreal
- [x] Other

## Your Environment
- Nakama: 3.3.0
- Database: cockroach

**Comment by sesposito** [comment]
Resolved in #648.
