### ISSUE TITLE
[JS] groupCreate - creatorId argument retrieved from wrong index

### ISSUE THREAD

**Issue by bencami22** [heroiclabs/nakama#646]
## Description

In groupCreate function for javascript runtime, the creatorId is being retrieved from the wrong argument index.

It should be retrieved form index 2 but is currently on index 3.

https://github.com/heroiclabs/nakama/blob/master/server/runtime_javascript_nakama.go#L5175-L5176

## Actual Result
creatorId cannot be set.

## Context

- [ ] Unity
- [ ] Unreal
- [x] Other

## Your Environment
- Nakama: 3.3.0
- Database: Cockroachdb

**Comment by sesposito** [comment]
Resolved in #648.
