### ISSUE TITLE
issue no Context in LeaderboardList

### ISSUE THREAD

**Issue by amirhoseinjfri** [heroiclabs/nakama#653]
there is no Context in LeaderboardList but in the reference of function in the website example says it has .
![Screenshot 2021-07-28 095248](https://user-images.githubusercontent.com/17927985/127268309-de006247-91c8-47c4-80bd-b19b7abdf3bb.png)

**Comment by zyro** [comment]
@amirhoseinjfri Thanks for pointing this out. The function is correct, but the documentation is misleading and will be fixed shortly! 🙇

**Comment by sesposito** [comment]
Fixed https://github.com/heroiclabs/docs-centre/pull/148
