### ISSUE TITLE
Error is thrown when the server reads/writes storage objects with userId = ""

### ISSUE THREAD

**Issue by OlegGedzjuns** [heroiclabs/nakama#657]
## Description
Error is thrown when the server reads/writes storage objects with userId = ""

## Steps to Reproduce
Try to write to storage with any collection, any key, any value, and with userId = ""
or
Try to read from storage with userId = ""

## Expected Result
No error is thrown and data is written to storage or read from storage

## Actual Result
Exception "expects 'userId' value to be a valid id" is thrown

## Context

- [ ] Unity
- [ ] Unreal
- [X] Other - TS modules

## Your Environment
- Nakama: 3.4.0
- Docker environment version 3
- Operating System and version: Windows 10 Pro 19043.1110

Maybe this code is in the wrong order, userId parsing is called before empty string check
https://github.com/heroiclabs/nakama/blob/a3a5227b2fc06e78b5deeea08f254657761b735c/server/runtime_javascript_nakama.go#L3345
https://github.com/heroiclabs/nakama/blob/a3a5227b2fc06e78b5deeea08f254657761b735c/server/runtime_javascript_nakama.go#L3357

**Comment by zyro** [comment]
If you're looking to read/write storage objects owned by the system user, you must omit the `userId` key from the object identifier or use the full system user ID (`00000000-0000-0000-0000-000000000000`).

As you've noted if the key is present then the runtime will attempt to validate the value.
