### ISSUE TITLE
Auth tokens become invalid after server restart

### ISSUE THREAD

**Issue by chilons** [heroiclabs/nakama#658]
## Description
User tokens become invalid after server restart 

## Steps to Reproduce
1. Authenticate a user, get a token
2. Restart nakama server
3. Use the token to make any http request

## Expected Result
The token should still be valid

## Actual Result
Server returns 401 Unauthorized: "Auth token invalid"

## Your Environment
- Nakama: 3.3.3
- Database: Postgres 12.2

## Investigation
There seems to be a bug [here](https://github.com/heroiclabs/nakama/blob/846ab81a82dfd8ceac2cebffaaaf96df2256f25c/server/api_rpc.go#L57).
The sessionCache is probably lost when Nakama server restarts, it returns false and thus incorrectly deems the token invalid. It should properly recheck the token and reupdate the cache I think.

**Comment by zyro** [comment]
In Nakama 3, we've introduced more in-depth session management - to ensure this scales well with short-lived tokens, we've implemented an in-memory "whitelist" in Nakama on the known generated tokens. What you're seeing is expected behaviour for single nodes.

Clients should be prepared to re-authenticate as needed - something they should handle no matter what since session tokens do expire even outside server restarts.

**Comment by chilons** [comment]
So that means if there are a million tokens generated, the cache must hold all those tokens in memory, otherwise they would be "invalid"? How does that make any sense at all?
If the cache's holding all the tokens it ever generated, then that means if I keep a server running for a couple of years it could run out of memory due to all the tokens in cache adding up whenever somebody logs in and out? That's ridiculous.
If a token is not whitelisted it should be checked, a cache is just a cache, it cannot hold all information and shouldn't determine that a token is valid or not.

**Comment by zyro** [comment]
The whitelist is not all tokens ever generated, only a rolling window of currently active ones. Once tokens expire or are otherwise invalidated they are of course removed from the whitelist even if the server never restarts.

**Comment by chilons** [comment]
> The whitelist is not all tokens ever generated, only a rolling window of currently active ones. Once tokens expire or are otherwise invalidated they are of course removed from the whitelist even if the server never restarts.
That's pretty much the same thing because people could set a really long expiration time, or even with just an expiration time of like 3 months there could be many people logging in and out; a malicious attacker could create a bunch of tokens in days, thus crash the server.
This is a serious memory leak and confusing behavior, all for "optimizing" a trivial JWT checking operation.

**Comment by zyro** [comment]
The intention is not to optimise the JWT check, you'll find that is still done. The whitelist governs session management aspects that JWTs by themselves cannot, and there is currently no plan to significantly change its core behaviour.

Thanks for your feedback, we'll make a note to introduce an upper bound on the maximum size of the whitelist. 👍

**Comment by chilons** [comment]
> The intention is not to optimise the JWT check, you'll find that is still done. The whitelist governs session management aspects that JWTs by themselves cannot, and there is currently no plan to significantly change its core behaviour.
> 
> Thanks for your feedback, we'll make a note to introduce an upper bound on the maximum size of the whitelist.

Then the code should perform a full check, whatever that is, when a token is not whitelisted. A cache cannot be used as an authorative check. If the whitelist is still being an authorative check like right now and you limit it's size, it's gonna be even worse, tokens would randomly be deemed "invalid" here and there.

>Clients should be prepared to re-authenticate as needed - something they should handle no matter what since session tokens do expire even outside server restarts.

My client code is always ready to re-authenticate, but my players shouldn't have to login again whenever I restart the server for whatever reason. The client doesn't even know that it's token suddenly became invalid for no reason.

**Comment by zyro** [comment]
Tokens can always be invalidated for any number of reason (config change, developer action, server restart etc) and clients should be prepared to re-authenticate again. This is a design decision we're not looking to change at the moment.
