### ISSUE TITLE
Server authoritative bytes data gets corrupted on TypeScript

### ISSUE THREAD

**Issue by LucasGaspar** [heroiclabs/nakama#659]
## Description
When transferring bytes data into a TypeScript server authoritative match and relaying it back the bytes data gets corrupted on the process

## Steps to Reproduce
Send bytes data from Unity.
`nakamaManager.Socket.SendMatchStateAsync(match.Id, (long)code, bytes);`

Relay the message back to unity from the server.
`dispatcher.broadcastMessage(message.opCode, message.data, null, message.sender);`

Read bytes data received in Unity.

## Expected Result
The byte data received in Unity should be exactly the same as the sent data

## Actual Result
I sent this from unity: (Bytes to string with a space between each one)
12 0 0 0 8 0 16 0 14 0 4 0 8 0 0 0 253 96 66 65 142 250 66 191 0 0 20 0

I received this after relaying the message: (Bytes to string with a space between each one)
12 0 0 0 8 0 16 0 14 0 4 0 8 0 0 0 239 191 189 96 66 65 239 191 189 239 191 189 66 239 191 189 0 0 20 0

## Context
Unity + TypeScript server authoritative

## Your Environment
Nakama 3.4.0-r1
Unity Nakama 3.0.0 package

**Comment by sesposito** [comment]
@LucasGaspar what's the reason you're sending raw bytes in the messages? The JS runtime expects an utf-8 string for the messages, so the issue could be that the bytes are wrongly decoded as such if the payload is not utf-8.

**Comment by LucasGaspar** [comment]
@sesposito I wanted to use flatbuffers

**Comment by LucasGaspar** [comment]
Thank you a lot @sesposito 😄
