### ISSUE TITLE
func  LeaderboardRecordWrite line 422 

### ISSUE THREAD

**Issue by david1mband** [heroiclabs/nakama#662]
## Description
There is a minor bug in the line 422 of nakama/server/core_leaderboard.go,
func LeaderboardRecordWrite
filterSQL = " WHERE leaderboard_record.score <> $5 OR leaderboard_record.subscore <> $5"

The first $5 is wrong, it would be $4?

- Nakama: 3.4.0

**Comment by zyro** [comment]
@david1mband Nice find, fixed in d0386bbe022f30e24d575dda9c1655a3e7ff63b8 and will be part of the next release. 👍
