### ISSUE TITLE
BeforeDemoteGroupUsers AfterDemoteGroupUsers not handling

### ISSUE THREAD

**Issue by Molder72** [heroiclabs/nakama#668]
## Description
when I call DemoteGroupUsersAsync in unity the relative BeforeDemoteGroupUsers and AfterDemoteGroupUsers not running

## Steps to Reproduce
IN UNITY
await connection.Client.DemoteGroupUsersAsync(connection.Session, actualGroup.Group.Id, new string[] { userGroup.ownerId });

IN SERVER (typescript)

```
const InitModule: nkruntime.InitModule = function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama,
initializer: nkruntime.Initializer) {
             initializer.registerBeforeDemoteGroupUsers(beforeDemoteGroupUsersFn);   
             initializer.registerAfterDemoteGroupUsers(afterDemoteGroupUsersFn); 
}
```

```
const beforeDemoteGroupUsersFn: nkruntime.BeforeHookFunction<nkruntime.DemoteGroupUsersRequest> =
    function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, request: nkruntime.DemoteGroupUsersRequest): nkruntime.DemoteGroupUsersRequest {

               logger.info("@@@ beforeDemoteGroupUsersFn: ");

                return request;
    }
```

```
 const afterDemoteGroupUsersFn: nkruntime.AfterHookFunction<void, nkruntime.DemoteGroupUsersRequest> =
    function (ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, data: void, request: nkruntime.DemoteGroupUsersRequest) {

        logger.info("@@@ afterDemoteGroupUsersFn: ");
}

```

## Expected Result
in the server log
@@@ beforeDemoteGroupUsersFn: 
@@@ afterDemoteGroupUsersFn:

## Actual Result
server log empty

## Context

- [x ] Unity
- [ ] Unreal
- [ ] Other

## Your Environment
- Nakama: 3.5.0
- Database: cockroach:latest-v20.2
- Operating System and version: ubuntu

**Comment by sesposito** [comment]
This is already fixed in https://github.com/heroiclabs/nakama/pull/664 and will be part of the next server release.
