### ISSUE TITLE
Reply to RPC call from the C++ SDK is missing data

### ISSUE THREAD

**Issue by jan-ekholm** [heroiclabs/nakama#688]
When an RPC request is submitted via the C++ SDK the received reply is supposed to have `payload`, `id` and `httpKey` fields. Only the `payload` seems to contain what it should, the other two are empty. The RPC call itself is executed successfully and the reply payload is correct.

See more complete description here: https://forum.heroiclabs.com/t/c-rpc-callback-contains-no-id/1939

**Comment by zyro** [comment]
@jan-ekholm Thanks for the report! This data is not missing, it's just not expected as part of an RPC response. Client SDKs just use the same `Rpc` entity for both requests and responses for convenience.

We'll look into changing this if it creates confusion, but this is not currently a bug. 👍
