### ISSUE TITLE
Remote config example code does not work

### ISSUE THREAD

**Issue by mrpuzzler** [heroiclabs/nakama#692]
Put Lua code on server as described here for Dynamic parameters
https://heroiclabs.com/docs/nakama/tutorials/server/remote-configuration/

Fetch In-app parameters as described with curl code.

Get response:
{"error":"json: cannot unmarshal object into Go value of type string","message":"json: cannot unmarshal object into Go value of type string" ,"code":3}

Why?

**Comment by zyro** [comment]
The documented `curl` example uses the `POST` HTTP method, it should instead be `GET`.

Not a Nakama server issue so will close. Thanks for pointing this out, we'll fix the docs! 👍

**Comment by mrpuzzler** [comment]
With GET it returns this:

{"code":13,"error":{},"message":"Runtime function returned invalid data - only allowed one return value of type String/Byte."}

**Comment by zyro** [comment]
I just tested it with `GET` and it works fine. Which Lua code are you using for the server-side RPC function?

**Comment by mrpuzzler** [comment]
--Same as above we'll use server-side code with a module named `"rc.lua"`
and placed in the runtime path for the server. local nk = require("nakama")
local parameters = { reachable_levels = 10, max_player_level = 90,
min_version = 12 } local object = { collection = "configuration", key = "rc"
, value = parameters, permission_read = 1, permission_write = 0, version =
"*" -- Only write object if it does not already exist. } pcall(nk.
storage_write, { object }) -- Write object, ignore errors. local function
remote_configuration(_context, _payload) local rc = { collection = object.
collection, key = object.key } local objects = nk.storage_read({ rc })
return objects[1].value end nk.register_rpc(remote_configuration, "rc")

Пн, 27 сент. 2021 г. в 16:17, Andrei Mihu ***@***.***>:

**Comment by zyro** [comment]
Change `return objects[1].value` to `return nk.json_encode(objects[1].value)`. Either way we'll go through and fix the example in the docs, but this is not a server issue. 👍
