### ISSUE TITLE
Unreal Engine Support

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#7]
Add a client library for the Unreal engine (with compatibility for other C++ based game engines).

**Comment by julienBouysset** [comment]
Some idea: 
- Have a visual blueprint as it can be found on the gamesparks plugin (I'm talking about the visible part of blueprint https://docs.gamesparks.com/getting-started/using-authentication/unreal-authentication.html).

- Equally like gamesparks plugin have a visual blueprint function that allows automatic login via steam (via steamworks if install) on gamesparks this functionality retrieves the steamID and token and sends it to the server that checks via the api public steam. its very powerfull.

**Comment by novabyte** [comment]
This is now online as a separate GitHub project - https://github.com/heroiclabs/nakama-unreal 🎉 

Blueprints and a full test harness are in progress as a separate development sprint. I'll close this issue and any other questions/feature requests can be made on the separate repo.
