### ISSUE TITLE
Filter leaderboard listing by specific ids

### ISSUE THREAD

**Issue by brinca** [heroiclabs/nakama#71]
## Description
Implement a way to filter the leaderboard listing by a specific set of leaderboard id's, instead of getting the whole list at once.

There is sometimes a need to get just a subset of the leaderboards at a time, to check on their properties (count, metadata, etc) in order to display them properly.

Right now we have to get the list of all the leaderboards (using NLeaderboardsListMessage), and then filter it on the client side, which is very wasteful, and unwieldy in a production environment, where there could be thousands of leaderboards to fetch and comb through...

**Something like NUsersFetchMessage, where you can pass a variable parameter list of id's to the NLeaderboardsListMessage builder method, would work great.**

**Comment by novabyte** [comment]
This is added in https://github.com/heroiclabs/nakama/commit/c7221f8c609ade175808f70f7333ce548c4adf56 as part of the 0.13.0 release. You'll need the latest Unity client (0.6.0) or greater.
