### ISSUE TITLE
[FEATURE REQUEST] expose loading a JSON object by file to LUA runtime

### ISSUE THREAD

**Issue by jasonwinterpixel** [heroiclabs/nakama#718]
Currently, we configure various elements of our nakama instances by loading a json object at startup. We use that json object to create leaderboards, season lengths and start times, and create and insert various items into the database.  This singular json object allows us to deploy a second instance of our backend instantly, as it configures itself on startup.

Before the implementation of list_leaderboards, the nakama team specified that they expected people to have some kind of file like this and load it both on client and server, in order to have the client and server reference the same point of truth for what the leaderboard definitions are. This is a good design.

As far as I can tell, it's currently impossible to access the file system in the Lua runtime. This means that in order to supply a JSON object to the Lua runtime, we are manually inserting the JSON object into a LUA file by copy-pasting it as a multiline string and running nk.json_decode on it.

We would like to be able to load a json file directly in the LUA runtime so that we can use it to configure our nakama instance and bake the file into the client binaries. This will allow us to specify single points of truth for various configuration values like season lengths, urls to various things, names of stuff, etc. Some of the stuff we'd like to synchronize between client/backend are things we need the client to access even without a nakama connection, like for instance the URL to the nakama backend, or the app id, or the version code of the client.

We are considering a simple go module to just load a JSON file into an object and dump it into the database, but that seems like a workaround that perhaps could be improved:

A function like
`nk.json_load('path/object.json')`

would be useful for us to do this.

**Comment by novabyte** [comment]
@jasonwinterpixel This already exists in Nakama server as part of the server framework. The function can load files which are stored within the path relative to the `--runtime.path` used to load Go, Lua, or JS/TS code.

https://github.com/heroiclabs/nakama/blob/master/server/runtime_lua_nakama.go#L267

```lua
nk.file_read(...)
```

@seanpackham We should update the Function Reference to include this function under the "utils" section.
