### ISSUE TITLE
Support custom connection arguments for pgx driver in sql.Open("pgx")

### ISSUE THREAD

**Issue by jordo** [heroiclabs/nakama#730]
## Description

We'd like to use pgBouncer for managing a our postgres connection pool backend numbers in transaction pool mode.

Unfortunately with prepared statements, the statement ID and subsequent query can get proxy'd through different connections, which doesn't work for postgres.  The solution, which everyone seems to have implemented, (including twitch https://blog.twitch.tv/en/2016/10/11/how-twitch-uses-postgresql-c34aa9e56f58/ see binary parameters ) is to force the px driver into "prefer_simple_protocol", which makes a single round trip to the db per statement.  Downside is losing binary prep statements, but some upsides as well... (single round trip, and works with pgBouncer and other pools).

he vendored pgx driver in the latest nakama has support for this now.  Either through configuration the driver with `DriverConfig`, or passing an additional connection argument to the driver.  In this case `prefer_simple_protocol`.  

I'm up for a variety of ways to implement this, as it seems pretty basic to support something like this in `db.go`. I'm not sure if it would be best done in the connection URI string as a named param, or explicitly through something like `config.GetDatabase()` in the nakama configMap, and then initializing the pgx driver with a `DriverConfig`.

Thoughts?

**Comment by jordo** [comment]
I guess the other option would be to use `statement_cache_mode=describe` as well in the pgx driver,  https://github.com/jackc/pgx/blob/cf0de913ee8facdfef0a7611d41cd67522b12c76/conn.go#L123-L127 .

Either way, there's a need to get this into the pgx driver in some shape or form.  Open to implement in the best way advised.

**Comment by novabyte** [comment]
@jordo Thanks for the research. I'm not familiar with the "statement_cache_mode" option because we've never had to deploy a production game with pgBouncer so far. This `statement_cache_mode=describe` is it expected to be passed in through the database DSN uri?

**Comment by jordo** [comment]
> This `statement_cache_mode=describe` is it expected to be passed in through the database DSN uri?

That's correct.  This is supported in the uri with the current pgx version that nakama is using.    Both `prefer_simple_protocol` or `statement_cache_mode=describe` are available as DSN uri parameters to the pgx driver, or in in the `DriverConfig` structure if you initialize the pgx driver with a config struct.

The current connection pooling in sql.go/nakama (maxIdle, maxOpen) isn't going to be as efficient if we deploy multiple nakama application servers as each server instance's pool config is going to be configured independently.  This makes horizontally scaling on demand a little more trickier to maximize utilization of available/reserved postgres backends ( without overloading postgres with too many connections/pids).  I imagine this is probably the number 1 use case for pgBouncer.  If we know that our optimal # of postgres backends is say 100, then we configure pgBouncer to just utilize 100 connections, and can scale our application servers in front of the connection pooler without too much worry or reconfiguration.  

As far as passing any config items to pgx initialization, I'm open to achieving this is whatever was is preferrable.

**Comment by novabyte** [comment]
@jordo If you can pass `"statement_cache_mode=describe"` and `"prefer_simple_protocol=true"` can be passed as part of the DSN uri parameters I don't think any change needs to happen in Nakama for this to work. You simply need to pass it through the start up option in the server: `--database.address "somedsn?....etc"`. Please reopen if this requires a code change.

**Comment by jordo** [comment]
This does look like it gets passed through correctly to pgx.  So we can use the `database.address` config.  Thanks for looking into.
