### ISSUE TITLE
Expose Debug log level for nakama applications

### ISSUE THREAD

**Issue by jordo** [heroiclabs/nakama#742]
It would be nice to expose the Debug log level.  Currently the log levels that are exposed to a nakama application are INFO,WARN, and ERROR.  Nakama internally uses DEBUG for various things, it would be nice to expose this at the application level as well.

**Comment by novabyte** [comment]
> Currently the log levels that are exposed to a nakama application are INFO,WARN, and ERROR.

@jordo Where did you read that information from? (It would be good to clear it up in the documentation if needed.)

We already support ERROR, WARN, INFO, and DEBUG levels (though we don't have a TRACE level yet). This can be configured with `--logger.level DEBUG` in cmdline arguments or via YML:

```yml
logger:
  level: DEBUG
```

We also have functions to write to all logger levels via the server framework. i.e. `logger_debug()` in Lua, `logger.debug()` in JavaScript, and `logger.Debug()` in Go.

**Comment by jordo** [comment]
@novabyte Ah yes, this is just a documentation issue:   https://heroiclabs.com/docs/nakama/server-framework/function-reference/#logger
