### ISSUE TITLE
Linking account to Steam account causes SEGFAULT in Nakama server

### ISSUE THREAD

**Issue by dsnopek** [heroiclabs/nakama#744]
## Description
I'm able to authenticate a user account via Steam just fine (using `NakamaClient.authenticate_steam_async()` in the Godot client library).

I also used to be able to authenticate via the email method, and then link to a Steam account (via `NakamaClient.link_steam_async()`), but at some point, this has started causing a SEGFAULT in the Nakama server, which kicks everyone off the server as it restarts.

I don't know exactly when this started happening, because folks normally either login via Steam or Email - it's much rarer to login via Email and link a Steam account. So, it could have been caused by a Nakama version upgrade in the past but I didn't notice until just now? In any case, my code for linking to Steam and the Nakama configuration hasn't changed between when it was working and now. And if I'm doing something wrong, the server should probably give a nice message instead of a SEGFAULT. :-)

## Steps to Reproduce

1. Register a new user via email
2. Connect to server socket
3. Send message to link account to steam
4. Check server logs and see the SEGFAULT

## Expected Result
The Nakama account is linked to the Steam account and the Nakama server keeps working.

## Actual Result

The Nakama server SEGFAULTs, everyone is kicked from the server and it restarts.

Here's the info from the logs:

```
nakama_1       | panic: runtime error: invalid memory address or nil pointer dereference
nakama_1       | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14553b1]
nakama_1       | 
nakama_1       | goroutine 224 [running]:
nakama_1       | github.com/heroiclabs/nakama/v3/server.(*ApiServer).LinkSteam(0xc0002a6370, {0x1e77a38, 0xc000855020}, 0xc0008b7040)
nakama_1       |        github.com/heroiclabs/nakama/v3/server/api_link.go:416 +0x271
nakama_1       | github.com/heroiclabs/nakama/v3/apigrpc._Nakama_LinkSteam_Handler.func1({0x1e77a38, 0xc000855020}, {0x194c5c0, 0xc0008b7040})
nakama_1       |        github.com/heroiclabs/nakama/v3/apigrpc/apigrpc_grpc.pb.go:1956 +0x7b
nakama_1       | github.com/heroiclabs/nakama/v3/server.StartApiServer.func1({0x1e77a38, 0xc000854de0}, {0x194c5c0, 0xc0008b7040}, 0xc000351bb8, 0xc000354870)
nakama_1       |        github.com/heroiclabs/nakama/v3/server/api.go:101 +0x9f
nakama_1       | github.com/heroiclabs/nakama/v3/apigrpc._Nakama_LinkSteam_Handler({0x1a10d00, 0xc0002a6370}, {0x1e77a38, 0xc000854de0}, 0xc0003e0660, 0xc0002d69f0)
nakama_1       |        github.com/heroiclabs/nakama/v3/apigrpc/apigrpc_grpc.pb.go:1958 +0x138
nakama_1       | google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017ae00, {0x1e8e628, 0xc00069e780}, 0xc0003bf320, 0xc0002d6b10, 0x275b1c8, 0x0)
nakama_1       |        google.golang.org/grpc@v1.42.0/server.go:1282 +0xccf
nakama_1       | google.golang.org/grpc.(*Server).handleStream(0xc00017ae00, {0x1e8e628, 0xc00069e780}, 0xc0003bf320, 0x0)
nakama_1       |        google.golang.org/grpc@v1.42.0/server.go:1616 +0xa2a
nakama_1       | google.golang.org/grpc.(*Server).serveStreams.func1.2()
nakama_1       |        google.golang.org/grpc@v1.42.0/server.go:921 +0x98
nakama_1       | created by google.golang.org/grpc.(*Server).serveStreams.func1
nakama_1       |        google.golang.org/grpc@v1.42.0/server.go:919 +0x294
```

This appears to point at this line in the code:

https://github.com/heroiclabs/nakama/blob/master/server/api_link.go#L416

## Context

Using the Godot client with Godot 3.4.2.

## Your Environment

- Nakama: 3.10.0 (I also tried with 3.4.0 - it fails just the same)
- Database: CockroachDB 19.2.5
- Environment name and version: Docker 19.03.3
- Operating System and version: Ubuntu 18.04

**Comment by zyro** [comment]
This should now be fixed in commit 59a68b9b40fa50dffc1ec4069d0be4854dde6525.

The panic would happen if there was no input at all from the client for the Steam token field. I'm not sure why that would be blank from the sender in your case, but the server should absolutely gracefully handle this case rather than panic.

Double-check the input if you can to make sure the Steam access token is not empty, but please reopen this issue if you still observe this panic from the next Nakama release onward.

**Comment by dsnopek** [comment]
> Double-check the input if you can to make sure the Steam access token is not empty, but please reopen this issue if you still observe this panic from the next Nakama release onward.

Hm. I snuck in a print statement, and it's definitely passing a Steam access token into `NakamaClient.link_steam_async()`. I suppose something could be going wrong inside of the Nakama client library for Godot? I'll attempt to dig deeper when I have chance.

**Comment by dsnopek** [comment]
Ooooh, I think I might need to update the Godot client library. Looking at this commit from the summer:

https://github.com/heroiclabs/nakama-godot/commit/b6272c4547c3d4d54a7e485c2d70eaa167969c08#diff-2313628672fcffb4b4c78be7abf6295445a18a1cc60e667d5688adb25a52daf7L418

... it appears to be changing the format of the message to link Steam accounts.

**Comment by dsnopek** [comment]
Ok, updating the Godot client library to the latest from the 'master' branch on GitHub fixed it!

@novabyte @Faless You guys should probably make a new release of the Godot client library sometime soon. This issue is present in the latest release (2.1.0 from August 2020, so it's ~1.5 years old!), as well as some other fixes that I've been using for awhile that have been merged to 'master', but aren't part of a release yet.

**Comment by novabyte** [comment]
@dsnopek Would you be interested to help as a maintainer? You know the library well; let me know what you think. We can always speak on a brief call after the new year if you'd like?

**Comment by dsnopek** [comment]
@novabyte Yes, that's something I'd definitely be interested in! Let's chat about it more in the new year :-)
