### ISSUE TITLE
JavaScript: linkDevice calls linkCustom instead of linkDevice

### ISSUE THREAD

**Issue by vyacheslav-sozap** [heroiclabs/nakama#745]
## Description
Runtime: JavaScript. nk.linkDevice calls linkCustom instead of linkDevice. Can be seen here:

https://github.com/heroiclabs/nakama/blob/59a68b9b40fa50dffc1ec4069d0be4854dde6525/server/runtime_javascript_nakama.go#L2025-L2044

on this line:

https://github.com/heroiclabs/nakama/blob/59a68b9b40fa50dffc1ec4069d0be4854dde6525/server/runtime_javascript_nakama.go#L2038

## Steps to Reproduce

1. Call nk.linkDevice

## Expected Result
Device linked to player

## Actual Result
Device not linked to player
custom_id changed

## Context
- Unity

## Your Environment
- Nakama: 3.9.0
- Database: PostgreSQL from Docker image postgres:14.1-alpine
- Environment name and version: Docker image heroiclabs/nakama:3.9.0
- Operating System and version: WSL2 on Windows 10

**Comment by zyro** [comment]
@vyacheslav-sozap Thanks for reporting this! I've investigated and merged a fix in 2be8cf82a34b569934718f73483b71fd762ae397. This will be part of the next release. 👍
