### ISSUE TITLE
Panic at core_wallet.go:337 

### ISSUE THREAD

**Issue by kevinrstewart** [heroiclabs/nakama#759]
## Description
Using the Nakama runtime to call `AccountExportId` results in a panic due to a null deference in core_wallet.go:337, specifcally here: https://github.com/heroiclabs/nakama/blob/v3.10.0/server/core_wallet.go#L337 Looking at the code it looks like the value for `limit` is allowed to be `nil` but there is no nil check here. It looks like this is called by other internal code and `nil` is passed directly.

## Steps to Reproduce
1. Register a new user
2. Connect to server socket
3. Call `nk.AccountExportId` on the user. An account needs to exist to hit this panic

## Expected Result
No panic

## Actual Result
(Snipped for brevity/privacy)
```runtime error: invalid memory address or nil pointer dereference\ngoroutine 4504 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1802 +0x13a\npanic({0x2203660, 0x3010e50})\n\truntime/panic.go:1047 +0x262\ngithub.com/heroiclabs/nakama/v3/server.ListWalletLedger({0x26ef138, 0xc000f802a0}, 0xc000098d20, 0xc0000ac4e0, {0x93, 0x74, 0x4, 0xa8, 0x9c, 0xb9, ...}, ...)\n\tgithub.com/heroiclabs/nakama/v3@v3.10.0/server/core_wallet.go:337 +0xf10\ngithub.com/heroiclabs/nakama/v3/server.ExportAccount({0x26ef138, 0xc000f802a0}, 0xc000098d20, 0xc0000ac4e0, {0x93, 0x74, 0x4, 0xa8, 0x9c, 0xb9, ...})\n\tgithub.com/heroiclabs/nakama/v3@v3.10.0/server/core_account.go:431 +0x1b98\ngithub.com/heroiclabs/nakama/v3/server.(*RuntimeGoNakamaModule).AccountExportId(0xc0000cd680, {0x26ef138, 0xc000f802a0}, {0xc001270570, 0x24})\n\tgithub.com/heroiclabs/nakama/v3@v3.10.0/server/runtime_go_nakama.go:539 +0x1a6\n```

## Context

- [ ] Unity
- [ ] Unreal
- [X ] Other

## Your Environment

- Nakama: 3.10.0

**Comment by zyro** [comment]
@kevinrstewart You're right, this is specifically an issue with exports and does not affect other wallet operations. Fix merged in 5e7c2052828679fd9092ec96d608cee65afe032f and will be part of the next release.
