### ISSUE TITLE
Typescript nk.multiUpdate() function does not update user account details

### ISSUE THREAD

**Issue by gpiumatti** [heroiclabs/nakama#795]
## Description

From Typescript environment, `nk.multiUpdate()` with UserUpdateAccount[] does not work.

## Steps to Reproduce

```typescript
const user = nk.authenticateCustom(nk.uuidv4());
nk.multiUpdate([{
    userId: user.userId,
    displayName: 'test',
    metadata: { test: 'test' }
}], null, null);

const acct = nk.accountGetId(user.userId);
```
The user's account details are not updated.

## Expected Result
```
acct = {
   user: {
    displayName: 'test',
    metadata: { test: 'test' } 
  }
}
```
## Actual Result

```
acct = {
   user: {
    displayName: '',
    metadata: {  } 
  }
}
```

## Your Environment

- Nakama: 3.10.0
- Typescript environment

**Comment by zyro** [comment]
@gpiumatti This has already been fixed in commit eb5270fdd5a8ab79f0bed86d51d38a2b6d689a45 and will be part of the next release. 👍
