### ISSUE TITLE
Matchmaker doesn't match users although it sends back matchmaking tickets

### ISSUE THREAD

**Issue by amuuu** [heroiclabs/nakama#796]
## Description
Matchmaker doesn't match clients. It only sends matchmaking tickets back. I tested different implementations of matchmaking client codes (Unity) with both a production server and a local Nakama docker container. None of them worked.
Nakama log shows that it successfully receives matchmaking requests and sends back the tickets, however it doesn't match them together. (the socket connection, the authentication, rpc calls, and other features work properly.)

The msg receive log:
```
{"level":"debug","ts":"2022-03-02T10:06:04.554Z","caller":"server/pipeline.go:66","msg":"Received *rtapi.Envelope_MatchmakerAdd message","uid":"690b8434-16d3-411d-b69b-f1171ef2d144","sid":"5cedffff-9a10-11ec-8c4b-7106fdcb5b46","cid":"0","message":{"MatchmakerAdd":{"min_count":3,"max_count":4,"query":"*"}}}
```
Response log:
```
{"level":"debug","ts":"2022-03-02T10:06:04.556Z","caller":"server/session_ws.go:393","msg":"Sending *rtapi.Envelope_MatchmakerTicket message","uid":"690b8434-16d3-411d-b69b-f1171ef2d144","sid":"5cedffff-9a10-11ec-8c4b-7106fdcb5b46","envelope":"cid:\"0\"  matchmaker_ticket:{ticket:\"8fe8919e-3696-4bcd-8d45-682bd353b5ac\"}"}
```

The main issue is that everything used to work fine until a few days ago. I tried different scenarios but it doesn't seem to work. Maybe it has something to do with the internals of Nakama server?

## Steps to Reproduce
Not sure how to reproduce this, but what makes this bug happen to my projects often follow these steps:
1) Create sockets and authenticate multiple clients (let's say 4 clients)
2) Have each client send a matchmaking request with the room size of 3 to 4.
3) Each client will receive their matchmaking ticket properly
4) It haults!

## Expected Result
It's expected for each client to receive a `Envelope_MatchJoin` message
```
{"level":"debug","ts":"2022-03-02T10:14:07.093Z","caller":"server/pipeline.go:66","msg":"Received *rtapi.Envelope_MatchJoin message","uid":"2a470c91-db77-44f2-8ce6-0c24567db8d4","sid":"6450b250-9a11-11ec-8c4b-7106fdcb5b46","cid":"1","message":{"MatchJoin":{"Id":{"Token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDYyMTYwNzcsIm1pZCI6IjY5ZjkzY2ZlLTY0YzItNDI5Yi04MTIxLTJkOTQ0MjBiMTZjNC4ifQ.VyH766Bj6oO-3mlZSpTJjYGBZPY560vXEvkpIqxhxEU"}}}}
```

## Actual Result
They aren't receiving the `Envelope_MatchJoin` message.

## Context

- [x] Unity
- [ ] Unreal
- [ ] Other

## Your Environment
- Nakama: 3.2.1 and 3.9.0 were checked.
- Database: Both of CockroachDB and PostgreSQL were checked.
- Operating System and version: Both of Windows and Linux were checked.

**Comment by mofirouz** [comment]
There was a regression that's now fixed in 3.10.0 - please try with 3.10.0 and report back. If the issue still persists, please put a code example and your Nakama config in here for us to investigate further.

**Comment by amuuu** [comment]
Yes! I updated it to 3.10.0 and it got fixed. Thank you so much!

**Comment by mofirouz** [comment]
Perfect 👍

**Comment by mofirouz** [comment]
Please upgrade to v3.11+ and report again.

**Comment by SamsTheGreatest** [comment]
@mofirouz It worked after upgrading server to `3.11.0`. Thank you.

Maybe we can add this change to docker-compose files?
