### ISSUE TITLE
How to add additional authentication features？

### ISSUE THREAD

**Issue by gopecan** [heroiclabs/nakama#803]
I want to extend the existing authentication functions, such as adding WeChat's oAuth2 authentication. Can I add a function myself, such as AuthenticateWeChatAsync(), as part of the Nakama server functionality. Should I write this function as RPC, or write it as a hook and finally import it into the GO module. Or do I need to add this feature to the Nakama source code and compile the entire Nakama program? How should I do this?

**Comment by mofirouz** [comment]
GitHub issues isn’t the best place to ask for best practices. 

The short answer is you should use a BeforeHook on AuthenticateCustom and do token exchange. For a full answer with examples, please post on the forum; https://forum.heroiclabs.com

Alternatively you can try and open a PR for WeChat Auth support within Nakama and we can take a look.

**Comment by gopecan** [comment]
thanks I get it
