### ISSUE TITLE
[FEATURE REQUEST] Use Prometheus labels instead of changing the metric name

### ISSUE THREAD

**Issue by mixecan** [heroiclabs/nakama#806]
Hello
There are some metrics that change prefix depending the subject, for example the ones related to RPC (count, latency, etc)

These metrics should use labels instead so that `nakama_cluster_client_RPCName_count` would be something like `nakama_cluster_client_rpc_count{rpc="RPCName"}`
Maybe also "client" can be changed into a label.

This will make exploring metrics and creating dashboard easier

**Comment by zyro** [comment]
Solved in https://github.com/heroiclabs/nakama/pull/807 and will be part of the next release.
