### ISSUE TITLE
Possible error in concurrent leaderboard creation `LeaderboardCache.Create` (very low risk)

### ISSUE THREAD

**Issue by brianwinterpixel** [heroiclabs/nakama#821]
## Description

When inspecting a code path in our application for possible concurrency issues, I came across this function:

https://github.com/heroiclabs/nakama/blob/a5d95d2f3f26a9322d534a47c4f793a52fce513c/server/leaderboard_cache.go#L298-L362

This function is designed to no-op on repeated calls with the same params, but I speculate it may produce an SQL error: `ERROR 1062 (23000): Duplicate entry 'some_new_leaderboard_id' for key 'PRIMARY'`. For our use, this has very low risk and minimal side effects. It's also possible my analysis is wrong.

Possible fix:

```diff
--	query += ") RETURNING create_time"
++	query += ") ON DUPLICATE KEY UPDATE id=id RETURNING create_time"
```

## Steps to Reproduce

I expect it may appear while frequently running `nk.leaderboard_create` for the same leaderboard id when creating a new leaderboard.

## Expected Result

This function should no-op if the leaderboard already exists.

## Actual Result

Under good server health, I believe this function may occasionally produce an SQL error: `ERROR 1062 (23000): Duplicate entry 'some_new_leaderboard_id' for key 'PRIMARY'`

## Context

Server

## Your Environment

N/A

**Comment by novabyte** [comment]
Hi @brianwinterpixel. Thanks for the issue. It's a bit unclear to me whether you've encountered a concurrent access issue with the `nk.leaderboard_create` function or whether you think it could produce the error message you shared in certain circumstances. If you could clarify that would be great. Please also share whether you run the server with CRDB, Postgres, or AWS Aurora for PG.

**Comment by brianwinterpixel** [comment]
This issue was not actually encountered. I just thought I found a possible issue in the code and figured it wouldn't hurt to document it.

We use Postgres.
