### ISSUE TITLE
Swagger definition for "protobufAny" possibly incorrect in Nakama 3.11.0?

### ISSUE THREAD

**Issue by dsnopek** [heroiclabs/nakama#823]
I ran the codegen in the Godot Nakama SDK using the [apigrpc.swagger.json](https://github.com/heroiclabs/nakama/blob/master/apigrpc/apigrpc.swagger.json) from Nakama 3.11.0 to see if there were any API changes that needed to be added to the client SDK, and got unexpected results for 'protobufAny'.

Here's the changes to the swagger file:

```
--- a/apigrpc/apigrpc.swagger.json
+++ b/apigrpc/apigrpc.swagger.json
@@ -4769,14 +4769,11 @@
     "protobufAny": {
       "type": "object",
       "properties": {
-        "typeUrl": {
+        "@type": {
           "type": "string"
-        },
-        "value": {
-          "type": "string",
-          "format": "byte"
         }
-      }
+      },
+      "additionalProperties": {}
     },
     "rpcStatus": {
       "type": "object",
```

From PR #716 

This seems possibly incorrect, because the value is being removed, and as far as I can tell, `"@type"` would be the only property starting with `'@'`.

"protobufAny" is only used in "rpcStatus", for the "details" array. If the value is removed, then there'd be no way to see what those details actually are.

Thoughts?

**Comment by ftkg** [comment]
You're correct - this was an actual fix on the protoc plugin (https://github.com/grpc-ecosystem/grpc-gateway/pull/2292) but it breaks our SDK generators. 

I'll manually revert it in a PR for now.
