### ISSUE TITLE
[BUG] Match Logger BUG

### ISSUE THREAD

**Issue by lixw1994** [heroiclabs/nakama#834]
In lua runtime, If I `create_match` from `match_loop`, [this line](https://github.com/heroiclabs/nakama/blob/5029cf4972ef7a51baf583e1b3d6f2705abfb570/server/match_registry.go#L237) will cause `mid` field more and more in log

**Comment by zyro** [comment]
Fixed in 26094fa668ab204f6cc4325b67c02d9a1e5a884b and will be part of the next release.
