### ISSUE TITLE
typescript  server rpc 

### ISSUE THREAD

**Issue by atgui** [heroiclabs/nakama#838]
## Description
get the current server time ::  new Date(new Date().toLocaleDateString()).getTime()    is NaN

## Steps to Reproduce
function getRewardRpc(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string) {
    
    let startTime = new Date(new Date().toLocaleDateString()).getTime();    // NaN
    return JSON.stringify({time:startTime });
}

## Actual Result
let startTime = new Date(new Date().toLocaleDateString()).getTime();  
startTime = NaN

## Context

- Unity

## Your Environment

- Nakama: 3.11.0
- Database: postgreSQL 14.2
- Environment name and version:
- Operating System and version: windows11

**Comment by zyro** [comment]
```
new Date(new Date().toLocaleDateString()).getTime(); // NaN
```
This is correct, the expression above evaluates to `NaN` and as far as we can verify (you can try various online JS playground tools) it is indeed supposed to.

The correct way to get current time (in milliseconds) is:
```
new Date().getTime();
```
