### ISSUE TITLE
Can't build from source on Windows

### ISSUE THREAD

**Issue by bokmcdok** [heroiclabs/nakama#84]
## Description
When following the instructions in the Readme the build fails to compile on ```make gettools``` and returns an error.

## Steps to Reproduce
1. Install the requirements specified in the Readme.MD (go, nodejs, glide, protobuf, make)
2. Run the commands up to ```make gettools```
3. You will get the output above.

## Expected Result
No errors are returned and you can build from source.

## Actual Result
The following is the output from ```make gettools```:

```
The system cannot find the path specified.
process_begin: CreateProcess(NULL, jq --version, ...) failed.
FIND: Parameter format not correct
FIND: Parameter format not correct
go get -u github.com/gogo/protobuf/protoc-gen-gogoslick
go get -u github.com/jteeuwen/go-bindata/...
cd dashboard; npm install
The system cannot find the path specified.
make: * [gettools] Error 1
```

## Context
I'm not using a client

## Your Environment

- Nakama: Latest version from source
- Cockroach: N/A
- Environment name and version: N/A
- Operating System and version: Windows 10 Pro

**Comment by mofirouz** [comment]
Need to install `JQ` on Windows as it doesn't come bundled

**Comment by bokmcdok** [comment]
Installing JQ fixes the ```process_begin``` error, but I still get the path not specified errors.

**Comment by novabyte** [comment]
I've put together [some instructions](https://gist.github.com/novabyte/175b3d5ee5d0f278f5c3dfb1dc5b0305) on how to build from source on Windows. They're tested with Windows 10 Pro and assume usage of Powershell. The current Makefile build system assumes a few tools which are available on macOS/Linux but not on Windows.

I'll keep this ticket open to track changes I'll make to improve the ease of development on Windows. It's probable that we'll switch to another build system (like Bazel) which works on Windows as well as various other OSes. This may wait until the `dep` tool from the Go team has reached a maturity level which brings it into the Go compiler distribution. This would also help to simplify the build system.

**Comment by novabyte** [comment]
@bokmcdok We now embed all generated source dependencies in the repo so the project can be built with a simple `go build -i`. I still have plans to support full source builds with Bazel but given the sudden new flux around Go dependency management and `"vgo"` we'll likely wait a little longer for the dust to settle.
