### ISSUE TITLE
Critical DB operations are being cancelled in our hooks when client disconnects

### ISSUE THREAD

**Issue by brianwinterpixel** [heroiclabs/nakama#842]
## Description

We found a number of new accounts that are not being given critical initial metadata/wallet/storage data in authentication after hooks.

After searching for a while, we discovered the issue is being caused by the error `timeout: context canceled` in a storage request to read the default account configuration from a record.

Searching the issue, we found several forum posts ([here](https://forum.heroiclabs.com/t/error-context-canceled-and-context-deadline-exceed/122) and [here](https://forum.heroiclabs.com/t/error-encountered-context-canceled-while-in-goroutine/1609)) explaining why this is happening. To my understanding, the context is cancelled on client disconnect to reduce load, presuming the client won't be there to receive a response. The only problem is that we don't want nor expect this optimization. We now have dozens of accounts that are unable to use core features of our application due to metadata/wallet/storage records that were never initialized.

We're looking for a simple way to circumvent or disable this behavior in our Lua backend. If we can save resources by allowing storage operations to cancel on client disconnect, that should be an opt-in parameter.

## Steps to Reproduce

1. Add an after hook to AuthenticateEmail that performs storage operations
2. (??) we're not sure, perhaps people have bad connections or are closing the game in the middle of an auth request
3. Logs show `timeout: context canceled` for important storage operations

## Expected Result

Code should only error if Nakama loses DB connection or a DB operation takes way too long.

## Actual Result

Code can error anywhere we make DB requests.

## Context

Godot client, Lua backend

## Your Environment

Nakama 3.10 (forked from 1d0527e0)
Postgres
Docker

**Comment by mofirouz** [comment]
This is not a bug nor an unintended behaviour of the system. You've correctly [posted](https://forum.heroiclabs.com/t/what-to-do-about-timeout-context-canceled-in-critical-after-hook/2560) this on the forum and one the community members will reply soon.
