### ISSUE TITLE
Cursor Pagination is always returning the same cursor when limit is <100

### ISSUE THREAD

**Issue by JMCNAM-SN** [heroiclabs/nakama#848]
## Description
When calling the nkRuntime storageList using a cursor to return paginated data, if a limit is specified below the default value (100), then the cursor is always the same and I can't proceed beyond the 2nd page of data.

If the limit is null or >=100, then data is returned as expected.

## Steps to Reproduce
Method Call:
nk.storageList("00000000-0000-0000-0000-000000000000", collection, limit, cursor);

1. Pass limit value of 20 with null cursor.
2. First page of 20 records are returned along with the first cursor.
3. Pass limit of 20 with the first cursor.
4. Second page of 20 records are returned, new cursor is same as first.

## Expected Result
The second an subsequent cursors should be different and allow data to be returned in sets of 20 until last set of <=20, which should include a null cursor.

## Actual Result
Cursor is always the same after first page, so cannot proceed beyond the second page.

If the limit is null or >=100, then data is returned as expected.

## Context

- [ ] Other

## Your Environment

- Nakama: 3.10.0
- Database: postgres:12.2-alpine
- Environment name and version: Elasticbeanstalk

**Comment by Kwpa** [comment]
Also experiencing this

**Comment by Kwpa** [comment]
I am also finding I have this same issue in my project! More details to follow.

**Comment by JMCNAM-SN** [comment]
HI @sesposito,

Here's a link to the repo that is producing the issue.
https://github.com/supernimbus-dev/temp_ww_nakama/tree/main/src

IntitModule is in main.ts, it just registers the rpc 'server_endpoint_test'.
The first switch case, 'GetPlayers_Cursor', in endpoints.ts is where the call is made. The 'page' param is the  cursor string.
That method is in the same file, line 471, it just calls a get storage object method 'getDataList_Cursor'  in testClass.ts.

Here's a link to the above running on AWS that I use to test in Postman.
http://tempwwnakama-env.eba-fqussj7h.eu-west-1.elasticbeanstalk.com:7350/v2/rpc/server_endpoint_test?http_key=defaulthttpkey&unwrap=true&action=GetPlayers_Cursor&page=&pageSize=10&searchOption=&searchValue=

You can paste the returned cursor into the page parameter to test the issue.
Changing the pageSize parameter to 100 works as expected, otherwise same cursor is always returned.

On the insertion of storage objects, there is a 'CreatePlayers' case in 'server_endpoint_test' that added the data I'm testing.
Again, it calls a write storage object method in 'testClass.ts'.

Is this sufficent to let you try to reproduce the issue?



Also, this issue came up when trying to implement cursor pagination with Retool as a front-end UI.
They have cursor pagination settings on their table that I couldn't get working so got their support team to fix their side.
I gave them an app with a table that has 100+ rows to avoid the Nakama issue.
When they got back with a fix, I tried reducing the rows to 20.
The pagination works correctly like this in Retool, even though the cursor is still identical after the second call.
The Retool guys are unaware of Nakama, so I can't understand how it works in Retool and not in Postman.

**Comment by sesposito** [comment]
I do not have access to the linked repository, can you replicate the registered RPC function in a public gist please?

**Comment by JMCNAM-SN** [comment]
Here's the gist of it 
https://gist.github.com/JMCNAM-SN/e2229c1f750c95d2d1b43b392fca3097

**Comment by sesposito** [comment]
I tried to give a look at the code, but it's unfeasible for me to go through it all and try to understand if the issue is within the boundaries of the Nakama API or the custom code. I have failed to reproduce a case where the cursor wouldn't work as expected trying several combinations of inputs, so please provide a very simple example to reproduce it using simple nk runtime calls, otherwise I'm afraid the issue might lie elsewhere.

**Comment by zyro** [comment]
@JMCNAM-SN We were unable to reproduce the issue with Nakama 3.12.0, and the code provided is too complex to pick apart. If you can reproduce and have a smaller code sample (ideally a small sequence of `curl` commands that create/list storage objects) please reopen this and we'll take another look. 👍
