### ISSUE TITLE
Restricting max users & listing ongoing matches 

### ISSUE THREAD

**Issue by xysverma** [heroiclabs/nakama#85]
I would like a way to have a real time match which could be started without the need of another user and other users can join & leave ongoing matches after it has started but its restricted by number of users. In this case, user needs to see some info about a match without actually joining it so match metadata is additionally needed.

1) NMatchCreateMessage.Default() doesn't have any way to restrict number of users which can prohibit people from joining a game if its full. 

2) I need a way to have discovery for matches which are not full in terms of users & get count of matches which are full to be displayed to user ui. (Don't really want to use chat group as a hack since i need a long term solution).(Adding to #11 for non match maker game)

3) A dictionary setup to add some info about a game like level (easy / medium / hard). I have about 25 such levels. Need a way to find games filtered based on these key values. (Adding to #11 for non match maker game)

4) Some text/json metadata about a match which could be set while the game is going on 

5) Since its a real time match, need to way to remove/kick/ban users by other players for gameplay. 

I am open to lua scripting solution but it would be helpful if i could be guided on it. In short my use case is a customised match making which can have players joining leaving at anytime and could be started without any other user. Bots are supplied by unity client itself to keep game running if a user connects / disconnects.

**Comment by zyro** [comment]
All of these features are now available in Nakama 2 as part of the [authoritative multiplayer](https://heroiclabs.com/docs/gameplay-multiplayer-server-multiplayer/) and [match listing](https://heroiclabs.com/docs/gameplay-multiplayer-server-multiplayer/#match-listings) features.
