### ISSUE TITLE
nakama start not listen the port

### ISSUE THREAD

**Issue by diybl** [heroiclabs/nakama#851]
all port are  not listen 

i install it in centos7 with not docker

the log shows normal, but the port not listen, why??
i make sure the firewall is closed.
buet 7350 7351 not listen....

**Comment by diybl** [comment]
the relase version is nakama-3.11.0-linux-amd64.tar.gz

**Comment by zyro** [comment]
@diybl This is not a useful issue report. Looks like a topic better suited to the forum - https://forum.heroiclabs.com

Please include as much detail as you can, otherwise it will be hard to help.
