### ISSUE TITLE
[FEATURE] Group creation without an user

### ISSUE THREAD

**Issue by Rojoss** [heroiclabs/nakama#852]
Currently you must pass an userID when creating a group.
It would be useful if it were possible to create a group without an user.
For the use case we have some custom logic in place where we pre create a group for a set of users that can later join.
Also if we want to use the matchmaker to match users into groups rather than realtime matches it would make sense to have the ability to create a group when a match is found.

The current workaround I have in mind is create another system account.
Use the userID from this system account for the creation of the group.
Then when the first user joins the group it would promote that user to superadmin.
And finally remove the system user because we can't make the system user leave before there is another superadmin.

Alternatively we would have to store groups of users separately and then the first user creates the group.

**Comment by tomglenn** [comment]
Hi @Rojoss please see our response on the forum - https://forum.heroiclabs.com/t/adding-additional-indexed-properties-to-groups/2625/2.
