### ISSUE TITLE
password authentication failed for user root 

### ISSUE THREAD

**Issue by diybl** [heroiclabs/nakama#853]
database : cockroachdb
db run ok

when i run:

./nakama

the error:

"server/db.go:73","msg":"Error pinging database","error":"failed to connect to `host=localhost user=root database=nakama`: server error (ERROR: password authentication failed for user root (SQLSTATE 28000))"}

**Comment by zyro** [comment]
@diybl Your first destination for help must be the forum, not this issue tracker. Please post your problem on https://forum.heroiclabs.com with as much detail as possible about versions etc and we'll do our best to help. 👍
