### ISSUE TITLE
NotificationSendAll  duplicate key value violates unique constraint "notification_id_key" 

### ISSUE THREAD

**Issue by 435420057** [heroiclabs/nakama#861]
## Description
NotificationSendAll
ERROR: duplicate key value violates unique constraint \"notification_id_key\" (SQLSTATE 23505)

## Your Environment

- Nakama: 3.11.0

**Comment by zyro** [comment]
Fixed in 6e5af38a8b1ebb5630482df29ae5e2e638abea0e and will be part of the next release.
