### ISSUE TITLE
Concurrent read/write panic when modifying Lua tables defined at file-scope

### ISSUE THREAD

**Issue by brianwinterpixel** [heroiclabs/nakama#869]
## Description

We added a caching mechanism in Lua to reduce time wasted on marshalling data between Go and Lua for a large chunk of data we use very frequently. This was a noticeable performance improvement.

However, this caching mechanism is causing concurrency issues between Lua runtimes.

## Steps to Reproduce

This code should be able to reproduce the issue:
```lua

local nk = require("nakama")

local _cached_config = {}
local _cached_config_timestamp = 0
local _cache_duration = tonumber(nk.get_context().env.config_cache_duration) or 0

local function _actually_query_config()
	nk.logger_info("[config] _actually_query_config()")
	local storage_read = nk.storage_read({{
		collection = "winterpixel",
		key = "config"
	}})
	if storage_read[1] then
		return storage_read[1]["value"], storage_read[1]["version"]
	end
	nk.logger_error("[config] failed to query config")
	error("failed to query config")
	return nil, "*"
end

-- This function is used in other Lua modules very frequently.
-- Except for in the RPC below, the config returned here is never modified by other Lua modules.
local function query_config()
	if _cache_duration == nil or _cache_duration <= 0 then
		local value, version = _actually_query_config()
		return value
	end
	
	local current_time = math.floor(nk.time() / 1000) -- milliseconds to seconds
	if current_time - _cached_config_timestamp > _cache_duration then
		local value, version = _actually_query_config()
		_cached_config_timestamp = current_time

		-- NOTE: Reassigning _cached_config does not seem to cause any concurrency issues.
		_cached_config = value
	else
		nk.logger_info("[config] returning _cached_config()")
	end

	return _cached_config
end

-- ----------------------------

-- This RPC is called by clients to get the config.
-- We modify the config to send dynamic data to the client.
local function rpc_winterpixel_get_config(context, payload)
	local config = query_config()
	-- NOTE: If we do a shallow copy of this config table before modifying, we no longer encounter concurrency issues.
	-- Disabling lua_read_only_globals also resolves the issue.

	config["server_time"] = math.floor(nk.time() / 1000)
	-- [write other dynamic stuff to config file]

	return nk.json_encode(config)
end

nk.register_rpc(rpc_winterpixel_get_config, "winterpixel_get_config")

```

Call the above RPC frequently to trigger a concurrency panic.

## Expected Result

We expected the file-scope `local _cached_config` to be a local variable managed per Lua runtime. However, after debugging this issue my understanding is that file-scope variables are actually globals shared between Lua runtimes, set as read-only to avoid concurrency issues.

With this understanding, I expect that the code above should have triggered a panic for trying to modify a read-only global table. We encountered errors for trying to write to read-only globals while writing this code, but we didn't understand what it meant or why it was being triggered - all of our vars are local. It would have been helpful to have documentation on this subject.

## Actual Result

On occasion, a panic is triggered. Every case we've encountered involves a concurrency issue with modifying LTable strdict.

## Context

Godot

## Your Environment

Nakama 3.10 (forked from https://github.com/heroiclabs/nakama/commit/1d0527e00cdcb5106249e48baa40b03d37bf8b4f)
The only changes in our fork are:
"add rest interface with default raw json content type" https://github.com/heroiclabs/nakama/pull/775
"Switch order of http_key and Authorization header auth methods" https://github.com/heroiclabs/nakama/pull/772

Postgres

Docker

**Comment by zyro** [comment]
A panic output or stacktrace would be useful here, but I can try to guess what you're seeing.

I'm not sure your panic is due to Lua runtime instances sharing state, it might be because the instance is released back to the pool before the response is marshalled and sent to the client. In that case you may have concurrent reads and writes to your top-level fields if a following request grabs that instance to execute Lua code that may refresh/replace the cached value.

We generally recommend against top-level state like that - instead try using the localcache API, which is instance-wide and intended for this use case:
```lua
local value = "any Lua value"
nk.localcache_put("key", value)
```
```lua
local default_value = "optional, return this if cache did not have key"
local value = nk.localcache_get("key", default_value)
```
(More documentation on this coming soon.)

**Comment by brianwinterpixel** [comment]
> it might be because the instance is released back to the pool before the response is marshalled and sent to the client

I don't believe this is the case, because disabling lua_read_only_globals immediately solved the issue.

> instead try using the localcache API

Thanks for pointing this out, this should be a great help

**Comment by zyro** [comment]
I believe this has been addressed, feel free to re-open if necessary. 👍
