### ISSUE TITLE
Matchmaker with metadata

### ISSUE THREAD

**Issue by ArisTsevrenis** [heroiclabs/nakama#87]
Be able to enter matchmaking with data other user count. 

Having a MatchOpCode would be benefitial for example and a potentially easy solution but generally having "rules" to join would be good.

**Comment by nirolfa** [comment]
yes, custom matchmaking is needed -> shoud add some filter feature
(ex: match with only players between level 5 & 10 )

**Comment by AlimJaffer** [comment]
Hi @nirolfa , can you give me some further details on what you’re looking for in the matchmaker?  What is your specific use-case?

**Comment by prodigga** [comment]
Dont forget about https://github.com/heroiclabs/nakama/issues/11

The matchmaker really needs some love! :)

**Comment by novabyte** [comment]
@prodigga It's not been forgotten just keep an eye out on the issue tracker. 😉

**Comment by mofirouz** [comment]
This is now available on commit https://github.com/heroiclabs/nakama/commit/dc0a5964d8a1fe3dde79b1c6d1d8d0a59b71e216 and will be available in Nakama 1.1.0+
