### ISSUE TITLE
matchmaker.batch_pool_size is not used in code

### ISSUE THREAD

**Issue by Yanovskiy** [heroiclabs/nakama#879]
Hi, in documentation specifies the parameter **matchmaker.batch_pool_size** (Number of concurrent indexing batches that will be allocated. Default 32.), but i noticed that it is not used in the code. Is this ok?

**Comment by zyro** [comment]
@Yanovskiy Correct, that config parameter is deprecated and the code that used it is no longer present. If there's a problem you're aiming to solve please head over to [the forum](https://forum.heroiclabs.com) and post there, the issue tracker isn't the best place for a discussion like that.
