### ISSUE TITLE
From server side how to limit the number of the parties one user can create and message sending frequency? 

### ISSUE THREAD

**Issue by ownway88** [heroiclabs/nakama#881]
Hi,

I have some further test on the party functions. It seems one user can create unlimited number of parties. It seems that a malicious client can dry up the server resources by creating an infinite loop of party creation function, can’t it? I do not find any before hooks for Party related functions. How can I control the party behaviors from the server side? For example, I would like to forbid each player to create more than one party.

Additionally, I wonder where I can limit the frequency of the messages sent(Room, Group, DM) by users. I would like to limit the interval time of message sending to 1 sec for every player to avoid spamming.

I am still in progress on getting familiar with everything about Nakama, Kind of needing some help on those security mechanism in Nakama. Thanks

**Comment by zyro** [comment]
@ownway88 You're looking for [before hooks](https://heroiclabs.com/docs/nakama/server-framework/introduction/index.html#before-hooks) which let you intercept, validate, and throttle calls from the client based on the operation being attempted.

This discussion is better suited to [the forum](https://forum.heroiclabs.com), please head over there if you need further help.

**Comment by zyro** [comment]
Yes, before hooks for parties do exist same as before hooks on all other socket-based operations. The forum is the best community support resource, the issue tracker is not an appropriate venue for this topic.
