### ISSUE TITLE
[FEATURE REQUEST] Support with TrueNas Scale or TrueCharts

### ISSUE THREAD

**Issue by DreamersIncStudios** [heroiclabs/nakama#883]
Are there any plans or intent on getting nakama to run in TrueNas Scale in future ??

**Comment by redbaron** [comment]
You can run it as a docker image on the  TrueNAS, see [Docker instructions](https://heroiclabs.com/docs/nakama/getting-started/install/docker/)

**Comment by DreamersIncStudios** [comment]
The docker image pull defaults to cockroachDB and there is not way to switch to postgres since as from as I can tell these are not set up as environmental variables.

**Comment by mofirouz** [comment]
This doesn’t make sense as environment variables - we already have two separate Docker Compose files for the two databases.
