### ISSUE TITLE
Deleted/Removed messages are still there when I login again

### ISSUE THREAD

**Issue by GaNacereddine** [heroiclabs/nakama#894]
## Description
when I delete the messages using socket.RemoveChatMessageAsync(channelId, messageId) or directly using sql through the medium of a rpc function, and then login again the messages are still there.

what is the best way to delete a group of messages belonging to the same sender_id.

## Expected Result
message gone forever and all parties notified of deletion 

## Actual Result
message is gone but when login again the message is still there

## Context
I'm using the dot net client 3.3

## Your Environment

- Nakama: 3.10
- Database: 20.2 CockroachDB
- Environment name and version:
- Operating System and version: windows 11 docker 4.10

**Comment by zyro** [comment]
@GaNacereddine The socket `RemoveChatMessageAsync` function allows users to delete their own messages, it's not intended for users to delete messages sent by others in case that's what you're looking to do.

I'm not aware of any way messages would still be returned from a listing operation after being successfully deleted, especially if the rows were deleted via custom SQL. Can you provide a reproducible test case we can use to debug?

**Comment by GaNacereddine** [comment]
and yes I'm trying to implement an admin delete of all messages with same sender_Id.
