### ISSUE TITLE
Improve error message when ID used to register/login is used with self link

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#90]
This Unity code demonstrates the issue:

```csharp
var id = SystemInfo.deviceUniqueIdentifier;
var client = NClient.Default("defaultkey");
var message = NAuthenticateMessage.Device(id);
client.Register(message, (INSession session) => {
    client.Connect(session, (bool done) => {
        var badMessage = NSelfLinkMessage.Device(id);
        client.Send(badMessage, (bool completed) => {
            Debug.Log("Done.");
        }, (INError error) => {
            Debug.LogErrorFormat("Send error: code '{0}' - '{1}'.", error.Code, error.Message);
        });
    });
}, (INError error) => {
    Debug.LogErrorFormat("Send error: code '{0}' - '{1}'.", error.Code, error.Message);
});
```

The server logs show this error:

```
{"level":"warn","ts":"2017-07-10T19:52:01.713+0100","msg":"Could not link, query error","server":"nakama-a894","uid":"11c0a02f-cc8a-4efe-a1ce-b9a55cea4c17","sid":"13d1c676-0491-4d90-9105-582d5f3d945a","cid":"50304e1e-65fd-4b61-9639-f5695e8ff638","error":"pq: duplicate key value (id)=('2635CDEF-3AAB-5293-9611-F3364E35C807') violates unique constraint \"primary\""}
```

The database schema successfully prevents the user from linking a device ID already linked but we could do better to return a meaningful error to the client. The error currently returned by the server looks like "Could not link".

This was tested on Nakama 0.13.1 server and 0.6.1 Unity client.

**Comment by zyro** [comment]
Starting in the [1.0.0-rc1 release](https://github.com/heroiclabs/nakama/releases/tag/v1.0.0-rc.1) link operations that specify a device ID that's already in use correctly return "user link in use" errors. Look for `INError.ErrorCode.UserLinkInuse` in error responses in the [Nakama Unity client (version 0.7.0+)](https://github.com/heroiclabs/nakama-unity).
