### ISSUE TITLE
Godot 4 need a small refactoring

### ISSUE THREAD

**Issue by Mohsen7s** [heroiclabs/nakama#900]
## Description
Error and unrecognized NakamaClient after autoloaded in Godot 4.
NakamaClient need a few lines of refactoring so it fit to 4.x breaking changes

## Steps to Reproduce
1.Download Godot 4 beta or the last alpha
2. Autoload Nakama just like 3.x versions
3. Try to make a new NakamaClient instance

## Expected Result
It should work fine with godot 4.x versions

## Actual Result
Only errors

## Context
- [ ] Unity
- [ ] Unreal
- [ X] Godot

## Your Environment
Doesn't matter as it block at very first stage

**Comment by zyro** [comment]
This is the Nakama server repo, for issues related to the Nakama Godot client please head over to the relevant client repo here: https://github.com/heroiclabs/nakama-godot.
