### ISSUE TITLE
Separate Docker image with tags for postgres and Cockrockdb 

### ISSUE THREAD

**Issue by DreamersIncStudios** [heroiclabs/nakama#901]
## Your Environment

- Nakama: X.X.X
- Database:  postgres 
- Environment name and version:
- Operating System and version: truenas nas scale Debian 
https://www.truenas.com/docs/scale/scaleuireference/apps/docker/

Unable to use docker compose file with the truenas scale docker system. Default image pull from docker is the cockroachdb yml build. Is it  possible to have these tagged separately?

**Comment by zyro** [comment]
The Nakama [Dockerfile](https://github.com/heroiclabs/nakama/blob/master/build/Dockerfile) does not specify any database relationship at all, so I'm not sure this issue report is fully valid.

If you're using `docker-compose` (not to be confused with docker, the two are of course related but not exactly the same thing) and want to use Postgres then please use the appropriate YML config file: https://github.com/heroiclabs/nakama/blob/master/docker-compose-postgres.yml
