### ISSUE TITLE
Is ES6 supported already ?

### ISSUE THREAD

**Issue by Mohsen7s** [heroiclabs/nakama#905]
## Description
I have been reading nakama documents which state ("The JavaScript runtime is powered by the [goja VM](https://github.com/dop251/goja) which currently supports the JavaScript ES5 spec").
The last commit in gojaVM ES6 milestone to support ES6 standard was about 40 days ago and milestone is 100% implemented.
Howerver we get errors on `findIndex` function that introduced in ES6.
Is Nakama using old gojaVM ? if yes, is there any plan to upgrade to latest goja to support ES6 ?

Goja milestone and last ES6 commit:
https://github.com/dop251/goja/milestone/1
https://github.com/dop251/goja/issues/349

UPDATE:
Looks like nakama 3.13.1 release contains latest gojaVM according to pull :
https://github.com/heroiclabs/nakama/pull/896
So if nakama already supports ES6, please update old documents. Im confused between docs and release notes. Even in the nakama changelog didnt state ES6 upgrade.
## Your Environment  
Im using following image
`registry.heroiclabs.com/heroiclabs/nakama:3.13.1`

**Comment by zyro** [comment]
We will update documentation as needed, thanks for pointing that out!

Side note in future please include error messages, stack traces, code snippets, anything else you have available to help debug issues - "we get errors" is not enough detail to work with generally. 🙏
