### ISSUE TITLE
Apple receipt validation: not subscription receipt validation getting wrong function error

### ISSUE THREAD

**Issue by vyacheslav-sozap** [heroiclabs/nakama#907]
## Description
When validating Apple receipt from sandbox (haven't tried in production environment), sometimes receipt contains old transaction, which is, falsely, treated as subscription one. That causes "Subscription Receipt. Use the appropriate function instead." error.

## Steps to Reproduce
1. Have unfinished purchase
2. Purchase something else
3. Try to validate Apple receipt of the latest purchase (I'm using javascript method "purchaseValidateApple")

## Expected Result
Getting validation response

## Actual Result
Error "Subscription Receipt. Use the appropriate function instead." thrown

## Your Environment
- Nakama: 3.13.1
- Database: PostgreSQL from Docker image postgres:14.3-alpine
- Environment name and version: Docker image heroiclabs/nakama:3.13.1
- Operating System and version: WSL2 on Windows 10

## Note

As I see, receipt contains field "latest_receipt", looks like, despite what's Apple docs say, the fact that it is presented is not enough to say it is subscription receipt.

**Comment by zyro** [comment]
Fixed in https://github.com/heroiclabs/nakama/pull/912 and will be part of the next release.
