### ISSUE TITLE
Error 'prepared statement does not exist (SQLSTATE 26000)' when writing to the storage

### ISSUE THREAD

**Issue by rickysac** [heroiclabs/nakama#908]
## Description
When writing to the storage this error appears is some cases:
```
ERROR: prepared statement \"lrupsc_196_0\" does not exist (SQLSTATE 26000) at index.js:10177:7(173)
```
This happens randomly on different pods and at a different time through the day.
This error occurs in multiple RPCs and there isn’t a pattern.
Might be related to this log that points to a Go line
```
{"level":"error","ts":"2022-09-06T21:53:28.695Z","caller":"server/core_storage.go:484","msg":"Error writing storage objects.","error":"ERROR: prepared statement \"lrupsc_464_0\" does not exist (SQLSTATE 26000)"}
```

## Your Environment
- Nakama: 3.11.0-r12
- Database: AWS Aurora PostgreSQL 13.6

**Comment by redbaron** [comment]
Do you connect directly or through an RDS Proxy?

**Comment by rickysac** [comment]
RDS Proxy

Il ven 9 set 2022, 19:08 Maxim Ivanov ***@***.***> ha scritto:

**Comment by zyro** [comment]
Fixed on master and will be part of the next release.
