### ISSUE TITLE
Add a dedicated error code for when a user does not exist

### ISSUE THREAD

**Issue by novabyte** [heroiclabs/nakama#91]
The usual workflow for Login/Register in Unity is:

```csharp
INSession storedSession = null;
var id = SystemInfo.deviceUniqueIdentifier;
var message = NAuthenticateMessage.Device(id);
client.Login(message, (INSession session) => {
  storedSession = session;
}, (INError error) => {
  if (error.Message.Equals("ID not found")) { // problem!
    client.Register(message, (INSession session) => {
      storedSession = session;
    }, (INError error) => {
      Debug.LogErrorFormat("Error: code '{0}' - '{1}'.", error.Code, error.Message);
    });
  } else {
    Debug.LogErrorFormat("Error: code '{0}' - '{1}'.", error.Code, error.Message);
  }
});
```

You can see a bigger and more complete example of the workflow [here](https://github.com/heroiclabs/nakama-unity/blob/cdm-unitythread-dispatch/example/UnityMainThreadDispatch.cs).

The sequence works well except it relies on a string match against `"ID not found"` instead of a check against an enum code for the error. This is because we added error codes after the register/login design had been built. Nevertheless a string match condition is brittle because it relies on us never updating the error message returned by the server.

We should add a new enum code like `NoUser` to represent bad login attempts. Thoughts?

**Comment by anthonymurraygd** [comment]
Makes sense to me!

**Comment by zyro** [comment]
The [1.0.0-rc1 release](https://github.com/heroiclabs/nakama/releases/tag/v1.0.0-rc.1) returns a dedicated "user not found" error code when a login fails because the user does not exist. Look for `INError.UserNotFound` in error responses in the [Nakama Unity client (version 0.7.0+)](https://github.com/heroiclabs/nakama-unity).
