### ISSUE TITLE
Google Play Games v0.11.x is incompatible with Nakama 3.13.1

### ISSUE THREAD

**Issue by DaveOak** [heroiclabs/nakama#915]
I’ve upgraded to GooglePlayGamesPlugin-0.11.01 and modified my code to request a token by calling PlayGamesPlatform.Instance.RequestServerSideAccess instead of
PlayGamesPlatform.Instance.GetUserId() which is now deprecated.

However, this token is not being accepted by AuthenticateGoogleAsync.

The following is logged by the server:

`{"level":"info","ts":"2022-09-23T17:20:29.337Z","caller":"server/core_authenticate.go:630","msg":"Could not authenticate Google profile.","error":"google id token invalid"}`

I have upgraded the client library to 3.5.0 and the server to Nakama 3.13.1+2000e4b8 but the error persists.

https://github.com/playgameservices/play-games-plugin-for-unity#readme

**Comment by flaviofernandes004** [comment]
Hello @DaveOak,

I will require your help to debug this issue if you are available, I will need more details about the token. Could you reach out to us via email? 🙇

**Comment by DaveOak** [comment]
Hi Flavio

Unfortunately I have some pressing issues to resolve and don’t have the time right now. I got around this problem for now by downgrading to the previous version of Google Play Games.
If it helps at all, Unity game server had the same issue:

https://forum.unity.com/threads/google-play-authentication.1266272/ <https://forum.unity.com/threads/google-play-authentication.1266272/>

I haven’t seen a discussion on how the server validates the new token however.

Regards
Dave

**Comment by oscargoldman** [comment]
Any development on this issue?

**Comment by jayaram9877** [comment]
Anu update?

**Comment by flaviofernandes004** [comment]
Thx @andreparodi-bandai. I will take a look. Could you send us a faulty token via email (contact@heroiclabs.com)? I believe it would help me debug this problem.

**Comment by flaviofernandes004** [comment]
Release 3.16.0 includes a fix for this which requires a new configuration as described in the [docs](https://heroiclabs.com/docs/nakama/concepts/authentication/#google).

Additional info can be found [here](https://github.com/heroiclabs/nakama/pull/997) as well.
