### ISSUE TITLE
[FEATURE REQUEST] Add a member to the group in the devconsole

### ISSUE THREAD

**Issue by ftkg** [heroiclabs/nakama#923]
In the group members tab, add the ability to add a new member to the group. 
 A simple player id textfield and an add button.

**Comment by yoyopuyo** [comment]
Feature request is coming from me and now that I think about it, it could also be interesting to add join request.
For example we have a bug in live when we have like 20 requests. It's not really easy to test so it would be good to be able to add members or join request. 
We could even have the textfield understand playerId1,playerId2,...
But that's just a suggestion.
thanks
