### ISSUE TITLE
dont work in module ES6

### ISSUE THREAD

**Issue by Mehrdadgame** [heroiclabs/nakama#933]
Hi there
I worked with Nakama but i have problem. when change target to ES6 in don't run server .

error : nakama_nakama_1 exited with code 2

how solve this problem ?

## Context

- [ ] Unity

## Your Environment

- Nakama: last
- Database: last

**Comment by zyro** [comment]
As you'll see [in the documentation](https://heroiclabs.com/docs/nakama/server-framework/typescript-runtime/#compatibility), ES5 is the currently supported target.

Side note: please include error messages and stack traces with issue reports, and `last` is not a valid Nakama or database version number.

**Comment by Mehrdadgame** [comment]
Hi @zyro
 thanks for answer question but  i need ES6 for write code in nakama project .
Nakama just work with es5?

error : nakama  

goroutine 1 [running]:
nakama_1       | github.com/dop251/goja.(*Runtime).runWrapped.func1()
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/runtime.go:2396 +0xdc
nakama_1       | panic({0x1aca660, 0xc0001be870})
nakama_1       |        runtime/panic.go:884 +0x212
nakama_1       | github.com/dop251/goja.(*vm).try.func1()
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/vm.go:626 +0x70f
nakama_1       | panic({0x1aca660, 0xc0001be870})
nakama_1       |        runtime/panic.go:884 +0x212
nakama_1       | github.com/heroiclabs/nakama/v3/server.(*RuntimeJavascriptInitModule).getMatchHookFnIdentifier(0xc0003ff650, 0x18?, 0x7f4eac9945b8?, {0xc0003c40c3, 0xb}, {0xc000280358, 0x5}, {0x1c844f9, 0x9
})
nakama_1       |        github.com/heroiclabs/nakama/v3/server/runtime_javascript_init.go:1412 +0x7d5
nakama_1       | github.com/heroiclabs/nakama/v3/server.(*RuntimeJavascriptInitModule).extractMatchFnKey(0x2286338?, 0xc0001be7e0?, {0xc000280358, 0x5}, {0x1c844f9, 0x9})
nakama_1       |        github.com/heroiclabs/nakama/v3/server/runtime_javascript_init.go:1363 +0x96
nakama_1       | github.com/heroiclabs/nakama/v3/server.(*RuntimeJavascriptInitModule).registerMatch.func1({{0x2286338, 0xc0000c0630}, {0xc0001445c0, 0x2, 0x4}})
nakama_1       |        github.com/heroiclabs/nakama/v3/server/runtime_javascript_init.go:1249 +0x25b
nakama_1       | github.com/dop251/goja.(*vm)._nativeCall(0xc0005ae300, 0xc000445680, 0x2)
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/vm.go:3231 +0x1e3
nakama_1       | github.com/dop251/goja.call.exec(0xb?, 0xc0005ae300)
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/vm.go:3203 +0x2fb
nakama_1       | github.com/dop251/goja.(*vm).run(0xc0005ae300)
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/vm.go:495 +0x8b
nakama_1       | github.com/dop251/goja.(*baseJsFuncObject)._call(0xc0004a20c0, {0xc000423300?, 0x4, 0xc00076b160?}, {0x0?, 0x0}, {0x2286c20?, 0x2dd6c20?})
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/func.go:305 +0x3f8
nakama_1       | github.com/dop251/goja.(*baseJsFuncObject).call(...)
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/func.go:315
nakama_1       | github.com/dop251/goja.(*baseJsFuncObject).Call(0xc0000a0fc0?, {{0x2286c20, 0x2dd6c20}, {0xc000423300, 0x4, 0x4}})
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/func.go:267 +0xa5
nakama_1       | github.com/dop251/goja.AssertFunction.func1.1()
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/runtime.go:2356 +0x74
nakama_1       | github.com/dop251/goja.(*vm).try(0xc0005ae300, 0x0?)
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/vm.go:634 +0x18a
nakama_1       | github.com/dop251/goja.(*Runtime).runWrapped(0xc000466380, 0x7f4eac9945b8?)
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/runtime.go:2400 +0x7c
nakama_1       | github.com/dop251/goja.AssertFunction.func1({0x2286c20?, 0x2dd6c20?}, {0xc000423300?, 0x8?, 0xc0001f9600?})
nakama_1       |        github.com/dop251/goja@v0.0.0-20220806120448-1444e6b94559/runtime.go:2355 +0x92
nakama_1       | github.com/heroiclabs/nakama/v3/server.evalRuntimeModules(0xc0005ae200, 0xc000612220, 0xc0005a04e0, 0xc0001d82d0, {0x2279680, 0xc0001f9600}, 0xc00016aa80?, 0xc000480900, 0x0)
nakama_1       |        github.com/heroiclabs/nakama/v3/server/runtime_javascript.go:2040 +0x76e
nakama_1       | github.com/heroiclabs/nakama/v3/server.NewRuntimeProviderJS(_, _, _, _, _, {_, _}, _, {0x2283a00, 0xc0001151a0}, ...)
nakama_1       | github.com/heroiclabs/nakama/v3/server.NewRuntime({0x2277080, 0xc00026f480}, 0xc000115200?, 0xc000115200?, 0xc000124dd0?, 0x2b93740?, 0x2d9e9c0?, {0x22870f8?, _}, 0xc00045c0a0, ...)
nakama_1       |        github.com/heroiclabs/nakama/v3/server/runtime.go:612 +0xdd5
nakama_1       | main.main()
nakama_1       |        main.go:156 +0x161c

**Comment by zyro** [comment]
@Mehrdadgame I suggest [creating a forum thread](https://forum.heroiclabs.com/) to discuss ES6. Yes, at the moment Nakama's JS runtime supports ES5.
