### ISSUE TITLE
Will "Nakama" increase the "P2P" network capability?

### ISSUE THREAD

**Issue by 316902108** [heroiclabs/nakama#939]
Will "Nakama" increase the "P2P" network capability?
I think this is a good network capability！
I hope "Nakama" can have this ability!
Use the "Nakama" server as the judge to build a "P2P" network bridge for the client。

**Comment by redbaron** [comment]
Nakama offers extensible subsystems for various aspects of a multiplayer game, such as party system, matches, chats, state storage and realtime RPC.

With custom RPC functions you can implement almost any logic imaginable, which fits request-response model.

**Comment by zyro** [comment]
Seems this may be a discussion more appropriate for [the forum](https://forum.heroiclabs.com/) instead.
