### ISSUE TITLE
jsonwebtoken(jwt) add module

### ISSUE THREAD

**Issue by Mehrdadgame** [heroiclabs/nakama#952]
Hi 
I working with Nakama typescript 
I want use jsonwebtoken for login custom but i have error in Tsconfig.json and change    "module": "System" in tsconfig and add 
let jws= require('jsonwebtoken');
error on start server .
Failed initializing runtime modules","error":"ReferenceError: require is not defined at index.js:84:18(54)

## Description

Tsconfig.json :

   "compilerOptions": {
    "target": "ES5",
    "module": "System",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outFile": "./modules/index.js",
    "typeRoots": [
      "./node_modules" , "./node_modules/@types"
    ]
  }
## Expected Result

const verifyAndParseJwt = function (secretKey: string, jwtt: string , logger:nkruntime.Logger): Claims {
  let claims: Claims={id:"", username:""};
  // Use your favourite JWT library to verify the signature and decode the JWT contents

jws.sign({ foo: jwtt }, secretKey, { algorithm: 'RS256' }, function(err:any, token:any) {
    logger.info(token + " %%%%%%%%%%%%%%%%%%%%%%");
    claims.id=token.id;
    claims.username = token.username;
  });
 
## Context

- [ ] Unity

**Comment by Mehrdadgame** [comment]
![sss](https://user-images.githubusercontent.com/72225846/202856253-3f07b43f-1722-456a-baf6-3172c31d104a.svg)
![bbb](https://user-images.githubusercontent.com/72225846/202856320-80ca15d4-cb39-4e84-9d5e-a225a4112e11.svg)

**Comment by novabyte** [comment]
@Mehrdadgame The JavaScript runtime in the game server is not a Node runtime; it is also sandboxed for performance and security reasons. We already provide a `jwtGenerate` function in the server framework you can use to generate the token structure you need: 

https://heroiclabs.com/docs/nakama/server-framework/typescript-runtime/function-reference/#jwtGenerate

Hope this helps.
