### ISSUE TITLE
Apple signIn on android

### ISSUE THREAD

**Issue by kennir** [heroiclabs/nakama#957]
Hi 

I want use apple signin on an android device, but apple does not provide the SDK for android, So I can only authenticate through the http, then get the id_token via redirect_uri callback, and then authorize to nakama using nakama's REST API. My question is how do I get the session back to unity's client

Thanks

**Comment by novabyte** [comment]
> I want use apple signin on an android device

@kennir Are you sure Apple allows this as part of their terms of service? I'm unsure what restrictions Apple places on the use of their services where they choose not to officially support it.

> My question is how do I get the session back to unity's client

Which session are you trying to get back to the Unity client?
