### ISSUE TITLE
Possible minor bug in the walletUpdate method

### ISSUE THREAD

**Issue by SomethingWithComputers** [heroiclabs/nakama#960]
## Description
I've noticed the ledger for the wallet doesn't automatically get updated, even though the documentation states it should. The documentation states the `updateLedger` parameter defaults to true.
```
Update user wallet.
Params:

userId – User ID.
changeset – Object with the wallet changeset data.
metadata – Opt. Additional metadata to tag the wallet update with.
updateLedger – Opt. Whether to record this update in the ledger. Default true.
Throws:
TypeError | GoError
```

## Steps to reproduce
Executing `nk.walletUpdate(userId, changeset, metadata)` does not seem to leave an entry in the ledger. But `nk.walletUpdate(userId, changeset, metadata, true)` does. So perhaps the default values aren't set correctly in this version?

Would be nice if somebody can confirm/replicate this, I've tried it on a clean install and I'm getting the same result.
## Expected Result
An entry is added to the user's wallet's ledger.

## Actual Result
An entry is *not* added to the user's wallet's ledger.

## Context
n/a

## Your Environment
Versions: Nakama 3.13.1, Docker, TypeScript, all on Mac.

**Comment by zyro** [comment]
@SomethingWithComputers Thanks for pointing this out, the default is indeed `false` and we'll correct the documentation to match this! 👍
