### ISSUE TITLE
httpRequest does not support method "delete"

### ISSUE THREAD

**Issue by portwatcher** [heroiclabs/nakama#961]
I firstly found the lack of "delete" in TypeScript definition, as https://github.com/heroiclabs/nakama-common/issues/105 described

Then I found the bug still exsits as Go method throws error
```
{"level":"error","ts":"2022-12-18T05:59:30.920Z","caller":"server/runtime_javascript_logger.go:94","msg":"Invalid method must be one of: 'get', 'post', 'put', 'patch'.","mid":"4cc92f85-c48d-489b-95ce-c5cc1f0bd6a7"}
```

This error comes from:

https://github.com/heroiclabs/nakama/blob/fa2b7259984b9e14259928e0f42cc52a82e63b69/server/runtime_javascript_nakama.go#L595

When will this bugfix be shipped? If not so soon, I will write a http proxy server that receives `post` requests only to fix my use case.

**Comment by mofirouz** [comment]
Please feel free to open a Pull Request and contribute to the project if you need this urgently. If you can do this by end of week (23/12/22), we might be able to add this to the final release of 2022.

**Comment by portwatcher** [comment]
I don't write go often but this seems to be a very simple problem. I'll try to fix and pass tests

**Comment by portwatcher** [comment]
Actually this has been fixed in master branch as the code shows (it already contains `delete` and `head`):

https://github.com/heroiclabs/nakama/blob/fa2b7259984b9e14259928e0f42cc52a82e63b69/server/runtime_javascript_nakama.go#L595

I just need to wait for the final release of 2022! Thank you for replying!

**Comment by portwatcher** [comment]
@mofirouz
sorry for reopening this again. I'm wondering when will this fix be released?
I need to call `nk.httpRequest` with `delete` method to remove headless game servers properly through docker http api.
The game project almost comes to alpha testing.
